"""
Example Mode Presets — Complete, self-contained input records for each tool.

Each preset contains everything needed to:
1. Display to the user (name, thumbnail)
2. Build a deterministic cache key
3. Call the MCP provider directly (all params included)

Input images will be generated by Gemini and stored in GCS public bucket.
Until generated, image_url is a placeholder that the generate_example_inputs
script will replace with actual GCS URLs.

Target audience: Small business / personal users (Taiwan SMB focus).
NO luxury items. Products: bubble tea, fried chicken, bento, soap, cake, etc.
"""

from typing import Any, Dict, List

# GCS bucket base URL for example input images
GCS_EXAMPLES_BASE = "https://storage.googleapis.com/vidgo-media-vidgo-ai/examples"


# ─────────────────────────────────────────────────────────────────────────────
# BACKGROUND REMOVAL — only needs image_url, no prompt
# ─────────────────────────────────────────────────────────────────────────────

BACKGROUND_REMOVAL_PRESETS: List[Dict[str, Any]] = [
    {
        "id": "bg-bubbletea",
        "name": {"en": "Bubble Tea", "zh": "珍珠奶茶"},
        "image_url": f"{GCS_EXAMPLES_BASE}/bg/bubbletea.png",
        "params": {},
        "gemini_prompt": "A single cup of bubble tea with tapioca pearls, product photography on a simple background, high quality",
    },
    {
        "id": "bg-fried-chicken",
        "name": {"en": "Fried Chicken", "zh": "炸雞排"},
        "image_url": f"{GCS_EXAMPLES_BASE}/bg/fried-chicken.png",
        "params": {},
        "gemini_prompt": "A piece of crispy fried chicken on a plate, product photography, simple background",
    },
    {
        "id": "bg-bento",
        "name": {"en": "Bento Box", "zh": "便當"},
        "image_url": f"{GCS_EXAMPLES_BASE}/bg/bento.png",
        "params": {},
        "gemini_prompt": "A traditional Taiwanese bento lunch box with rice and side dishes, product photo, simple background",
    },
    {
        "id": "bg-soap",
        "name": {"en": "Handmade Soap", "zh": "手工皂"},
        "image_url": f"{GCS_EXAMPLES_BASE}/bg/soap.png",
        "params": {},
        "gemini_prompt": "Handmade natural soap bars with herbs, product photography, simple background",
    },
    {
        "id": "bg-cake",
        "name": {"en": "Birthday Cake", "zh": "生日蛋糕"},
        "image_url": f"{GCS_EXAMPLES_BASE}/bg/cake.png",
        "params": {},
        "gemini_prompt": "A small birthday cake with cream frosting, product photography, simple background",
    },
    {
        "id": "bg-coffee",
        "name": {"en": "Coffee Beans", "zh": "咖啡豆"},
        "image_url": f"{GCS_EXAMPLES_BASE}/bg/coffee.png",
        "params": {},
        "gemini_prompt": "A bag of roasted coffee beans with a few beans scattered, product photography, simple background",
    },
]


# ─────────────────────────────────────────────────────────────────────────────
# PRODUCT SCENE — image_url (product) + prompt (scene description)
# ─────────────────────────────────────────────────────────────────────────────

PRODUCT_SCENE_PRESETS: List[Dict[str, Any]] = [
    {
        "id": "ps-bubbletea-studio",
        "name": {"en": "Bubble Tea - Studio", "zh": "珍珠奶茶 - 攝影棚"},
        "image_url": f"{GCS_EXAMPLES_BASE}/ps/bubbletea.png",
        "params": {
            "prompt": "Professional studio lighting, clean white backdrop, soft shadows, product photography",
            "scene_type": "studio",
        },
        "gemini_prompt": "A single cup of bubble tea with tapioca pearls, isolated product photo on white background",
    },
    {
        "id": "ps-chicken-lifestyle",
        "name": {"en": "Fried Chicken - Lifestyle", "zh": "炸雞排 - 生活風格"},
        "image_url": f"{GCS_EXAMPLES_BASE}/ps/fried-chicken.png",
        "params": {
            "prompt": "Casual lifestyle setting, warm kitchen background, natural light, inviting atmosphere",
            "scene_type": "lifestyle",
        },
        "gemini_prompt": "Crispy fried chicken pieces in a paper basket, isolated product photo on white background",
    },
    {
        "id": "ps-bento-minimal",
        "name": {"en": "Bento - Minimal", "zh": "便當 - 極簡"},
        "image_url": f"{GCS_EXAMPLES_BASE}/ps/bento.png",
        "params": {
            "prompt": "Minimalist clean composition, solid color background, geometric shadows",
            "scene_type": "minimal",
        },
        "gemini_prompt": "A Taiwanese bento box with rice and side dishes, isolated product photo on white background",
    },
    {
        "id": "ps-soap-nature",
        "name": {"en": "Soap - Nature", "zh": "手工皂 - 自然"},
        "image_url": f"{GCS_EXAMPLES_BASE}/ps/soap.png",
        "params": {
            "prompt": "Natural outdoor setting with green leaves and soft sunlight, organic feel",
            "scene_type": "nature",
        },
        "gemini_prompt": "Handmade soap bars with dried herbs, isolated product photo on white background",
    },
    {
        "id": "ps-cake-seasonal",
        "name": {"en": "Cake - Seasonal", "zh": "蛋糕 - 季節性"},
        "image_url": f"{GCS_EXAMPLES_BASE}/ps/cake.png",
        "params": {
            "prompt": "Festive seasonal decoration, warm autumn colors, cozy atmosphere",
            "scene_type": "seasonal",
        },
        "gemini_prompt": "A small birthday cake with cream frosting, isolated product photo on white background",
    },
    {
        "id": "ps-coffee-urban",
        "name": {"en": "Coffee - Urban", "zh": "咖啡 - 都會"},
        "image_url": f"{GCS_EXAMPLES_BASE}/ps/coffee.png",
        "params": {
            "prompt": "Modern urban cafe setting, exposed brick, morning light, city vibes",
            "scene_type": "urban",
        },
        "gemini_prompt": "A bag of roasted coffee beans, isolated product photo on white background",
    },
]


# ─────────────────────────────────────────────────────────────────────────────
# EFFECT (Style Transfer) — image_url (source) + prompt (style)
# ─────────────────────────────────────────────────────────────────────────────

EFFECT_PRESETS: List[Dict[str, Any]] = [
    {
        "id": "fx-bubbletea-anime",
        "name": {"en": "Bubble Tea - Anime", "zh": "珍珠奶茶 - 動漫風"},
        "image_url": f"{GCS_EXAMPLES_BASE}/fx/bubbletea.png",
        "params": {
            "prompt": "anime style, vibrant colors, cel shading, bold outlines, Japanese animation aesthetic",
        },
        "gemini_prompt": "A cup of bubble tea with tapioca pearls, bright colorful product photo",
    },
    {
        "id": "fx-chicken-ghibli",
        "name": {"en": "Fried Chicken - Ghibli", "zh": "炸雞 - 吉卜力風"},
        "image_url": f"{GCS_EXAMPLES_BASE}/fx/fried-chicken.png",
        "params": {
            "prompt": "Studio Ghibli style, hand-painted watercolor, soft warm tones, Miyazaki aesthetic",
        },
        "gemini_prompt": "Crispy fried chicken on a plate, warm inviting food photo",
    },
    {
        "id": "fx-bento-cartoon",
        "name": {"en": "Bento - Cartoon", "zh": "便當 - 卡通風"},
        "image_url": f"{GCS_EXAMPLES_BASE}/fx/bento.png",
        "params": {
            "prompt": "cartoon style, bright flat colors, playful illustration, fun and cheerful",
        },
        "gemini_prompt": "A Taiwanese bento box with colorful side dishes, appetizing food photo",
    },
    {
        "id": "fx-cake-oil-painting",
        "name": {"en": "Cake - Oil Painting", "zh": "蛋糕 - 油畫風"},
        "image_url": f"{GCS_EXAMPLES_BASE}/fx/cake.png",
        "params": {
            "prompt": "oil painting style, thick brushstrokes, rich warm palette, classical still life aesthetic",
        },
        "gemini_prompt": "A birthday cake with cream frosting and berries, elegant food photo",
    },
    {
        "id": "fx-soap-watercolor",
        "name": {"en": "Soap - Watercolor", "zh": "手工皂 - 水彩風"},
        "image_url": f"{GCS_EXAMPLES_BASE}/fx/soap.png",
        "params": {
            "prompt": "watercolor painting style, soft translucent washes, delicate flowing edges, pastel tones",
        },
        "gemini_prompt": "Handmade soap bars with lavender and herbs, soft natural product photo",
    },
]


# ─────────────────────────────────────────────────────────────────────────────
# ROOM REDESIGN — image_url (room photo) + prompt (style description)
# ─────────────────────────────────────────────────────────────────────────────

ROOM_REDESIGN_PRESETS: List[Dict[str, Any]] = [
    {
        "id": "room-living-modern",
        "name": {"en": "Living Room - Modern", "zh": "客廳 - 現代極簡"},
        "image_url": f"{GCS_EXAMPLES_BASE}/room/living-room.png",
        "params": {
            "prompt": "Modern minimalist living room, clean lines, warm lighting, neutral tones, functional furniture",
            "style": "modern",
            "room_type": "living_room",
        },
        "gemini_prompt": "An empty living room with basic furniture, simple interior photo, clean space",
    },
    {
        "id": "room-bedroom-nordic",
        "name": {"en": "Bedroom - Nordic", "zh": "臥室 - 北歐風"},
        "image_url": f"{GCS_EXAMPLES_BASE}/room/bedroom.png",
        "params": {
            "prompt": "Nordic Scandinavian bedroom, natural wood, white walls, cozy textiles, simple elegant",
            "style": "nordic",
            "room_type": "bedroom",
        },
        "gemini_prompt": "A simple bedroom with a bed and nightstand, basic interior photo, clean space",
    },
    {
        "id": "room-kitchen-industrial",
        "name": {"en": "Kitchen - Industrial", "zh": "廚房 - 工業風"},
        "image_url": f"{GCS_EXAMPLES_BASE}/room/kitchen.png",
        "params": {
            "prompt": "Industrial style kitchen, exposed brick, metal shelving, pendant lights, cafe atmosphere",
            "style": "industrial",
            "room_type": "kitchen",
        },
        "gemini_prompt": "A basic kitchen with countertop and cabinets, simple interior photo",
    },
    {
        "id": "room-bathroom-zen",
        "name": {"en": "Bathroom - Zen", "zh": "浴室 - 禪風"},
        "image_url": f"{GCS_EXAMPLES_BASE}/room/bathroom.png",
        "params": {
            "prompt": "Zen Japanese bathroom, natural stone, wood accents, minimal fixtures, peaceful atmosphere",
            "style": "zen",
            "room_type": "bathroom",
        },
        "gemini_prompt": "A simple bathroom with bathtub and sink, basic interior photo",
    },
    {
        "id": "room-living-japanese",
        "name": {"en": "Living Room - Japanese", "zh": "客廳 - 日式"},
        "image_url": f"{GCS_EXAMPLES_BASE}/room/living-japanese.png",
        "params": {
            "prompt": "Japanese style living room, tatami mats, low furniture, shoji screens, natural materials",
            "style": "japanese",
            "room_type": "living_room",
        },
        "gemini_prompt": "A simple living room with low table and floor cushions, basic interior photo",
    },
]


# ─────────────────────────────────────────────────────────────────────────────
# SHORT VIDEO — image_url (source) + prompt (video description)
# ─────────────────────────────────────────────────────────────────────────────

SHORT_VIDEO_PRESETS: List[Dict[str, Any]] = [
    {
        "id": "vid-bubbletea-showcase",
        "name": {"en": "Bubble Tea Showcase", "zh": "珍珠奶茶展示"},
        "image_url": f"{GCS_EXAMPLES_BASE}/vid/bubbletea.png",
        "params": {
            "prompt": "Smooth zoom into bubble tea cup, tapioca pearls floating, steam rising, appetizing showcase",
            "duration": 5,
        },
        "gemini_prompt": "A cup of bubble tea with tapioca pearls, top-down product photo, vibrant colors",
    },
    {
        "id": "vid-chicken-promo",
        "name": {"en": "Fried Chicken Promo", "zh": "炸雞促銷"},
        "image_url": f"{GCS_EXAMPLES_BASE}/vid/fried-chicken.png",
        "params": {
            "prompt": "Dynamic pan around crispy fried chicken, golden crust close-up, sizzling hot, food advertisement",
            "duration": 5,
        },
        "gemini_prompt": "Crispy golden fried chicken on a plate, food photography, warm lighting",
    },
    {
        "id": "vid-coffee-brand",
        "name": {"en": "Coffee Brand Intro", "zh": "咖啡品牌介紹"},
        "image_url": f"{GCS_EXAMPLES_BASE}/vid/coffee.png",
        "params": {
            "prompt": "Slow pour of coffee beans falling, rich brown tones, aromatic atmosphere, brand storytelling",
            "duration": 5,
        },
        "gemini_prompt": "Roasted coffee beans scattered on a wooden surface, warm food photography",
    },
    {
        "id": "vid-skincare-tutorial",
        "name": {"en": "Skincare Tutorial", "zh": "保養品教學"},
        "image_url": f"{GCS_EXAMPLES_BASE}/vid/skincare.png",
        "params": {
            "prompt": "Gentle squeeze of skincare serum dropping onto surface, clean minimal, beauty product showcase",
            "duration": 5,
        },
        "gemini_prompt": "A skincare serum bottle with dropper, clean minimal product photo, white background",
    },
    {
        "id": "vid-backpack-outdoor",
        "name": {"en": "Backpack Outdoor", "zh": "書包戶外"},
        "image_url": f"{GCS_EXAMPLES_BASE}/vid/backpack.png",
        "params": {
            "prompt": "Student backpack in outdoor setting, swaying in breeze, nature background, lifestyle video",
            "duration": 5,
        },
        "gemini_prompt": "A student backpack on grass with books beside it, outdoor lifestyle photo",
    },
]


# ─────────────────────────────────────────────────────────────────────────────
# AI AVATAR — avatar image_url + script text (prompt)
# Avatar images are pre-existing; scripts from try_prompts.py
# ─────────────────────────────────────────────────────────────────────────────

AVATAR_PRESETS: List[Dict[str, Any]] = [
    {
        "id": "avatar-yijun-thermos",
        "name": {"en": "Yi-Jun - Thermos", "zh": "怡君 - 保溫瓶"},
        "image_url": f"{GCS_EXAMPLES_BASE}/avatar/yijun.png",
        "params": {
            "text": "我爸是做鐵工的，每天帶一個便宜保溫瓶，總是會漏水。所以我花了兩年研發這款真空保溫瓶——雙層不鏽鋼，保溫12小時。去年到現在賣超過8000個，只要599元。30天不滿意全額退費，放心試！",
            "language": "zh-TW",
            "voice_id": "xiaoxiao",
            "duration": 30,
            "aspect_ratio": "9:16",
        },
        "gemini_prompt": "Professional headshot of a young Taiwanese woman in a white blouse, friendly smile, clean background, spokesperson look",
    },
    {
        "id": "avatar-zhiwei-ricecooker",
        "name": {"en": "Zhi-Wei - Rice Cooker", "zh": "志偉 - 電子鍋"},
        "image_url": f"{GCS_EXAMPLES_BASE}/avatar/zhiwei.png",
        "params": {
            "text": "你看——我只要放米、加水、按一個按鈕，25分鐘後就是粒粒分明的完美白飯，每次都一樣。這台智慧電子鍋有8種模式、不沾內鍋、24小時預約。網路上超過1500則五星評價。只要1290元，在家就能煮出餐廳等級的飯。本週免運費！",
            "language": "zh-TW",
            "voice_id": "yunxi",
            "duration": 30,
            "aspect_ratio": "9:16",
        },
        "gemini_prompt": "Professional headshot of a young Taiwanese man in a casual white t-shirt, friendly smile, clean background, spokesperson look",
    },
    {
        "id": "avatar-yating-shampoo",
        "name": {"en": "Ya-Ting - Shampoo", "zh": "雅婷 - 洗髮精"},
        "image_url": f"{GCS_EXAMPLES_BASE}/avatar/yating.png",
        "params": {
            "text": "阿嬤以前都用山上採的天然草本洗頭，80歲頭髮還是又黑又亮。我把她的配方做成了這瓶洗髮精——無矽靈、無硫酸鹽，12種草本精華。今年已經有超過3000位客人轉用。每瓶399元，你的頭髮會感謝你！",
            "language": "zh-TW",
            "voice_id": "xiaochen",
            "duration": 30,
            "aspect_ratio": "9:16",
        },
        "gemini_prompt": "Professional headshot of a young Taiwanese woman in a red top, warm smile, clean background, spokesperson look",
    },
    {
        "id": "avatar-guanyu-cable",
        "name": {"en": "Guan-Yu - Charging Cable", "zh": "冠宇 - 充電線"},
        "image_url": f"{GCS_EXAMPLES_BASE}/avatar/guanyu.png",
        "params": {
            "text": "擔心網路買充電線踩雷？我懂。所以我們每條線都通過5000次彎折測試。一年內斷裂免費換新——不問原因。LINE傳訂單號碼就好。賣出超過10000條，換貨率不到0.5%。兩條一組只要349元！",
            "language": "zh-TW",
            "voice_id": "yunyang",
            "duration": 30,
            "aspect_ratio": "9:16",
        },
        "gemini_prompt": "Professional headshot of a young Taiwanese man in a blue formal shirt, confident expression, clean background, spokesperson look",
    },
]


# ─────────────────────────────────────────────────────────────────────────────
# PATTERN GENERATE — prompt only (no input image needed)
# ─────────────────────────────────────────────────────────────────────────────

PATTERN_PRESETS: List[Dict[str, Any]] = [
    {
        "id": "pat-bubbletea-seamless",
        "name": {"en": "Bubble Tea Pattern", "zh": "珍珠奶茶圖案"},
        "image_url": "",  # T2I — no input image needed
        "params": {
            "prompt": "Seamless repeating pattern of bubble tea cups with tapioca pearls, cute kawaii style, pastel pink and brown, tileable",
            "size": "1024*1024",
        },
        "gemini_prompt": "",
    },
    {
        "id": "pat-floral-skincare",
        "name": {"en": "Floral Skincare Pattern", "zh": "花卉保養品圖案"},
        "image_url": "",
        "params": {
            "prompt": "Elegant floral pattern with sakura blossoms and green leaves, soft pastel colors, seamless tileable, skincare packaging design",
            "size": "1024*1024",
        },
        "gemini_prompt": "",
    },
    {
        "id": "pat-geometric-cafe",
        "name": {"en": "Geometric Cafe Pattern", "zh": "幾何咖啡圖案"},
        "image_url": "",
        "params": {
            "prompt": "Geometric pattern with coffee cups and beans, modern minimal design, brown and cream colors, seamless tileable",
            "size": "1024*1024",
        },
        "gemini_prompt": "",
    },
    {
        "id": "pat-abstract-food",
        "name": {"en": "Abstract Food Pattern", "zh": "抽象美食圖案"},
        "image_url": "",
        "params": {
            "prompt": "Abstract colorful pattern with food elements, playful shapes, warm colors, menu design background, seamless tileable",
            "size": "1024*1024",
        },
        "gemini_prompt": "",
    },
    {
        "id": "pat-traditional-gift",
        "name": {"en": "Traditional Gift Pattern", "zh": "傳統禮品圖案"},
        "image_url": "",
        "params": {
            "prompt": "Traditional Chinese pattern with clouds and waves, red and gold colors, gift wrapping design, seamless tileable",
            "size": "1024*1024",
        },
        "gemini_prompt": "",
    },
]


# ─────────────────────────────────────────────────────────────────────────────
# MASTER REGISTRY — tool_type → preset list
# Maps tool_type strings to TaskType enum values in the cache service
# ─────────────────────────────────────────────────────────────────────────────

EXAMPLE_PRESETS: Dict[str, List[Dict[str, Any]]] = {
    "background_removal": BACKGROUND_REMOVAL_PRESETS,
    "product_scene": PRODUCT_SCENE_PRESETS,
    "effect": EFFECT_PRESETS,
    "room_redesign": ROOM_REDESIGN_PRESETS,
    "short_video": SHORT_VIDEO_PRESETS,
    "ai_avatar": AVATAR_PRESETS,
    "pattern_generate": PATTERN_PRESETS,
}


def get_presets(tool_type: str) -> List[Dict[str, Any]]:
    """Get all presets for a tool type."""
    return EXAMPLE_PRESETS.get(tool_type, [])


def get_preset_by_id(tool_type: str, preset_id: str) -> Dict[str, Any] | None:
    """Find a specific preset by tool_type and preset_id."""
    for preset in EXAMPLE_PRESETS.get(tool_type, []):
        if preset["id"] == preset_id:
            return preset
    return None


def get_all_tool_types() -> List[str]:
    """Get list of all tool types that have presets."""
    return list(EXAMPLE_PRESETS.keys())
