steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    args:
      - 'build'
      - '-t'
      - 'asia-east1-docker.pkg.dev/$PROJECT_ID/vidgo-images/vidgo-frontend:paypal-cancel-retry'
      - '-t'
      - 'asia-east1-docker.pkg.dev/$PROJECT_ID/vidgo-images/vidgo-frontend:latest'
      - '--cache-from'
      - 'asia-east1-docker.pkg.dev/$PROJECT_ID/vidgo-images/vidgo-frontend:latest'
      - '-f'
      - 'frontend-vue/Dockerfile.prod'
      - 'frontend-vue/'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend'
    waitFor: ['build-frontend']
    args:
      - 'push'
      - '--all-tags'
      - 'asia-east1-docker.pkg.dev/$PROJECT_ID/vidgo-images/vidgo-frontend'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

timeout: '1800s'

images:
  - 'asia-east1-docker.pkg.dev/$PROJECT_ID/vidgo-images/vidgo-frontend:paypal-cancel-retry'
