"""
Unified Material Model for VidGo Platform
Based on ARCHITECTURE_FINAL.md specification

Material system for:
1. Pre-generated seed materials (960 examples across 5 tools)
2. User-generated content (for approval/featuring)
3. Admin-curated content
"""
from sqlalchemy import Column, String, Integer, Boolean, DateTime, Text, Float, ForeignKey, Enum, Index, func
from sqlalchemy.dialects.postgresql import UUID, ARRAY, JSONB
from sqlalchemy.orm import relationship
import uuid
import enum
from app.core.database import Base


class ToolType(str, enum.Enum):
    """6 Core Tools as specified in ARCHITECTURE_FINAL.md"""
    BACKGROUND_REMOVAL = "background_removal"
    PRODUCT_SCENE = "product_scene"
    TRY_ON = "try_on"
    ROOM_REDESIGN = "room_redesign"
    SHORT_VIDEO = "short_video"
    AI_AVATAR = "ai_avatar"  # NEW: AI Avatar video generation


class MaterialSource(str, enum.Enum):
    """Source of material content"""
    SEED = "seed"      # Pre-generated by seed script
    USER = "user"      # Generated by paid users
    ADMIN = "admin"    # Uploaded/curated by admin


class MaterialStatus(str, enum.Enum):
    """Material approval status"""
    PENDING = "pending"       # Awaiting review
    APPROVED = "approved"     # Approved for public display
    REJECTED = "rejected"     # Rejected (quality/content issues)
    FEATURED = "featured"     # Featured on landing page


class Material(Base):
    """
    Unified Material model for pre-generated examples and user content.

    Supports:
    - 5 tool types (background_removal, product_scene, try_on, room_redesign, short_video)
    - Multi-step generation tracking via generation_steps JSON
    - Multi-language titles (en, zh, ja)
    - Demo user restrictions (watermarked results, no download)
    - Personalized recommendations (track views per user)
    """
    __tablename__ = "materials"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # === Classification ===
    tool_type = Column(
        Enum(ToolType, values_callable=lambda x: [e.value for e in x]),
        nullable=False,
        index=True
    )
    topic = Column(String(100), nullable=False, index=True)  # e.g., "electronics", "fashion", "food"
    language = Column(String(10), default="en", index=True)  # en, zh-TW, ja, ko, es - for language-specific content
    tags = Column(ARRAY(String), default=[])
    source = Column(
        Enum(MaterialSource, values_callable=lambda x: [e.value for e in x]),
        default=MaterialSource.SEED,
        nullable=False
    )
    source_user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)
    status = Column(
        Enum(MaterialStatus, values_callable=lambda x: [e.value for e in x]),
        default=MaterialStatus.PENDING,
        nullable=False,
        index=True
    )

    # === Input Data ===
    prompt = Column(Text, nullable=False)
    prompt_enhanced = Column(Text, nullable=True)  # Gemini-enhanced version
    input_image_url = Column(String(500), nullable=True)  # Source image (nullable for text-to-image)
    input_params = Column(JSONB, default={})  # Parameters used for generation

    # === Generation Pipeline ===
    generation_steps = Column(JSONB, default=[])
    """
    JSON array tracking each step of the generation pipeline.
    Example:
    [
        {
            "step": 1,
            "api": "leonardo",
            "action": "text_to_image",
            "model": "phoenix",
            "input": {"prompt": "..."},
            "result_url": "https://...",
            "cost": 0.01,
            "duration_ms": 5000
        },
        {
            "step": 2,
            "api": "goenhance",
            "action": "style_transfer",
            "style": "nordic",
            "input": {"image_url": "..."},
            "result_url": "https://...",
            "cost": 0.05,
            "duration_ms": 8000
        }
    ]
    """

    # === Output Data ===
    result_image_url = Column(String(500), nullable=True)
    result_video_url = Column(String(500), nullable=True)
    result_thumbnail_url = Column(String(500), nullable=True)
    result_watermarked_url = Column(String(500), nullable=True)  # For demo users

    # === Multi-language Titles ===
    title_en = Column(String(255), nullable=True)
    title_zh = Column(String(255), nullable=True)
    title_ja = Column(String(255), nullable=True)

    # === Description (optional) ===
    description_en = Column(Text, nullable=True)
    description_zh = Column(Text, nullable=True)
    description_ja = Column(Text, nullable=True)

    # === Statistics ===
    view_count = Column(Integer, default=0)
    use_count = Column(Integer, default=0)  # How many times used for demo
    like_count = Column(Integer, default=0)
    generation_cost_usd = Column(Float, default=0.0)  # Total API cost

    # === Quality & Ranking ===
    quality_score = Column(Float, default=0.8)  # 0-1 rating
    sort_order = Column(Integer, default=0)

    # === Metadata ===
    duration_seconds = Column(Float, nullable=True)  # For videos
    resolution = Column(String(20), nullable=True)  # e.g., "1080p", "4K"

    # === Flags ===
    is_featured = Column(Boolean, default=False)
    is_active = Column(Boolean, default=True)

    # === Timestamps ===
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    approved_at = Column(DateTime(timezone=True), nullable=True)

    # === Relationships ===
    source_user = relationship("User", foreign_keys=[source_user_id])
    views = relationship("MaterialView", back_populates="material", cascade="all, delete-orphan")

    # === Indexes ===
    __table_args__ = (
        Index('idx_material_tool_topic', 'tool_type', 'topic', 'is_active'),
        Index('idx_material_status', 'status', 'is_active'),
        Index('idx_material_featured', 'is_featured', 'is_active'),
        Index('idx_material_tags', 'tags', postgresql_using='gin'),
        Index('idx_material_source', 'source', 'source_user_id'),
    )


class MaterialView(Base):
    """
    Track material views per user for personalization.
    Ensures demo users don't see the same material twice.
    """
    __tablename__ = "material_views"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    material_id = Column(UUID(as_uuid=True), ForeignKey("materials.id"), nullable=False, index=True)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True, index=True)
    session_id = Column(String(64), nullable=True)  # For anonymous users
    ip_address = Column(String(45), nullable=True)

    # View context
    source_page = Column(String(50), nullable=True)  # landing, inspiration, tool_page
    viewed_at = Column(DateTime(timezone=True), server_default=func.now())

    # === Relationships ===
    material = relationship("Material", back_populates="views")

    # === Indexes ===
    __table_args__ = (
        Index('idx_material_view_user', 'user_id', 'material_id'),
        Index('idx_material_view_session', 'session_id', 'material_id'),
    )


class MaterialTopic(Base):
    """
    Configuration table for material topics.
    Defines the topics available for each tool type.
    """
    __tablename__ = "material_topics"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    tool_type = Column(Enum(ToolType, values_callable=lambda x: [e.value for e in x]), nullable=False, index=True)
    topic_id = Column(String(50), nullable=False)  # e.g., "electronics", "fashion"
    topic_name_en = Column(String(100), nullable=False)
    topic_name_zh = Column(String(100), nullable=True)
    topic_name_ja = Column(String(100), nullable=True)
    description = Column(Text, nullable=True)
    icon = Column(String(50), nullable=True)  # Emoji or icon class
    target_count = Column(Integer, default=30)  # Target number of materials per topic
    is_active = Column(Boolean, default=True)
    sort_order = Column(Integer, default=0)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    __table_args__ = (
        Index('idx_topic_tool', 'tool_type', 'is_active'),
    )


# === Topic Configuration (for seed script) ===
# Based on ARCHITECTURE_FINAL.md: 960 total materials (5 tools × 6-8 topics × 30 each)

MATERIAL_TOPICS = {
    ToolType.BACKGROUND_REMOVAL: [
        {"topic_id": "electronics", "name_en": "Electronics", "name_zh": "電子產品"},
        {"topic_id": "fashion", "name_en": "Fashion", "name_zh": "時尚服飾"},
        {"topic_id": "jewelry", "name_en": "Jewelry", "name_zh": "珠寶首飾"},
        {"topic_id": "food", "name_en": "Food & Beverage", "name_zh": "食品飲料"},
        {"topic_id": "cosmetics", "name_en": "Cosmetics", "name_zh": "化妝品"},
        {"topic_id": "furniture", "name_en": "Furniture", "name_zh": "家具"},
        {"topic_id": "toys", "name_en": "Toys", "name_zh": "玩具"},
        {"topic_id": "sports", "name_en": "Sports Equipment", "name_zh": "運動器材"},
    ],
    ToolType.PRODUCT_SCENE: [
        {"topic_id": "studio", "name_en": "Studio Lighting", "name_zh": "攝影棚"},
        {"topic_id": "nature", "name_en": "Nature Setting", "name_zh": "自然場景"},
        {"topic_id": "luxury", "name_en": "Luxury Setting", "name_zh": "奢華場景"},
        {"topic_id": "minimal", "name_en": "Minimal", "name_zh": "極簡風格"},
        {"topic_id": "lifestyle", "name_en": "Lifestyle", "name_zh": "生活情境"},
        {"topic_id": "urban", "name_en": "Urban", "name_zh": "都市風格"},
        {"topic_id": "seasonal", "name_en": "Seasonal", "name_zh": "季節主題"},
        {"topic_id": "holiday", "name_en": "Holiday", "name_zh": "節日主題"},
    ],
    ToolType.TRY_ON: [
        {"topic_id": "casual", "name_en": "Casual Wear", "name_zh": "休閒服飾"},
        {"topic_id": "formal", "name_en": "Formal Wear", "name_zh": "正式服飾"},
        {"topic_id": "sportswear", "name_en": "Sportswear", "name_zh": "運動服飾"},
        {"topic_id": "outerwear", "name_en": "Outerwear", "name_zh": "外套"},
        {"topic_id": "accessories", "name_en": "Accessories", "name_zh": "配飾"},
        {"topic_id": "dresses", "name_en": "Dresses", "name_zh": "連衣裙"},
    ],
    ToolType.ROOM_REDESIGN: [
        {"topic_id": "modern", "name_en": "Modern", "name_zh": "現代風格"},
        {"topic_id": "nordic", "name_en": "Nordic", "name_zh": "北歐風格"},
        {"topic_id": "japanese", "name_en": "Japanese", "name_zh": "日式風格"},
        {"topic_id": "industrial", "name_en": "Industrial", "name_zh": "工業風"},
        {"topic_id": "minimalist", "name_en": "Minimalist", "name_zh": "極簡主義"},
        {"topic_id": "luxury", "name_en": "Luxury", "name_zh": "奢華風格"},
    ],
    ToolType.SHORT_VIDEO: [
        {"topic_id": "product_showcase", "name_en": "Product Showcase", "name_zh": "產品展示"},
        {"topic_id": "brand_story", "name_en": "Brand Story", "name_zh": "品牌故事"},
        {"topic_id": "tutorial", "name_en": "Tutorial", "name_zh": "教學影片"},
        {"topic_id": "promo", "name_en": "Promotion", "name_zh": "促銷廣告"},
    ],
    ToolType.AI_AVATAR: [
        {"topic_id": "spokesperson", "name_en": "Spokesperson", "name_zh": "品牌代言人"},
        {"topic_id": "product_intro", "name_en": "Product Introduction", "name_zh": "產品介紹"},
        {"topic_id": "customer_service", "name_en": "Customer Service", "name_zh": "客服助理"},
        {"topic_id": "social_media", "name_en": "Social Media", "name_zh": "社群媒體"},
    ],
}

# Language-specific avatar scripts for pre-generation (4 topics only)
AVATAR_SCRIPTS = {
    "en": {
        "spokesperson": [
            "Welcome to our brand! I'm excited to introduce our latest innovations that will transform your daily life.",
            "Hello everyone! Today I'll be sharing something truly special with you. Let's discover what makes our products unique.",
            "Thank you for joining us! We've been working hard to bring you the best quality and experience.",
        ],
        "product_intro": [
            "Let me show you the amazing features of this product. It's designed with you in mind.",
            "This innovative product combines cutting-edge technology with user-friendly design.",
            "Discover why thousands of customers love this product and how it can benefit you.",
        ],
        "customer_service": [
            "Hello! I'm here to help you with any questions you may have about our services.",
            "Welcome to our support center. How may I assist you today?",
            "Thank you for reaching out! Let me guide you through our solutions.",
        ],
        "social_media": [
            "Hey everyone! Don't forget to like and subscribe for more amazing content!",
            "What's up! Today I'm going to share some exciting news with you all.",
            "Hi friends! Thanks for watching. Let me tell you about something cool.",
        ],
    },
    "zh-TW": {
        "spokesperson": [
            "歡迎來到我們的品牌！我很高興為您介紹我們最新的創新產品，將改變您的日常生活。",
            "大家好！今天我要與您分享一些真正特別的東西。讓我們一起發現我們產品的獨特之處。",
            "感謝您的加入！我們一直努力為您帶來最好的品質和體驗。",
        ],
        "product_intro": [
            "讓我為您展示這款產品的驚人功能。它是專為您設計的。",
            "這款創新產品結合了尖端技術與人性化設計。",
            "探索為什麼成千上萬的客戶喜愛這款產品，以及它如何為您帶來好處。",
        ],
        "customer_service": [
            "您好！我在這裡為您解答任何關於我們服務的問題。",
            "歡迎來到我們的客服中心。今天有什麼可以為您效勞的嗎？",
            "感謝您的聯繫！讓我為您介紹我們的解決方案。",
        ],
        "social_media": [
            "嗨大家好！記得按讚訂閱，獲得更多精彩內容！",
            "哈囉！今天我要跟大家分享一些令人興奮的消息。",
            "嗨朋友們！感謝收看。讓我告訴你一些很酷的事情。",
        ],
    },
}
