"""
Seed script for Tool Showcases.

This script seeds the tool_showcases table with placeholder data.
The result_image_url is set to None - actual AI-generated results must be
created by running: python -m scripts.generate_real_showcases

IMPORTANT: Source images are real product/scene images.
Result images must be generated by AI APIs to show actual transformations.

Run with: python -m scripts.seed_tool_showcases
Use --clear flag to clear existing data first.
"""
import asyncio
import sys
import argparse

# Add parent directory to path
sys.path.insert(0, "/app")

from sqlalchemy import select, delete
from app.core.database import AsyncSessionLocal
from app.models.demo import ToolShowcase


# =============================================================================
# TOOL SHOWCASE DATA
# =============================================================================
# NOTE: result_image_url is intentionally set to None for most entries.
# Run `python -m scripts.generate_real_showcases` to generate actual AI results.
# This ensures before/after images have a real transformation relationship.

# Working video samples from Google's public video bucket (allows hotlinking)
# Note: These are placeholder videos. In production, use actual AI-generated videos.
SAMPLE_VIDEOS = {
    "product_demo_1": "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "product_demo_2": "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    "product_demo_3": "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    "product_demo_4": "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    "product_demo_5": "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
}

# Tool Showcase Data organized by category
# IMPORTANT: tool_id must match frontend definitions in front_app.py
# NOTE: result_image_url = None means "needs AI generation"
TOOL_SHOWCASES = {
    # ==========================================================================
    # EDIT TOOLS (編輯工具)
    # Frontend tool IDs: universal_edit, hd_upscale, ai_cutout, change_bg, photo_cartoon, ai_expand
    # ==========================================================================
    "edit_tools": [
        # Universal Edit - 萬能改圖
        {
            "tool_id": "universal_edit",
            "tool_name": "Universal Edit",
            "tool_name_zh": "萬能改圖",
            "showcases": [
                {
                    "source_image_url": "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
                    "prompt": "Change the sky to a dramatic sunset with orange and purple clouds",
                    "prompt_zh": "將天空改為戲劇性的日落，橙色和紫色的雲彩",
                    "result_image_url": None,  # Needs AI generation
                    "title": "Sky Replacement",
                    "title_zh": "天空替換",
                    "style_tags": ["天空", "日落", "編輯"],
                    "is_featured": True
                },
                {
                    "source_image_url": "https://images.unsplash.com/photo-1518837695005-2083093ee35b?w=800",
                    "prompt": "Add a rainbow over the ocean waves",
                    "prompt_zh": "在海浪上方添加彩虹",
                    "result_image_url": None,  # Needs AI generation
                    "title": "Add Rainbow",
                    "title_zh": "添加彩虹",
                    "style_tags": ["彩虹", "海洋", "編輯"]
                }
            ]
        },
        # HD Upscale - 高清放大 (Same image, different resolution demonstrates upscaling)
        {
            "tool_id": "hd_upscale",
            "tool_name": "HD Upscale",
            "tool_name_zh": "高清放大",
            "showcases": [
                {
                    # For upscale, showing low-res vs high-res of same image is correct
                    "source_image_url": "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=400&q=50",
                    "prompt": "Enhance image quality to 4K, improve sharpness and color vibrancy",
                    "prompt_zh": "增強至4K畫質，提升銳利度和色彩",
                    "result_image_url": "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=1600&q=100",
                    "title": "4K Enhancement",
                    "title_zh": "4K 畫質增強",
                    "style_tags": ["4K", "高畫質", "增強"],
                    "is_featured": True
                }
            ]
        },
        # AI Cutout - AI摳圖
        {
            "tool_id": "ai_cutout",
            "tool_name": "AI Cutout",
            "tool_name_zh": "AI摳圖",
            "showcases": [
                {
                    "source_image_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800",
                    "prompt": "Remove background and keep the person isolated on transparent",
                    "prompt_zh": "移除背景，保留人物於透明背景",
                    "result_image_url": None,  # Needs AI generation - background removal
                    "title": "Person Isolation",
                    "title_zh": "人物去背",
                    "style_tags": ["去背", "人物", "透明"],
                    "is_featured": True
                }
            ]
        },
        # Change BG - 換背景
        {
            "tool_id": "change_bg",
            "tool_name": "Change Background",
            "tool_name_zh": "換背景",
            "showcases": [
                {
                    # Product on complex background -> product on white
                    "source_image_url": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800",
                    "prompt": "Replace background with pure white for e-commerce product listing",
                    "prompt_zh": "將背景替換為純白色，用於電商產品上架",
                    "result_image_url": None,  # Needs AI generation
                    "title": "White Background",
                    "title_zh": "白色背景",
                    "style_tags": ["白底", "產品", "電商"],
                    "is_featured": True
                }
            ]
        },
        # Photo to Cartoon - 真人轉漫畫
        {
            "tool_id": "photo_cartoon",
            "tool_name": "Photo to Cartoon",
            "tool_name_zh": "真人轉漫畫",
            "showcases": [
                {
                    "source_image_url": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800",
                    "prompt": "Transform portrait into anime style illustration with vibrant colors",
                    "prompt_zh": "將人像轉換為動漫風格插畫，鮮艷色彩",
                    "result_image_url": None,  # Needs AI generation - style transfer
                    "title": "Anime Style",
                    "title_zh": "動漫風格",
                    "style_tags": ["動漫", "卡通", "藝術"],
                    "is_featured": True
                }
            ]
        },
        # AI Expand - AI擴圖
        {
            "tool_id": "ai_expand",
            "tool_name": "AI Expand",
            "tool_name_zh": "AI擴圖",
            "showcases": [
                {
                    "source_image_url": "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600",
                    "prompt": "Expand the image borders to show more of the mountain landscape",
                    "prompt_zh": "擴展圖片邊界以顯示更多山景",
                    "result_image_url": None,  # Needs AI generation - outpainting
                    "title": "Landscape Expansion",
                    "title_zh": "風景擴展",
                    "style_tags": ["擴圖", "風景", "AI"],
                    "is_featured": True
                }
            ]
        }
    ],

    # ==========================================================================
    # E-COMMERCE (產品電商)
    # Frontend tool IDs: product_design, white_bg, scene_gen, model_tryon
    # ==========================================================================
    "ecommerce": [
        # Product Design - AI產品設計 (Video generation)
        # NOTE: Uses placeholder videos from Pexels for demo purposes.
        # Run: python -m scripts.generate_real_showcases --category ecommerce
        # to generate AI videos that match the source images when API credits available.
        {
            "tool_id": "product_design",
            "tool_name": "Product Design",
            "tool_name_zh": "AI產品設計",
            "showcases": [
                {
                    "source_image_url": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800",
                    "prompt": "Create luxury watch commercial with elegant rotation, spotlight effect",
                    "prompt_zh": "創建豪華手錶廣告，優雅旋轉，聚光燈效果",
                    # Placeholder video - luxury product video from Pexels
                    "result_video_url": "https://videos.pexels.com/video-files/3195394/3195394-uhd_2560_1440_25fps.mp4",
                    "title": "Luxury Watch Ad",
                    "title_zh": "豪華手錶廣告",
                    "style_tags": ["奢華", "手錶", "產品"],
                    "duration_seconds": 15.0,
                    "is_featured": True
                },
                {
                    "source_image_url": "https://images.unsplash.com/photo-1541643600914-78b084683601?w=800",
                    "prompt": "Perfume bottle with mist effect, crystal reflections, romantic atmosphere",
                    "prompt_zh": "香水瓶帶有霧氣效果，水晶反射，浪漫氛圍",
                    # Placeholder video - elegant product video from Pexels
                    "result_video_url": "https://videos.pexels.com/video-files/3209829/3209829-uhd_2560_1440_25fps.mp4",
                    "title": "Perfume Commercial",
                    "title_zh": "香水廣告",
                    "style_tags": ["香水", "浪漫", "奢華"],
                    "duration_seconds": 15.0
                }
            ]
        },
        # White Background - 一鍵白底圖
        {
            "tool_id": "white_bg",
            "tool_name": "White Background",
            "tool_name_zh": "一鍵白底圖",
            "showcases": [
                {
                    # Sneaker with background -> sneaker on white
                    "source_image_url": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800",
                    "prompt": "Remove background and place product on pure white background for e-commerce",
                    "prompt_zh": "移除背景並將產品放在純白背景上用於電商",
                    "result_image_url": None,  # Needs AI generation
                    "title": "Sneaker White BG",
                    "title_zh": "運動鞋白底圖",
                    "style_tags": ["白底", "電商", "產品"],
                    "is_featured": True
                }
            ]
        },
        # Scene Generation - 場景圖生成
        {
            "tool_id": "scene_gen",
            "tool_name": "Scene Generation",
            "tool_name_zh": "場景圖生成",
            "showcases": [
                {
                    # Coffee cup product shot -> coffee in cozy scene
                    "source_image_url": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800",
                    "prompt": "Place coffee cup in cozy morning scene with warm lighting and breakfast setting",
                    "prompt_zh": "將咖啡杯放在溫馨的早晨場景中，暖色照明和早餐擺設",
                    "result_image_url": None,  # Needs AI generation
                    "title": "Morning Coffee Scene",
                    "title_zh": "早晨咖啡場景",
                    "style_tags": ["場景", "咖啡", "溫馨"],
                    "is_featured": True
                }
            ]
        },
        # Model Try-on - 模特試衣
        {
            "tool_id": "model_tryon",
            "tool_name": "Model Try-on",
            "tool_name_zh": "模特試衣",
            "showcases": [
                {
                    # Clothing flat lay -> model wearing it
                    "source_image_url": "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=800",
                    "prompt": "Show this dress on a professional model with studio lighting",
                    "prompt_zh": "在專業模特身上展示這件連衣裙，攝影棚燈光",
                    "result_image_url": None,  # Needs AI generation - virtual try-on
                    "title": "Dress Model",
                    "title_zh": "連衣裙模特",
                    "style_tags": ["模特", "服裝", "時尚"],
                    "is_featured": True
                },
                {
                    # Jacket product -> model wearing it
                    "source_image_url": "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800",
                    "prompt": "Display this jacket on male model in urban street setting",
                    "prompt_zh": "在城市街景中展示男模特穿這件夾克",
                    "result_image_url": None,  # Needs AI generation
                    "title": "Street Fashion",
                    "title_zh": "街頭時尚",
                    "style_tags": ["男裝", "街頭", "時尚"]
                }
            ]
        }
    ],

    # ==========================================================================
    # ARCHITECTURE (建築設計)
    # Frontend tool IDs: ai_concept, 3d_render, style_convert, floor_plan
    # ==========================================================================
    "architecture": [
        # AI Concept - AI概念圖
        {
            "tool_id": "ai_concept",
            "tool_name": "AI Concept",
            "tool_name_zh": "AI概念圖",
            "showcases": [
                {
                    # Architectural sketch -> rendered concept
                    "source_image_url": "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800",
                    "prompt": "Generate modern architectural concept from this sketch with glass facade",
                    "prompt_zh": "從這個草圖生成帶玻璃幕牆的現代建築概念",
                    "result_image_url": None,  # Needs AI generation
                    "title": "Modern Concept",
                    "title_zh": "現代概念",
                    "style_tags": ["概念", "現代", "建築"],
                    "is_featured": True
                }
            ]
        },
        # 3D Render - 3D渲染
        {
            "tool_id": "3d_render",
            "tool_name": "3D Render",
            "tool_name_zh": "3D渲染",
            "showcases": [
                {
                    # Basic room/floor plan -> rendered kitchen
                    "source_image_url": "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800",
                    "prompt": "Create photorealistic 3D render of modern kitchen with marble countertops",
                    "prompt_zh": "創建帶大理石檯面的現代廚房逼真3D渲染",
                    "result_image_url": None,  # Needs AI generation
                    "title": "Kitchen Render",
                    "title_zh": "廚房渲染",
                    "style_tags": ["廚房", "3D", "渲染"],
                    "is_featured": True
                },
                {
                    "source_image_url": "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800",
                    "prompt": "Render cozy bedroom with warm lighting and indoor plants",
                    "prompt_zh": "渲染溫馨臥室，暖色照明和室內植物",
                    "result_image_url": None,  # Needs AI generation
                    "title": "Cozy Bedroom",
                    "title_zh": "溫馨臥室",
                    "style_tags": ["臥室", "溫馨", "植物"]
                }
            ]
        },
        # Style Convert - 風格轉換
        {
            "tool_id": "style_convert",
            "tool_name": "Style Convert",
            "tool_name_zh": "風格轉換",
            "showcases": [
                {
                    # Modern house -> Mediterranean style
                    "source_image_url": "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800",
                    "prompt": "Convert this modern villa to Mediterranean style with terracotta roof",
                    "prompt_zh": "將這座現代別墅轉換為地中海風格，陶瓦屋頂",
                    "result_image_url": None,  # Needs AI generation - style transfer
                    "title": "Mediterranean Villa",
                    "title_zh": "地中海別墅",
                    "style_tags": ["地中海", "別墅", "風格"],
                    "is_featured": True
                }
            ]
        },
        # Floor Plan - 彩平圖
        {
            "tool_id": "floor_plan",
            "tool_name": "Floor Plan",
            "tool_name_zh": "彩平圖",
            "showcases": [
                {
                    # Basic floor plan -> colored/furnished floor plan
                    "source_image_url": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
                    "prompt": "Enhance floor plan with furniture layout and color coding",
                    "prompt_zh": "增強平面圖，添加家具佈局和顏色編碼",
                    "result_image_url": None,  # Needs AI generation
                    "title": "Enhanced Floor Plan",
                    "title_zh": "增強平面圖",
                    "style_tags": ["平面圖", "家具", "佈局"],
                    "is_featured": True
                }
            ]
        }
    ],

    # ==========================================================================
    # VIDEO (AI影片)
    # Frontend topic: video - 圖轉影片、風格轉換
    # NOTE: result_video_url = None - must be generated by actual AI APIs
    # Never use placeholder videos that don't match the prompts!
    # ==========================================================================
    "video": [
        # Image to Video - 圖轉影片
        # Flow: Source Image → Leonardo Motion → Animated Video
        {
            "tool_id": "image_to_video",
            "tool_name": "Image to Video",
            "tool_name_zh": "圖轉影片",
            "generation_type": "image_to_video",
            "showcases": [
                {
                    "source_image_url": "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
                    "prompt": "Gentle camera pan across mountain landscape, clouds slowly drifting, cinematic atmosphere",
                    "prompt_zh": "緩慢鏡頭掃過山景，雲朵緩緩飄動，電影氛圍",
                    "result_video_url": None,  # Must be AI generated - matches source image!
                    "title": "Mountain Cinematic",
                    "title_zh": "山景電影感",
                    "style_tags": ["風景", "電影", "動態"],
                    "duration_seconds": 5.0,
                    "is_featured": True
                },
                {
                    "source_image_url": "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800",
                    "prompt": "Subtle water ripples on lake surface, gentle breeze effect, peaceful morning",
                    "prompt_zh": "湖面輕微波紋，微風效果，寧靜早晨",
                    "result_video_url": None,  # Must be AI generated - matches source image!
                    "title": "Lake Scene",
                    "title_zh": "湖畔風光",
                    "style_tags": ["湖景", "自然", "寧靜"],
                    "duration_seconds": 5.0
                },
                {
                    "source_image_url": "https://images.unsplash.com/photo-1518837695005-2083093ee35b?w=800",
                    "prompt": "Ocean waves crashing on shore, sea foam movement, dynamic water motion",
                    "prompt_zh": "海浪拍打岸邊，海沫流動，動態水面",
                    "result_video_url": None,  # Must be AI generated
                    "title": "Ocean Waves",
                    "title_zh": "海浪翻湧",
                    "style_tags": ["海洋", "波浪", "動態"],
                    "duration_seconds": 5.0
                }
            ]
        },
        # Video Transform - 風格轉換 (Image → Styled Video via GoEnhance)
        # Flow: Source Image → GoEnhance V2V → Styled Animation
        {
            "tool_id": "video_transform",
            "tool_name": "Video Transform",
            "tool_name_zh": "風格轉換",
            "generation_type": "image_to_styled_video",
            "showcases": [
                {
                    "source_image_url": "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800",
                    "prompt": "Ghibli anime style, soft watercolor colors, dreamy atmosphere, hand-painted look",
                    "prompt_zh": "吉卜力動畫風格，柔和水彩色調，夢幻氛圍",
                    "result_video_url": None,  # Must be AI generated with Ghibli style!
                    "title": "Ghibli Style",
                    "title_zh": "吉卜力風格",
                    "style_tags": ["ghibli", "動畫", "吉卜力"],
                    "style_id": "ghibli",  # For GoEnhance model selection
                    "duration_seconds": 5.0,
                    "is_featured": True
                },
                {
                    "source_image_url": "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
                    "prompt": "Clay animation style, 3D clay texture, stop motion feel, handcrafted look",
                    "prompt_zh": "黏土動畫風格，3D黏土質感，定格動畫感",
                    "result_video_url": None,  # Must be AI generated with clay style!
                    "title": "Clay Animation",
                    "title_zh": "黏土動畫",
                    "style_tags": ["clay", "黏土", "3D"],
                    "style_id": "clay",  # For GoEnhance model selection
                    "duration_seconds": 5.0
                },
                {
                    "source_image_url": "https://images.unsplash.com/photo-1542224566-6e85f2e6772f?w=800",
                    "prompt": "Anime style transformation, vibrant colors, dynamic lighting, Japanese animation aesthetic",
                    "prompt_zh": "動漫風格轉換，鮮豔色彩，動態光影，日本動畫美學",
                    "result_video_url": None,  # Must be AI generated with anime style!
                    "title": "Anime Style",
                    "title_zh": "動漫風格",
                    "style_tags": ["anime", "動漫", "日式"],
                    "style_id": "anime",  # For GoEnhance model selection
                    "duration_seconds": 5.0,
                    "is_featured": True
                }
            ]
        }
    ],

    # ==========================================================================
    # PATTERN (圖案設計)
    # Frontend topic: pattern - 花卉、幾何、無縫圖案
    # ==========================================================================
    "pattern": [
        # Pattern Generate - 圖案生成
        # NOTE: This is TEXT-TO-IMAGE - NO source image needed!
        # User provides text prompt → AI generates pattern directly
        {
            "tool_id": "pattern_generate",
            "tool_name": "Pattern Generate",
            "tool_name_zh": "圖案生成",
            "generation_type": "text_to_image",  # Mark as TEXT-TO-IMAGE
            "showcases": [
                {
                    # TEXT-TO-IMAGE: No source_image_url - just prompt → result
                    "source_image_url": None,  # No source - pure text generation
                    "prompt": "Elegant floral seamless pattern with roses and peonies, soft pink colors, textile design",
                    "prompt_zh": "優雅花卉無縫圖案，玫瑰和牡丹，柔和粉色",
                    "result_image_url": None,  # Needs AI generation
                    "title": "Floral Pattern",
                    "title_zh": "花卉圖案",
                    "style_tags": ["花卉", "無縫", "粉色"],
                    "is_featured": True
                },
                {
                    "source_image_url": None,  # No source - pure text generation
                    "prompt": "Modern geometric seamless pattern, gold and navy art deco style, repeating tiles",
                    "prompt_zh": "現代幾何無縫圖案，金色海軍藍裝飾藝術",
                    "result_image_url": None,  # Needs AI generation
                    "title": "Geometric Art Deco",
                    "title_zh": "幾何裝飾藝術",
                    "style_tags": ["幾何", "裝飾", "藝術"],
                    "is_featured": True
                },
                {
                    "source_image_url": None,  # No source - pure text generation
                    "prompt": "Traditional Chinese cloud pattern, seamless tile, blue and white porcelain style",
                    "prompt_zh": "傳統中國雲紋圖案，無縫拼貼，青花瓷風格",
                    "result_image_url": None,  # Needs AI generation
                    "title": "Chinese Cloud Pattern",
                    "title_zh": "中國雲紋",
                    "style_tags": ["中國風", "雲紋", "傳統"]
                }
            ]
        },
        # Pattern Transfer - 圖案轉印
        {
            "tool_id": "pattern_transfer",
            "tool_name": "Pattern Transfer",
            "tool_name_zh": "圖案轉印",
            "showcases": [
                {
                    "source_image_url": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800",
                    "prompt": "Apply floral pattern to product surface",
                    "prompt_zh": "將花卉圖案應用到產品表面",
                    "result_image_url": None,  # Needs AI generation
                    "title": "Floral Product",
                    "title_zh": "花卉產品",
                    "style_tags": ["轉印", "花卉", "產品"],
                    "is_featured": True
                }
            ]
        }
    ],

    # ==========================================================================
    # PORTRAIT (人像寫真)
    # Frontend tool IDs: face_swap, photo_restore, ai_portrait
    # ==========================================================================
    "portrait": [
        # Face Swap - 人像換臉
        {
            "tool_id": "face_swap",
            "tool_name": "Face Swap",
            "tool_name_zh": "人像換臉",
            "showcases": [
                {
                    "source_image_url": "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=800",
                    "prompt": "Swap face with target image while preserving natural lighting and expressions",
                    "prompt_zh": "與目標圖片換臉，同時保留自然光線和表情",
                    "result_image_url": None,  # Needs AI generation - face swap
                    "title": "Face Swap Result",
                    "title_zh": "換臉結果",
                    "style_tags": ["換臉", "人像", "AI"],
                    "is_featured": True
                },
                {
                    "source_image_url": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800",
                    "prompt": "Professional face swap with studio quality lighting",
                    "prompt_zh": "專業換臉，攝影棚品質燈光",
                    "result_image_url": None,  # Needs AI generation
                    "title": "Professional Face Swap",
                    "title_zh": "專業換臉",
                    "style_tags": ["專業", "商務", "換臉"]
                }
            ]
        },
        # Photo Restore - 老照片修復 (Same image, different quality)
        {
            "tool_id": "photo_restore",
            "tool_name": "Photo Restore",
            "tool_name_zh": "老照片修復",
            "showcases": [
                {
                    # Low quality/grainy -> restored high quality
                    "source_image_url": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400&q=30",
                    "prompt": "Restore old photo, remove scratches, enhance clarity and add natural colors",
                    "prompt_zh": "修復老照片，去除劃痕，增強清晰度並添加自然色彩",
                    "result_image_url": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1200&q=100",
                    "title": "Photo Restoration",
                    "title_zh": "照片修復",
                    "style_tags": ["修復", "老照片", "上色"],
                    "is_featured": True
                }
            ]
        },
        # AI Portrait - AI寫真
        {
            "tool_id": "ai_portrait",
            "tool_name": "AI Portrait",
            "tool_name_zh": "AI寫真",
            "showcases": [
                {
                    # Normal portrait -> enhanced artistic portrait
                    "source_image_url": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800",
                    "prompt": "Create artistic portrait with professional studio lighting and soft bokeh",
                    "prompt_zh": "創建藝術人像，專業攝影棚燈光和柔和散景",
                    "result_image_url": None,  # Needs AI generation
                    "title": "Professional Portrait",
                    "title_zh": "專業人像",
                    "style_tags": ["人像", "專業", "藝術"],
                    "is_featured": True
                },
                {
                    # Portrait -> oil painting style
                    "source_image_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800",
                    "prompt": "Transform to oil painting style portrait with classical art feel",
                    "prompt_zh": "轉換為油畫風格人像，古典藝術感",
                    "result_image_url": None,  # Needs AI generation - style transfer
                    "title": "Oil Painting Portrait",
                    "title_zh": "油畫人像",
                    "style_tags": ["油畫", "古典", "藝術"]
                }
            ]
        }
    ]
}


async def seed_tool_showcases(clear_existing: bool = False):
    """Seed tool showcase data."""
    async with AsyncSessionLocal() as session:
        if clear_existing:
            print("Clearing existing tool showcases...")
            await session.execute(delete(ToolShowcase))
            await session.commit()
            print("Cleared.")

        print("\nSeeding tool showcases...")

        total_count = 0
        for category, tools in TOOL_SHOWCASES.items():
            print(f"\n  Category: {category}")

            for tool in tools:
                tool_id = tool["tool_id"]
                tool_name = tool["tool_name"]
                tool_name_zh = tool["tool_name_zh"]
                showcases = tool["showcases"]

                print(f"    Tool: {tool_name} ({len(showcases)} showcases)")

                for idx, showcase_data in enumerate(showcases):
                    # Check if already exists
                    result = await session.execute(
                        select(ToolShowcase).where(
                            ToolShowcase.tool_category == category,
                            ToolShowcase.tool_id == tool_id,
                            ToolShowcase.prompt == showcase_data["prompt"]
                        )
                    )
                    existing = result.scalar_one_or_none()

                    if existing:
                        print(f"      [{idx+1}] Updating: {showcase_data.get('title', 'Untitled')}")
                        for key, value in showcase_data.items():
                            setattr(existing, key, value)
                        existing.tool_name = tool_name
                        existing.tool_name_zh = tool_name_zh
                    else:
                        print(f"      [{idx+1}] Creating: {showcase_data.get('title', 'Untitled')}")
                        showcase = ToolShowcase(
                            tool_category=category,
                            tool_id=tool_id,
                            tool_name=tool_name,
                            tool_name_zh=tool_name_zh,
                            source_image_url=showcase_data["source_image_url"],
                            prompt=showcase_data["prompt"],
                            prompt_zh=showcase_data.get("prompt_zh"),
                            result_image_url=showcase_data.get("result_image_url"),
                            result_video_url=showcase_data.get("result_video_url"),
                            title=showcase_data.get("title"),
                            title_zh=showcase_data.get("title_zh"),
                            style_tags=showcase_data.get("style_tags", []),
                            duration_seconds=showcase_data.get("duration_seconds", 5.0),
                            is_featured=showcase_data.get("is_featured", False),
                            sort_order=idx,
                            is_active=True
                        )
                        session.add(showcase)
                        total_count += 1

                await session.commit()

        print(f"\n{'='*60}")
        print(f"Seeded {total_count} new tool showcases.")
        print(f"{'='*60}")


async def main():
    """Main function."""
    parser = argparse.ArgumentParser(description="Seed tool showcase data")
    parser.add_argument("--clear", action="store_true", help="Clear existing data first")
    args = parser.parse_args()

    print("=" * 60)
    print("VidGo Tool Showcase Seed Script")
    print("=" * 60)

    await seed_tool_showcases(clear_existing=args.clear)

    print("\nSeeding completed successfully!")


if __name__ == "__main__":
    asyncio.run(main())
