"""script.py.mako"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '05a5bdfb49cf'
down_revision = 'n2b3c4d5e6f7'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('prompt_normalized', sa.Text(), nullable=False),
    sa.Column('prompt_en', sa.Text(), nullable=True),
    sa.Column('prompt_zh', sa.Text(), nullable=True),
    sa.Column('prompt_ja', sa.Text(), nullable=True),
    sa.Column('prompt_ko', sa.Text(), nullable=True),
    sa.Column('prompt_es', sa.Text(), nullable=True),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('group', sa.Enum('product_effect', 'background_removal', 'background_change', 'product_scene', 'image_to_video', 'text_to_video', 'video_effect', 'style_transfer', 'room_redesign', 'interior_design', 'virtual_try_on', 'fashion_model', 'ai_avatar', 'talking_head', 'upscale', 'watermark_removal', 'pattern_generate', 'creative_design', name='promptgroup'), nullable=False),
    sa.Column('sub_topic', sa.Enum('color_change', 'material_change', 'lighting_change', 'angle_change', 'transparent', 'white_background', 'studio_background', 'nature_background', 'luxury_background', 'modern_style', 'nordic_style', 'japanese_style', 'industrial_style', 'minimalist_style', 'zoom_in', 'zoom_out', 'pan_left', 'pan_right', 'rotate', 'cinematic', 'default', 'custom', name='promptsubtopic'), nullable=True),
    sa.Column('group_display_en', sa.String(length=100), nullable=True),
    sa.Column('group_display_zh', sa.String(length=100), nullable=True),
    sa.Column('sub_topic_display_en', sa.String(length=100), nullable=True),
    sa.Column('sub_topic_display_zh', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('input_description', sa.Text(), nullable=True),
    sa.Column('input_image_url', sa.String(length=500), nullable=True),
    sa.Column('input_video_url', sa.String(length=500), nullable=True),
    sa.Column('input_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_description', sa.Text(), nullable=True),
    sa.Column('result_image_url', sa.String(length=500), nullable=True),
    sa.Column('result_video_url', sa.String(length=500), nullable=True),
    sa.Column('result_thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('result_watermarked_url', sa.String(length=500), nullable=True),
    sa.Column('result_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('api_endpoint', sa.String(length=100), nullable=True),
    sa.Column('api_provider', sa.String(length=50), nullable=True),
    sa.Column('api_model', sa.String(length=100), nullable=True),
    sa.Column('generation_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('avg_generation_time_ms', sa.Integer(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('popularity_score', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('min_subscription_tier', sa.String(length=20), nullable=True),
    sa.Column('credits_required', sa.Integer(), nullable=True),
    sa.Column('title_en', sa.String(length=255), nullable=True),
    sa.Column('title_zh', sa.String(length=255), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_zh', sa.Text(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_cached', sa.Boolean(), nullable=True),
    sa.Column('cache_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prompt_template_cached', 'prompt_templates', ['is_cached', 'cache_expires_at'], unique=False)
    op.create_index('idx_prompt_template_featured', 'prompt_templates', ['is_featured', 'is_active'], unique=False)
    op.create_index('idx_prompt_template_group', 'prompt_templates', ['group', 'is_active', 'is_default'], unique=False)
    op.create_index('idx_prompt_template_keywords', 'prompt_templates', ['keywords'], unique=False, postgresql_using='gin')
    op.create_index('idx_prompt_template_popular', 'prompt_templates', ['popularity_score', 'is_active'], unique=False)
    op.create_index('idx_prompt_template_sub_topic', 'prompt_templates', ['sub_topic', 'is_active'], unique=False)
    op.create_index('idx_prompt_template_tags', 'prompt_templates', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('idx_prompt_template_unique', 'prompt_templates', ['prompt_hash', 'group', 'sub_topic'], unique=True)
    op.create_index(op.f('ix_prompt_templates_group'), 'prompt_templates', ['group'], unique=False)
    op.create_index(op.f('ix_prompt_templates_prompt_hash'), 'prompt_templates', ['prompt_hash'], unique=False)
    op.create_index(op.f('ix_prompt_templates_sub_topic'), 'prompt_templates', ['sub_topic'], unique=False)
    op.create_table('prompt_template_usages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('source_page', sa.String(length=50), nullable=True),
    sa.Column('user_tier', sa.String(length=20), nullable=True),
    sa.Column('used_cached', sa.Boolean(), nullable=True),
    sa.Column('was_successful', sa.Boolean(), nullable=True),
    sa.Column('generation_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('custom_prompt', sa.Text(), nullable=True),
    sa.Column('custom_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['prompt_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_template_usage_template', 'prompt_template_usages', ['template_id', 'used_at'], unique=False)
    op.create_index('idx_template_usage_user', 'prompt_template_usages', ['user_id', 'used_at'], unique=False)
    op.create_index(op.f('ix_prompt_template_usages_template_id'), 'prompt_template_usages', ['template_id'], unique=False)
    op.create_index(op.f('ix_prompt_template_usages_user_id'), 'prompt_template_usages', ['user_id'], unique=False)
    op.alter_column('materials', 'main_topic',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('materials', 'main_topic_zh',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('materials', 'topic_zh',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('materials', 'input_video_url',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_index('idx_material_language', table_name='materials')
    op.create_index('idx_material_main_topic', 'materials', ['main_topic', 'topic', 'is_active'], unique=False)
    op.create_index('idx_material_prompt_effect', 'materials', ['prompt', 'effect_prompt'], unique=False)
    op.create_index('idx_material_status', 'materials', ['status', 'is_active'], unique=False)
    op.create_index(op.f('ix_materials_language'), 'materials', ['language'], unique=False)
    op.create_index(op.f('ix_materials_main_topic'), 'materials', ['main_topic'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_materials_main_topic'), table_name='materials')
    op.drop_index(op.f('ix_materials_language'), table_name='materials')
    op.drop_index('idx_material_status', table_name='materials')
    op.drop_index('idx_material_prompt_effect', table_name='materials')
    op.drop_index('idx_material_main_topic', table_name='materials')
    op.create_index('idx_material_language', 'materials', ['language', 'tool_type', 'is_active'], unique=False)
    op.alter_column('materials', 'input_video_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('materials', 'topic_zh',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('materials', 'main_topic_zh',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('materials', 'main_topic',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_prompt_template_usages_user_id'), table_name='prompt_template_usages')
    op.drop_index(op.f('ix_prompt_template_usages_template_id'), table_name='prompt_template_usages')
    op.drop_index('idx_template_usage_user', table_name='prompt_template_usages')
    op.drop_index('idx_template_usage_template', table_name='prompt_template_usages')
    op.drop_table('prompt_template_usages')
    op.drop_index(op.f('ix_prompt_templates_sub_topic'), table_name='prompt_templates')
    op.drop_index(op.f('ix_prompt_templates_prompt_hash'), table_name='prompt_templates')
    op.drop_index(op.f('ix_prompt_templates_group'), table_name='prompt_templates')
    op.drop_index('idx_prompt_template_unique', table_name='prompt_templates')
    op.drop_index('idx_prompt_template_tags', table_name='prompt_templates', postgresql_using='gin')
    op.drop_index('idx_prompt_template_sub_topic', table_name='prompt_templates')
    op.drop_index('idx_prompt_template_popular', table_name='prompt_templates')
    op.drop_index('idx_prompt_template_keywords', table_name='prompt_templates', postgresql_using='gin')
    op.drop_index('idx_prompt_template_group', table_name='prompt_templates')
    op.drop_index('idx_prompt_template_featured', table_name='prompt_templates')
    op.drop_index('idx_prompt_template_cached', table_name='prompt_templates')
    op.drop_table('prompt_templates')
    # ### end Alembic commands ###
