"""script.py.mako"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24d2e773257a'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demo_categories_slug'), 'demo_categories', ['slug'], unique=True)
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('plan_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('price_monthly', sa.Float(), nullable=True),
    sa.Column('price_yearly', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('billing_cycle', sa.String(), nullable=True),
    sa.Column('credits_per_month', sa.Integer(), nullable=True),
    sa.Column('max_video_length', sa.Integer(), nullable=True),
    sa.Column('max_resolution', sa.String(), nullable=True),
    sa.Column('watermark', sa.Boolean(), nullable=True),
    sa.Column('priority_queue', sa.Boolean(), nullable=True),
    sa.Column('api_access', sa.Boolean(), nullable=True),
    sa.Column('feature_clothing_transform', sa.Boolean(), nullable=True),
    sa.Column('feature_goenhance', sa.Boolean(), nullable=True),
    sa.Column('feature_video_gen', sa.Boolean(), nullable=True),
    sa.Column('feature_batch_processing', sa.Boolean(), nullable=True),
    sa.Column('feature_custom_styles', sa.Boolean(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_index(op.f('ix_plans_slug'), 'plans', ['slug'], unique=True)
    op.create_table('prompt_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('prompt_original', sa.Text(), nullable=False),
    sa.Column('prompt_normalized', sa.Text(), nullable=False),
    sa.Column('detected_language', sa.String(length=10), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('category_hints', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('style_hints', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_cache_prompt_hash'), 'prompt_cache', ['prompt_hash'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verification_token', sa.String(), nullable=True),
    sa.Column('email_verification_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_reset_token', sa.String(), nullable=True),
    sa.Column('password_reset_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_email_verification_token'), 'users', ['email_verification_token'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_password_reset_token'), 'users', ['password_reset_token'], unique=False)
    op.create_table('demo_videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=False),
    sa.Column('video_url_watermarked', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('style', sa.String(length=50), nullable=True),
    sa.Column('source_service', sa.String(length=50), nullable=True),
    sa.Column('generation_params', sa.Text(), nullable=True),
    sa.Column('popularity_score', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['demo_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demo_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('demo_id', sa.UUID(), nullable=False),
    sa.Column('demo_type', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('search_prompt', sa.Text(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demo_views_demo_id'), 'demo_views', ['demo_id'], unique=False)
    op.create_table('image_demos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_original', sa.Text(), nullable=False),
    sa.Column('prompt_normalized', sa.Text(), nullable=False),
    sa.Column('prompt_language', sa.String(length=10), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('keywords_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('category_slug', sa.String(length=50), nullable=True),
    sa.Column('image_url_before', sa.String(length=500), nullable=False),
    sa.Column('image_url_after', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('style_id', sa.Integer(), nullable=True),
    sa.Column('style_name', sa.String(length=100), nullable=True),
    sa.Column('style_slug', sa.String(length=50), nullable=True),
    sa.Column('source_service', sa.String(length=50), nullable=True),
    sa.Column('task_id', sa.String(length=100), nullable=True),
    sa.Column('generation_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generation_cost', sa.Float(), nullable=True),
    sa.Column('popularity_score', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('match_boost', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['demo_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_image_demo_active', 'image_demos', ['is_active', 'status'], unique=False)
    op.create_index('idx_image_demo_keywords', 'image_demos', ['keywords'], unique=False, postgresql_using='gin')
    op.create_index('idx_image_demo_search', 'image_demos', ['prompt_normalized', 'category_slug', 'style_slug'], unique=False)
    op.create_index(op.f('ix_image_demos_category_slug'), 'image_demos', ['category_slug'], unique=False)
    op.create_index(op.f('ix_image_demos_keywords'), 'image_demos', ['keywords'], unique=False)
    op.create_index(op.f('ix_image_demos_prompt_normalized'), 'image_demos', ['prompt_normalized'], unique=False)
    op.create_index(op.f('ix_image_demos_style_slug'), 'image_demos', ['style_slug'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('payment_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number'),
    sa.UniqueConstraint('order_id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoices')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_image_demos_style_slug'), table_name='image_demos')
    op.drop_index(op.f('ix_image_demos_prompt_normalized'), table_name='image_demos')
    op.drop_index(op.f('ix_image_demos_keywords'), table_name='image_demos')
    op.drop_index(op.f('ix_image_demos_category_slug'), table_name='image_demos')
    op.drop_index('idx_image_demo_search', table_name='image_demos')
    op.drop_index('idx_image_demo_keywords', table_name='image_demos', postgresql_using='gin')
    op.drop_index('idx_image_demo_active', table_name='image_demos')
    op.drop_table('image_demos')
    op.drop_index(op.f('ix_demo_views_demo_id'), table_name='demo_views')
    op.drop_table('demo_views')
    op.drop_table('demo_videos')
    op.drop_index(op.f('ix_users_password_reset_token'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email_verification_token'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_prompt_cache_prompt_hash'), table_name='prompt_cache')
    op.drop_table('prompt_cache')
    op.drop_index(op.f('ix_plans_slug'), table_name='plans')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_demo_categories_slug'), table_name='demo_categories')
    op.drop_table('demo_categories')
    # ### end Alembic commands ###
