"""script.py.mako"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77591469f3e4'
down_revision = 'cff0ab0d7891'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verifications_email'), 'email_verifications', ['email'], unique=False)
    op.create_index(op.f('ix_email_verifications_id'), 'email_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_email_verifications_user_id'), 'email_verifications', ['user_id'], unique=False)
    op.add_column('plans', sa.Column('weekly_credits', sa.Integer(), nullable=True))
    op.add_column('plans', sa.Column('can_use_effects', sa.Boolean(), nullable=True))
    op.add_column('service_pricing', sa.Column('min_plan', sa.String(length=50), nullable=True))
    op.add_column('service_pricing', sa.Column('subscribers_only', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('credits_reset_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'credits_reset_at')
    op.drop_column('service_pricing', 'subscribers_only')
    op.drop_column('service_pricing', 'min_plan')
    op.drop_column('plans', 'can_use_effects')
    op.drop_column('plans', 'weekly_credits')
    op.drop_index(op.f('ix_email_verifications_user_id'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_id'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_email'), table_name='email_verifications')
    op.drop_table('email_verifications')
    # ### end Alembic commands ###
