"""script.py.mako"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '819bba13fb13'
down_revision = '24d2e773257a'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demo_videos', sa.Column('category_slug', sa.String(length=50), nullable=True))
    op.add_column('demo_videos', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('demo_videos', sa.Column('style_slug', sa.String(length=50), nullable=True))
    op.alter_column('demo_videos', 'generation_params',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='generation_params::jsonb')
    op.create_index('idx_demo_video_category', 'demo_videos', ['category_slug', 'is_active'], unique=False)
    op.create_index(op.f('ix_demo_videos_category_slug'), 'demo_videos', ['category_slug'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_demo_videos_category_slug'), table_name='demo_videos')
    op.drop_index('idx_demo_video_category', table_name='demo_videos')
    op.alter_column('demo_videos', 'generation_params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('demo_videos', 'style_slug')
    op.drop_column('demo_videos', 'image_url')
    op.drop_column('demo_videos', 'category_slug')
    # ### end Alembic commands ###
