"""script.py.mako"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ee2c1ad815f'
down_revision = '77591469f3e4'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_showcases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tool_category', sa.String(length=50), nullable=False),
    sa.Column('tool_id', sa.String(length=50), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('tool_name_zh', sa.String(length=100), nullable=True),
    sa.Column('source_image_url', sa.String(length=500), nullable=False),
    sa.Column('source_thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('prompt_zh', sa.Text(), nullable=True),
    sa.Column('result_image_url', sa.String(length=500), nullable=True),
    sa.Column('result_video_url', sa.String(length=500), nullable=True),
    sa.Column('result_thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('title_zh', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_zh', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('style_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('popularity_score', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('source_service', sa.String(length=50), nullable=True),
    sa.Column('generation_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_user_generated', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tool_showcase_category', 'tool_showcases', ['tool_category', 'is_active'], unique=False)
    op.create_index('idx_tool_showcase_featured', 'tool_showcases', ['is_featured', 'is_active'], unique=False)
    op.create_index('idx_tool_showcase_tool', 'tool_showcases', ['tool_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_tool_showcases_tool_category'), 'tool_showcases', ['tool_category'], unique=False)
    op.create_index(op.f('ix_tool_showcases_tool_id'), 'tool_showcases', ['tool_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_showcases_tool_id'), table_name='tool_showcases')
    op.drop_index(op.f('ix_tool_showcases_tool_category'), table_name='tool_showcases')
    op.drop_index('idx_tool_showcase_tool', table_name='tool_showcases')
    op.drop_index('idx_tool_showcase_featured', table_name='tool_showcases')
    op.drop_index('idx_tool_showcase_category', table_name='tool_showcases')
    op.drop_table('tool_showcases')
    # ### end Alembic commands ###
