"""script.py.mako"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '99d728708134'
down_revision = 'q4d5e6f7g8h9'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_material_language', table_name='materials')
    op.create_index(op.f('ix_materials_language'), 'materials', ['language'], unique=False)
    op.add_column('user_generations', sa.Column('input_text', sa.String(), nullable=True))
    op.add_column('user_generations', sa.Column('result_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index('idx_user_gen_created', table_name='user_generations')
    op.drop_index('idx_user_gen_user_tool', table_name='user_generations')
    op.create_index(op.f('ix_user_generations_created_at'), 'user_generations', ['created_at'], unique=False)
    op.drop_constraint('user_generations_user_id_fkey', 'user_generations', type_='foreignkey')
    op.create_foreign_key(None, 'user_generations', 'users', ['user_id'], ['id'])
    op.drop_column('user_generations', 'status')
    op.drop_column('user_generations', 'generation_steps')
    op.drop_column('user_generations', 'error_message')
    op.drop_column('user_generations', 'prompt')
    op.drop_column('user_generations', 'completed_at')
    op.drop_column('user_generations', 'result_thumbnail_url')
    op.drop_column('user_generations', 'generation_cost_usd')
    op.drop_column('user_generations', 'is_deleted')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_generations', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user_generations', sa.Column('generation_cost_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('user_generations', sa.Column('result_thumbnail_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('user_generations', sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('user_generations', sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('user_generations', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('user_generations', sa.Column('generation_steps', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('user_generations', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_generations', type_='foreignkey')
    op.create_foreign_key('user_generations_user_id_fkey', 'user_generations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_generations_created_at'), table_name='user_generations')
    op.create_index('idx_user_gen_user_tool', 'user_generations', ['user_id', 'tool_type'], unique=False)
    op.create_index('idx_user_gen_created', 'user_generations', ['created_at'], unique=False)
    op.drop_column('user_generations', 'result_metadata')
    op.drop_column('user_generations', 'input_text')
    op.drop_index(op.f('ix_materials_language'), table_name='materials')
    op.create_index('idx_material_language', 'materials', ['language', 'tool_type', 'is_active'], unique=False)
    # ### end Alembic commands ###
