"""script.py.mako"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae2b07d4b94'
down_revision = '05a5bdfb49cf'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('lookup_hash', sa.String(length=64), nullable=True))
    op.create_index('idx_material_lookup_hash', 'materials', ['lookup_hash'], unique=False)
    op.create_index(op.f('ix_materials_lookup_hash'), 'materials', ['lookup_hash'], unique=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_materials_lookup_hash'), table_name='materials')
    op.drop_index('idx_material_lookup_hash', table_name='materials')
    op.drop_column('materials', 'lookup_hash')
    # ### end Alembic commands ###
