"""script.py.mako"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cff0ab0d7891'
down_revision = 'd6f8f12ee01a'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_pricing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('credit_cost', sa.Integer(), nullable=False),
    sa.Column('api_cost_usd', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('max_duration', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_type')
    )
    op.create_index(op.f('ix_service_pricing_id'), 'service_pricing', ['id'], unique=False)
    op.create_table('credit_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=True),
    sa.Column('generation_id', sa.UUID(), nullable=True),
    sa.Column('package_id', sa.UUID(), nullable=True),
    sa.Column('payment_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['credit_packages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_transactions_id'), 'credit_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_credit_transactions_user_id'), 'credit_transactions', ['user_id'], unique=False)
    op.create_table('generations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('prompt_original', sa.Text(), nullable=False),
    sa.Column('prompt_enhanced', sa.Text(), nullable=True),
    sa.Column('input_image_url', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('credits_used', sa.Integer(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generations_id'), 'generations', ['id'], unique=False)
    op.create_index(op.f('ix_generations_user_id'), 'generations', ['user_id'], unique=False)
    op.add_column('credit_packages', sa.Column('display_name', sa.String(length=100), nullable=True))
    op.add_column('credit_packages', sa.Column('price_twd', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('credit_packages', sa.Column('price_usd', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('credit_packages', sa.Column('min_plan', sa.String(length=50), nullable=True))
    op.add_column('plans', sa.Column('display_name', sa.String(length=100), nullable=True))
    op.add_column('plans', sa.Column('price_twd', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('plans', sa.Column('price_usd', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('plans', sa.Column('monthly_credits', sa.Integer(), nullable=True))
    op.add_column('plans', sa.Column('topup_discount_rate', sa.DECIMAL(precision=3, scale=2), nullable=True))
    op.add_column('plans', sa.Column('has_watermark', sa.Boolean(), nullable=True))
    op.add_column('plans', sa.Column('pollo_limit', sa.Integer(), nullable=True))
    op.add_column('plans', sa.Column('goenhance_limit', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('subscription_credits', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('purchased_credits', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('bonus_credits', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('bonus_credits_expiry', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('current_plan_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('plan_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('plan_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_current_plan_id'), 'users', ['current_plan_id'], unique=False)
    op.create_foreign_key(None, 'users', 'plans', ['current_plan_id'], ['id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_current_plan_id'), table_name='users')
    op.drop_column('users', 'plan_expires_at')
    op.drop_column('users', 'plan_started_at')
    op.drop_column('users', 'current_plan_id')
    op.drop_column('users', 'bonus_credits_expiry')
    op.drop_column('users', 'bonus_credits')
    op.drop_column('users', 'purchased_credits')
    op.drop_column('users', 'subscription_credits')
    op.drop_column('plans', 'goenhance_limit')
    op.drop_column('plans', 'pollo_limit')
    op.drop_column('plans', 'has_watermark')
    op.drop_column('plans', 'topup_discount_rate')
    op.drop_column('plans', 'monthly_credits')
    op.drop_column('plans', 'price_usd')
    op.drop_column('plans', 'price_twd')
    op.drop_column('plans', 'display_name')
    op.drop_column('credit_packages', 'min_plan')
    op.drop_column('credit_packages', 'price_usd')
    op.drop_column('credit_packages', 'price_twd')
    op.drop_column('credit_packages', 'display_name')
    op.drop_index(op.f('ix_generations_user_id'), table_name='generations')
    op.drop_index(op.f('ix_generations_id'), table_name='generations')
    op.drop_table('generations')
    op.drop_index(op.f('ix_credit_transactions_user_id'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_id'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index(op.f('ix_service_pricing_id'), table_name='service_pricing')
    op.drop_table('service_pricing')
    # ### end Alembic commands ###
