"""script.py.mako"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd6f8f12ee01a'
down_revision = '817acc653944'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_examples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=50), nullable=False),
    sa.Column('topic_zh', sa.String(length=50), nullable=True),
    sa.Column('topic_en', sa.String(length=50), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('prompt_enhanced', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('video_url_watermarked', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('title_zh', sa.String(length=255), nullable=True),
    sa.Column('title_en', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('style_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('popularity_score', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('source_service', sa.String(length=50), nullable=True),
    sa.Column('generation_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_demo_example_featured', 'demo_examples', ['is_featured', 'is_active'], unique=False)
    op.create_index('idx_demo_example_topic', 'demo_examples', ['topic', 'is_active'], unique=False)
    op.create_index(op.f('ix_demo_examples_topic'), 'demo_examples', ['topic'], unique=False)
    op.add_column('prompt_cache', sa.Column('prompt_enhanced', sa.Text(), nullable=True))
    op.add_column('prompt_cache', sa.Column('prompt_embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('prompt_cache', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('prompt_cache', sa.Column('video_url', sa.String(length=500), nullable=True))
    op.add_column('prompt_cache', sa.Column('video_url_watermarked', sa.String(length=500), nullable=True))
    op.add_column('prompt_cache', sa.Column('usage_count', sa.Integer(), nullable=True))
    op.add_column('prompt_cache', sa.Column('source_service', sa.String(length=50), nullable=True))
    op.add_column('prompt_cache', sa.Column('generation_cost', sa.Float(), nullable=True))
    op.add_column('prompt_cache', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('prompt_cache', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('prompt_cache', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_cache', 'updated_at')
    op.drop_column('prompt_cache', 'is_active')
    op.drop_column('prompt_cache', 'status')
    op.drop_column('prompt_cache', 'generation_cost')
    op.drop_column('prompt_cache', 'source_service')
    op.drop_column('prompt_cache', 'usage_count')
    op.drop_column('prompt_cache', 'video_url_watermarked')
    op.drop_column('prompt_cache', 'video_url')
    op.drop_column('prompt_cache', 'image_url')
    op.drop_column('prompt_cache', 'prompt_embedding')
    op.drop_column('prompt_cache', 'prompt_enhanced')
    op.drop_index(op.f('ix_demo_examples_topic'), table_name='demo_examples')
    op.drop_index('idx_demo_example_topic', table_name='demo_examples')
    op.drop_index('idx_demo_example_featured', table_name='demo_examples')
    op.drop_table('demo_examples')
    # ### end Alembic commands ###
