"""add_new_pricing_tiers_and_features

Revision ID: v1a2b3c4d5e6
Revises: u3v4w5x6y7z8
Create Date: 2026-03-25 11:11:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'v1a2b3c4d5e6'
down_revision = 'u3v4w5x6y7z8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new columns to plans table
    op.add_column('plans', sa.Column('allowed_models', postgresql.JSON(astext_type=sa.Text()), server_default='["default"]', nullable=True))
    op.add_column('plans', sa.Column('social_media_batch_posting', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('plans', sa.Column('enterprise_features', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('plans', sa.Column('max_concurrent_generations', sa.Integer(), server_default='1', nullable=True))
    
    # Update currency default to TWD
    op.alter_column('plans', 'currency',
               existing_type=sa.VARCHAR(),
               server_default='TWD',
               existing_nullable=True)
    
    # Add new columns to service_pricing table
    op.add_column('service_pricing', sa.Column('model_type', sa.String(length=50), server_default='default', nullable=True))
    op.add_column('service_pricing', sa.Column('tool_category', sa.String(length=50), server_default='static', nullable=True))
    op.add_column('service_pricing', sa.Column('allowed_models', postgresql.JSON(astext_type=sa.Text()), server_default='["default"]', nullable=True))
    op.add_column('service_pricing', sa.Column('tool_type', sa.String(length=50), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_pricing', 'tool_type')
    op.drop_column('service_pricing', 'allowed_models')
    op.drop_column('service_pricing', 'tool_category')
    op.drop_column('service_pricing', 'model_type')
    
    op.alter_column('plans', 'currency',
               existing_type=sa.VARCHAR(),
               server_default='USD',
               existing_nullable=True)
    
    op.drop_column('plans', 'max_concurrent_generations')
    op.drop_column('plans', 'enterprise_features')
    op.drop_column('plans', 'social_media_batch_posting')
    op.drop_column('plans', 'allowed_models')
    # ### end Alembic commands ###