<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRouter } from 'vue-router'
import { useUIStore, useCreditsStore } from '@/stores'
import { useDemoMode } from '@/composables'
// PRESET-ONLY MODE: UploadZone removed - all users use presets
import CreditCost from '@/components/tools/CreditCost.vue'
import LoadingOverlay from '@/components/common/LoadingOverlay.vue'
import ImageUploader from '@/components/common/ImageUploader.vue'
import apiClient from '@/api/client'
import { demoApi } from '@/api/demo'

const { t, locale } = useI18n()
const router = useRouter()
const uiStore = useUIStore()
const creditsStore = useCreditsStore()
const isZh = computed(() => locale.value.startsWith('zh'))

// Demo mode. We call loadInputLibrary/loadEffectCatalog in onMounted so the
// composable's shared state is warm for other code paths, but this view's
// avatar grid still renders the curated 6-portrait UI — so we intentionally
// do not bind the library/catalog refs here.
const {
  isDemoUser,
  loadDemoTemplates,
  demoTemplates,
  resolveDemoTemplateResultUrl,
  generateOnDemand,
  loadInputLibrary,
  loadEffectCatalog,
} = useDemoMode()

const uploadedImage = ref<string | undefined>(undefined)
const resultVideo = ref<string | null>(null)
const isProcessing = ref(false)
// True when a demo user clicked Generate but the selected tile isn't backed
// by a real Material DB preset (db_empty fallback or missing preset id).
// Surfaces a persistent in-block message instead of a silent no-op.
const demoEmptyState = ref(false)
const script = ref('')
const selectedLanguage = ref('zh-TW')
const selectedVoice = ref('')
const voices = ref<any[]>([])
const selectedDefaultScriptId = ref<string | null>(null)
const selectedAvatarId = ref<string | null>(null)

const languageOptions = [
  { id: 'zh-TW', name: '繁體中文', flag: '🇹🇼' },
  { id: 'en', name: 'English', flag: '🇺🇸' }
]

// Frozen curated head-and-shoulders avatar portraits — Kling Avatar needs a
// big, centered face (full-body photos are rejected). Stored in a dedicated
// GCS path, separate from the full-body try-on models.
const _AVATARS_BASE = 'https://storage.googleapis.com/vidgo-media-vidgo-ai/static/avatars'

const femaleAvatars = [
  { id: 'female-1', gender: 'female' as const, name_zh: '怡君', name_en: 'Yi-Jun',   url: `${_AVATARS_BASE}/female-1.png` },
  { id: 'female-2', gender: 'female' as const, name_zh: '雅婷', name_en: 'Ya-Ting',  url: `${_AVATARS_BASE}/female-2.png` },
  { id: 'female-3', gender: 'female' as const, name_zh: '佳穎', name_en: 'Jia-Ying', url: `${_AVATARS_BASE}/female-3.png` },
]

const maleAvatars = [
  { id: 'male-1', gender: 'male' as const, name_zh: '志偉', name_en: 'Zhi-Wei',  url: `${_AVATARS_BASE}/male-1.png` },
  { id: 'male-2', gender: 'male' as const, name_zh: '冠宇', name_en: 'Guan-Yu',  url: `${_AVATARS_BASE}/male-2.png` },
  { id: 'male-3', gender: 'male' as const, name_zh: '宗翰', name_en: 'Zong-Han', url: `${_AVATARS_BASE}/male-3.png` },
]

// Combined list (order: females first, then males) for voice index
const defaultAvatars = [...femaleAvatars, ...maleAvatars]

// Voice index per avatar (same gender): each avatar gets a different voice (0, 1, 2, 3...)
function getVoiceIndexForAvatar(avatar: { id: string; gender: string }): number {
  const sameGender = defaultAvatars.filter(a => a.gender === avatar.gender)
  const idx = sameGender.findIndex(a => a.id === avatar.id)
  return idx >= 0 ? idx : 0
}

// Default scripts matching backend SCRIPT_MAPPING exactly (4 topics × 3 scripts = 12 scripts)
// IDs must match backend script IDs for preset lookup to work.
// Focus: 平民化產品 — everyday Taiwanese/Chinese consumer PRODUCTS (NOT services).
// Generated by: scripts/generate_citizen_life_prompts.py (synced with main_pregenerate.py SCRIPT_MAPPING)
const defaultScripts = [
  // spokesperson: Origin story / brand storytelling
  {
    id: 'spokesperson-1',
    text_zh: '我爸是做鐵工的，每天帶一個便宜保溫瓶，總是會漏水。所以我花了兩年研發這款真空保溫瓶——雙層不鏽鋼，保溫12小時。去年到現在賣超過8000個，只要599元。30天不滿意全額退費，放心試！',
    text_en: "My father was an ironworker. He carried a cheap thermos every day and it always leaked. That is why I spent two years developing this vacuum bottle—double-wall stainless steel, keeps drinks hot for 12 hours. We have sold over 8000 since last year. Only 599. Try it risk-free with our 30-day money-back guarantee!",
    category: 'spokesperson',
    category_zh: '品牌故事'
  },
  {
    id: 'spokesperson-2',
    text_zh: '阿嬤以前都用山上採的天然草本洗頭，80歲頭髮還是又黑又亮。我把她的配方做成了這瓶洗髮精——無矽靈、無硫酸鹽，12種草本精華。今年已經有超過3000位客人轉用。每瓶399元，你的頭髮會感謝你！',
    text_en: "My grandmother used to wash her hair with natural herbs from the mountains. At 80, she still had thick, beautiful hair. I turned her recipe into this shampoo—no silicone, no sulfate, just 12 kinds of herbal extracts. Over 3000 customers have switched to us this year. 399 per bottle. Your hair will thank you!",
    category: 'spokesperson',
    category_zh: '品牌故事'
  },
  {
    id: 'spokesperson-3',
    text_zh: '我家在阿里山種茶已經三代了。每年春天我天亮就上山手採，趁露水還在的時候。這款烏龍經過72小時五道烘焙。喝一口，你就能嚐到山的味道。150克只要590元，當天出貨、真空包裝鎖住鮮味！',
    text_en: "My family has been growing tea in Alishan for three generations. Every spring I hand-pick the leaves at dawn when the dew is still fresh. This oolong goes through five stages of roasting over 72 hours. One sip and you will taste the mountain. 150 grams for 590. We ship same-day, vacuum-sealed for freshness!",
    category: 'spokesperson',
    category_zh: '品牌故事'
  },
  // product_intro: Social proof / before-after / demo technique
  {
    id: 'product-intro-1',
    text_zh: '你看——我只要放米、加水、按一個按鈕，25分鐘後就是粒粒分明的完美白飯，每次都一樣。這台智慧電子鍋有8種模式、不沾內鍋、24小時預約。網路上超過1500則五星評價。只要1290元，在家就能煮出餐廳等級的飯。本週免運費！',
    text_en: "Check this out—I just put in rice, water, and pressed one button. 25 minutes later? Perfect fluffy rice, every single time. This smart cooker has 8 cooking modes, a non-stick inner pot, and a 24-hour timer. Over 1500 five-star reviews online. Only 1290 for restaurant-quality rice at home. Free shipping this week!",
    category: 'product_intro',
    category_zh: '產品開箱'
  },
  {
    id: 'product-intro-2',
    text_zh: '以前我刷牙30秒就覺得好了，結果牙醫說我有三顆蛀牙。換了這支音波牙刷——每分鐘40000次震動、2分鐘智慧計時、充一次電用30天。半年後零蛀牙。799元附兩個替換刷頭，你的牙齒會感謝你！',
    text_en: "I used to brush for 30 seconds and call it done. Then my dentist said I had three cavities. I switched to this sonic toothbrush—40000 vibrations per minute, 2-minute smart timer, 30-day battery life. Six months later, zero cavities. 799 with two extra brush heads. Your teeth will thank you!",
    category: 'product_intro',
    category_zh: '產品開箱'
  },
  {
    id: 'product-intro-3',
    text_zh: '我比較了20款檯燈才選了這一台。零頻閃、色溫可調從暖光到白光、還有USB充電孔。加班到深夜眼睛不再痠痛。690元含兩年保固。超過800位學生和遠距工作者推薦。照亮你的工作空間！',
    text_en: "I compared 20 desk lamps before choosing this one. Zero flicker, adjustable color temperature from warm to cool, and a built-in USB charging port. My eyes stopped hurting after late-night work. 690 and it comes with a 2-year warranty. Over 800 students and remote workers recommend it. Light up your workspace!",
    category: 'product_intro',
    category_zh: '產品開箱'
  },
  // customer_service: Trust-building / guarantee (reduces purchase anxiety)
  {
    id: 'customer-service-1',
    text_zh: '擔心網路買充電線踩雷？我懂。所以我們每條線都通過5000次彎折測試。一年內斷裂免費換新——不問原因。LINE傳訂單號碼就好。賣出超過10000條，換貨率不到0.5%。兩條一組只要349元！',
    text_en: "Worried about buying a charging cable online? I understand. That is why every cable we sell goes through a 5000-bend test. If it breaks within one year, we replace it for free—no questions asked. Just message us on LINE with your order number. Over 10000 cables sold, replacement rate under 0.5 percent. 349 for a set of two!",
    category: 'customer_service',
    category_zh: '客戶服務'
  },
  {
    id: 'customer-service-2',
    text_zh: '很多媽媽問我：這瓶洗衣精洗寶寶衣服真的安全嗎？讓我來回答。99%植物萃取、皮膚科醫師測試、無螢光劑。SGS檢驗報告就在我們網站上。2000ml只要299元，全家都能用。有問題隨時LINE我們，2小時內回覆！',
    text_en: "A lot of moms ask me: is this laundry detergent really safe for baby clothes? Let me answer. It is 99 percent plant-derived, dermatologist-tested, and free of fluorescent agents. We even have the SGS test report on our website. 2000ml for only 299. Perfect for the whole family. Questions? Message us anytime on LINE—we reply within 2 hours!",
    category: 'customer_service',
    category_zh: '客戶服務'
  },
  {
    id: 'customer-service-3',
    text_zh: '新手爸媽，我知道你們對奶瓶有很多問題。最常問的三個：不含BPA嗎？是的，100%。防脹氣閥真的有用嗎？92%的家長說寶寶脹氣減少了。可以消毒嗎？耐熱180度沒問題。每支490元。7天內寶寶不適應可免費退貨！',
    text_en: "New parents, I know you have questions about our baby bottle. Here are the top three: Is it BPA-free? Yes, 100 percent. Does the anti-colic valve really work? 92 percent of parents say their baby had less gas. Can I sterilize it? Yes, it is heat-resistant up to 180 degrees. 490 per bottle. Free return within 7 days if baby does not like it!",
    category: 'customer_service',
    category_zh: '客戶服務'
  },
  // social_media: Interactive / viral hooks / emotional (drives shares)
  {
    id: 'social-media-1',
    text_zh: '馬上存下這支影片！這是我們最暢銷的保濕面膜——原價一盒10片499元。但只限今天，買一送一。20片只要499！上次辦這個活動3小時就賣完了。追蹤我們開啟通知才不會錯過。連結在自介！',
    text_en: "Save this video right now! This is our best-selling hydrating face mask—normally 499 for a box of 10. But today only, buy one box get one free. That is 20 masks for 499! Last time we did this, we sold out in 3 hours. Follow us and turn on notifications so you never miss a deal. Link in bio!",
    category: 'social_media',
    category_zh: '社群行銷'
  },
  {
    id: 'social-media-2',
    text_zh: '先別滑了——你一定要聽聽這個。這副無線耳機續航30小時、有降噪、還防水。最棒的是只要890元。我已經用了6個月，健身房、公車上、甚至淋雨都沒問題。限時特賣今晚12點結束，趕快點連結，賣完就沒了！',
    text_en: "Stop scrolling—you need to hear this. These wireless earbuds have 30-hour battery life, noise cancellation, and they are waterproof. The best part? Only 890. I have been using them for 6 months at the gym, on the bus, even in the rain. Flash sale ends tonight at midnight. Tap the link now before they sell out!",
    category: 'social_media',
    category_zh: '社群行銷'
  },
  {
    id: 'social-media-3',
    text_zh: '我把這包芒果乾給10個同事吃，沒說價錢。每個人都猜超過300元。真正的價格？大包裝只要169元。屏東愛文芒果製作、無添加糖。標記一個愛吃芒果的朋友！買三包免運。辦公室最佳零嘴！',
    text_en: "I gave this dried mango to 10 coworkers without telling them the price. Every single one guessed it costs over 300. The real price? 169 for a big bag. Made in Pingtung from Irwin mangoes, no added sugar. Tag someone who loves mango! Buy 3 bags and get free shipping. Best office snack ever!",
    category: 'social_media',
    category_zh: '社群行銷'
  }
]

// Pre-generated preset cache: key = "avatar-id_script-id_language", value = preset ID
const preGeneratedTemplateIds = ref<Record<string, string>>({})

// Get result key for current selection
const currentResultKey = computed(() => {
  if (!selectedAvatarId.value || !selectedDefaultScriptId.value) return null
  return `${selectedAvatarId.value}_${selectedDefaultScriptId.value}_${selectedLanguage.value}`
})

// Get pre-generated preset ID for current avatar×script×language combination
const currentPreGeneratedTemplateId = computed(() => {
  if (!currentResultKey.value) return null
  return preGeneratedTemplateIds.value[currentResultKey.value] || null
})

// Selected avatar info
const selectedAvatar = computed(() => {
  return defaultAvatars.find(a => a.id === selectedAvatarId.value) || null
})

// Voice options filtered by selected avatar gender (used to set fixed voice per avatar)
const filteredVoices = computed(() => {
  if (!selectedAvatar.value) return voices.value
  const avatarGender = selectedAvatar.value.gender
  return voices.value.filter(v => v.gender === avatarGender)
})


async function loadVoices() {
  try {
    const response = await apiClient.get(`/api/v1/tools/avatar/voices?language=${selectedLanguage.value}`)
    voices.value = response.data || []
    // Auto-select first voice matching avatar gender
    selectMatchingVoice()
  } catch (error) {
    console.error('Failed to load voices:', error)
    // Fallback voices - one per avatar (4 female, 4 male)
    voices.value = selectedLanguage.value === 'zh-TW'
      ? [
          { id: 'zh-TW-female-1', name: '小曉', gender: 'female' },
          { id: 'zh-TW-female-2', name: '小晨', gender: 'female' },
          { id: 'zh-TW-female-3', name: '曉夢', gender: 'female' },
          { id: 'zh-TW-female-4', name: '小萱', gender: 'female' },
          { id: 'zh-TW-male-1', name: '雲熙', gender: 'male' },
          { id: 'zh-TW-male-2', name: '雲揚', gender: 'male' },
          { id: 'zh-TW-male-3', name: '雲傑', gender: 'male' },
          { id: 'zh-TW-male-4', name: '雲皓', gender: 'male' }
        ]
      : [
          { id: 'en-US-fable', name: 'Fable', gender: 'female' },
          { id: 'en-US-nova', name: 'Nova', gender: 'female' },
          { id: 'en-US-shimmer', name: 'Shimmer', gender: 'female' },
          { id: 'en-US-echo', name: 'Echo', gender: 'male' },
          { id: 'en-US-onyx', name: 'Onyx', gender: 'male' }
        ]
    selectMatchingVoice()
  }
}

function selectMatchingVoice() {
  // Each avatar gets a different voice by index (female-1→voice0, female-2→voice1, ...)
  if (selectedAvatar.value && filteredVoices.value.length > 0) {
    const idx = getVoiceIndexForAvatar(selectedAvatar.value)
    const voice = filteredVoices.value[idx % filteredVoices.value.length]
    selectedVoice.value = voice.id
  } else if (voices.value.length > 0) {
    selectedVoice.value = voices.value[0].id
  }
}



function selectAvatar(avatar: typeof defaultAvatars[0]) {
  selectedAvatarId.value = avatar.id
  uploadedImage.value = avatar.url
  resultVideo.value = null
  demoEmptyState.value = false
  // Assign this avatar's distinct voice (by index)
  selectMatchingVoice()
}

function selectDefaultScript(scriptItem: typeof defaultScripts[0]) {
  selectedDefaultScriptId.value = scriptItem.id
  // Script text follows the selected VOICE language (selectedLanguage), not
  // the UI locale (isZh). Visitor browsing in Chinese UI can still pick an
  // English-speaking avatar and see the English script preview.
  script.value = selectedLanguage.value === 'zh-TW' ? scriptItem.text_zh : scriptItem.text_en
  resultVideo.value = null
  demoEmptyState.value = false
}

async function generateAvatar() {
  if (!uploadedImage.value) {
    uiStore.showError(isZh.value ? '請選擇頭像照片' : 'Please select an avatar photo')
    return
  }

  if (!script.value) {
    uiStore.showError(isZh.value ? '請選擇或輸入腳本' : 'Please select or enter a script')
    return
  }

  // For demo users, ONLY allow pre-generated combinations
  if (isDemoUser.value) {
    // Must use default avatar (not custom upload)
    if (!selectedAvatarId.value) {
      uiStore.showError(isZh.value ? '請選擇預設頭像' : 'Please select a default avatar')
      return
    }

    // Must use default script
    if (!selectedDefaultScriptId.value) {
      uiStore.showError(isZh.value ? '請選擇預設腳本' : 'Please select a default script')
      return
    }

    // Clear stale result so loading overlay is the only thing visible.
    resultVideo.value = null
    isProcessing.value = true
    try {
      // Simulate processing delay for demo effect
      await new Promise(resolve => setTimeout(resolve, 1500))

      const preGeneratedTemplateId = currentPreGeneratedTemplateId.value
      if (preGeneratedTemplateId) {
        const demoResultUrl = await resolveDemoTemplateResultUrl(preGeneratedTemplateId)
        if (demoResultUrl) {
          resultVideo.value = demoResultUrl
          uiStore.showSuccess(isZh.value ? '生成成功（示範）' : 'Generated successfully (Demo)')
          return
        }
      }

      const template = demoTemplates.value.find(t => {
        const params = (t as any).input_params || {}
        if (params.avatar_id === selectedAvatarId.value &&
            params.script_id === selectedDefaultScriptId.value &&
            (!params.language || params.language === selectedLanguage.value)) {
          return true
        }
        return false
      })

      if (template?.id) {
        const demoResultUrl = await resolveDemoTemplateResultUrl(template.id)
        if (demoResultUrl) {
          resultVideo.value = demoResultUrl
          if (currentResultKey.value) {
            preGeneratedTemplateIds.value[currentResultKey.value] = template.id
          }
          uiStore.showSuccess(isZh.value ? '生成成功（示範）' : 'Generated successfully (Demo)')
          return
        }
      }

      // Cache-through on demand. Pass avatar_id + language + script category
      // so the backend honors the visitor's choices instead of falling back
      // to a random hardcoded seed.
      const scriptCategory = defaultScripts.find(s => s.id === selectedDefaultScriptId.value)?.category
      uiStore.showInfo(isZh.value ? '此組合尚未生成，正在為您即時生成（約 3-5 分鐘）...' : 'Generating in real-time (3-5 min)...')
      const onDemandUrl = await generateOnDemand('ai_avatar', scriptCategory, {
        product_id: selectedAvatarId.value || undefined,
        language: selectedLanguage.value,
        input_image_url: uploadedImage.value || undefined,
        effect_prompt: script.value || undefined,
      })
      if (onDemandUrl) {
        resultVideo.value = onDemandUrl
        uiStore.showSuccess(isZh.value ? '頭像生成成功' : 'Avatar generated successfully')
      } else {
        demoEmptyState.value = true
        uiStore.showError(isZh.value ? '頭像服務暫時無法使用，請稍後再試或訂閱解鎖完整功能' : 'Avatar service temporarily unavailable. Please try again later or subscribe.')
      }
    } finally {
      isProcessing.value = false
    }
    return
  }

  // For subscribed users, call API
  isProcessing.value = true
  try {
    let imageUrl = uploadedImage.value
    if (uploadedImage.value?.startsWith('data:')) {
      const blob = await fetch(uploadedImage.value).then(r => r.blob())
      const uploaded = await demoApi.uploadImage(blob as File)
      imageUrl = uploaded.url
    }

    const response = await apiClient.post('/api/v1/tools/avatar', {
      image_url: imageUrl,
      script: script.value,
      language: selectedLanguage.value,
      voice_id: selectedVoice.value,
      duration: 30,
      aspect_ratio: '9:16',
      resolution: '720p'
    })

    if (response.data.success && response.data.result_url) {
      resultVideo.value = response.data.result_url
      creditsStore.deductCredits(response.data.credits_used || 15)
      uiStore.showSuccess(t('common.success'))
    } else {
      uiStore.showError(response.data.message || 'Generation failed')
    }
  } catch (error: any) {
    uiStore.showError(error.response?.data?.detail || 'Generation failed')
  } finally {
    isProcessing.value = false
  }
}



onMounted(async () => {
  loadVoices()
  await Promise.all([
    loadDemoTemplates('ai_avatar'),
    // Pregenerated Vertex Imagen head-shots (3:4 aspect) so Kling's face
    // detector accepts them; and the script catalog whose `prompt` is the
    // effect_prompt cached against each headshot.
    loadInputLibrary('ai_avatar'),
    loadEffectCatalog('ai_avatar', locale.value),
  ])

  // Populate pre-generated preset cache from loaded templates
  demoTemplates.value.forEach(template => {
    const params = (template as any).input_params || {}
    if (params.avatar_id && params.script_id && params.language) {
      const key = `${params.avatar_id}_${params.script_id}_${params.language}`
      preGeneratedTemplateIds.value[key] = template.id
    }
  })

  // Auto-select first avatar and first script for demo users
  if (isDemoUser.value) {
    if (defaultAvatars.length > 0) {
      selectAvatar(defaultAvatars[0])
    }
    if (defaultScripts.length > 0) {
      selectDefaultScript(defaultScripts[0])
    }
  }
})

watch(selectedLanguage, () => {
  loadVoices()
  // Update script text to match the new voice language.
  if (selectedDefaultScriptId.value) {
    const scriptItem = defaultScripts.find(s => s.id === selectedDefaultScriptId.value)
    if (scriptItem) {
      script.value = selectedLanguage.value === 'zh-TW' ? scriptItem.text_zh : scriptItem.text_en
    }
  }
})

// When avatar changes, auto-select matching voice
watch(selectedAvatarId, () => {
  selectMatchingVoice()
})
</script>

<template>
  <div class="min-h-screen pt-24 pb-20" style="background: #09090b; color: #f5f5fa;">
    <LoadingOverlay :show="isProcessing" :message="t('tools.avatar.processing')" />

    <div class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
      <!-- Back Button -->
      <button
        @click="router.back()"
        class="mb-6 flex items-center gap-2 text-dark-300 hover:text-dark-50 transition-colors"
      >
        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
        </svg>
        {{ t('common.back') }}
      </button>

      <!-- Header -->
      <div class="text-center mb-12">
        <h1 class="text-4xl font-bold text-dark-50 mb-4">
          {{ t('tools.avatar.name') }}
        </h1>
        <p class="text-xl text-dark-300">
          {{ t('tools.avatar.longDesc') }}
        </p>

        <!-- Subscribe Notice for Demo Users -->
        <div v-if="isDemoUser" class="mt-4 inline-flex items-center gap-2 px-4 py-2 bg-primary-500/20 text-primary-400 rounded-lg text-sm">
          <RouterLink to="/pricing" class="hover:underline">
            {{ isZh ? '訂閱以解鎖更多功能' : 'Subscribe to unlock more features' }}
          </RouterLink>
        </div>
      </div>

      <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <!-- Left Panel - Input (example mode: language + script first, then avatar, then voice) -->
        <div class="space-y-6">
          <!-- 1. Language & Script (present first so user chooses language and script) -->
          <div class="card">
            <h3 class="text-lg font-semibold text-dark-50 mb-4">{{ isZh ? '選擇語言與腳本' : 'Choose Language & Script' }}</h3>
            <!-- Language -->
            <div class="mb-6">
              <label class="label">{{ t('tools.avatar.language') }}</label>
              <div class="flex gap-3">
                <button
                  v-for="lang in languageOptions"
                  :key="lang.id"
                  @click="selectedLanguage = lang.id"
                  class="flex-1 py-3 rounded-xl border-2 transition-all flex items-center justify-center gap-2"
                  :class="selectedLanguage === lang.id
                    ? 'border-primary-500 bg-primary-500/10'
                    : 'hover:border-dark-500'" style="border-color: rgba(255,255,255,0.08);">
                >
                  <span>{{ lang.flag }}</span>
                  <span>{{ lang.name }}</span>
                </button>
              </div>
            </div>
            <!-- Script Selection -->
            <div>
              <label class="label">{{ t('tools.avatar.script') }}</label>
              <p class="text-sm text-dark-300 mb-2">{{ isZh ? '選擇預設腳本' : 'Select Script' }}</p>
              <div class="space-y-2 max-h-48 overflow-y-auto">
                <button
                  v-for="scriptItem in defaultScripts"
                  :key="scriptItem.id"
                  @click="selectDefaultScript(scriptItem)"
                  class="w-full text-left p-3 rounded-lg border-2 transition-all text-sm"
                  :class="selectedDefaultScriptId === scriptItem.id
                    ? 'border-primary-500 bg-primary-500/10'
                    : 'hover:border-dark-500'" style="border-color: rgba(255,255,255,0.08);">
                >
                  <span class="inline-block px-2 py-0.5 text-xs bg-dark-600 text-dark-300 rounded mb-1">
                    {{ isZh ? scriptItem.category_zh : scriptItem.category }}
                  </span>
                  <p class="text-dark-200">
                    {{ (selectedLanguage === 'zh-TW' ? scriptItem.text_zh : scriptItem.text_en).slice(0, 60) }}...
                  </p>
                </button>
              </div>
            </div>
            <!-- Show selected script -->
            <div v-if="script" class="mt-4 p-3 rounded-lg" style="background: #141420;">
              <p class="text-sm text-dark-200">{{ script }}</p>
            </div>
            <p class="text-xs text-dark-400 mt-2">{{ t('tools.avatar.maxSpeech') }}</p>
          </div>

          <!-- 2. Avatar Selection -->
          <div class="card">
            <h3 class="text-lg font-semibold text-dark-50 mb-4">{{ t('tools.avatar.avatarPhoto') }}</h3>

            <!-- Female Avatars (Asian/Chinese) -->
            <div class="mb-4">
              <p class="text-sm text-dark-300 mb-2">{{ isZh ? '女性頭像' : 'Female Avatars' }}</p>
              <div class="grid grid-cols-2 sm:grid-cols-4 gap-3">
                <button
                  v-for="avatar in femaleAvatars"
                  :key="avatar.id"
                  @click="selectAvatar(avatar)"
                  class="relative aspect-square rounded-xl overflow-hidden border-2 transition-all"
                  :class="selectedAvatarId === avatar.id
                    ? 'border-primary-500 ring-2 ring-primary-500/50'
                    : 'hover:border-dark-500'" style="border-color: rgba(255,255,255,0.08);">
                >
                  <!-- Always show static Asian/Chinese avatar photo (no video overlay) -->
                  <img
                    :src="avatar.url"
                    :alt="isZh ? avatar.name_zh : avatar.name_en"
                    class="w-full h-full object-cover"
                    loading="lazy"
                  />
                  <div class="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/70 to-transparent p-2">
                    <p class="text-xs text-dark-50 text-center">{{ isZh ? avatar.name_zh : avatar.name_en }}</p>
                  </div>
                </button>
              </div>
            </div>

            <!-- Male Avatars -->
            <div class="mb-4">
              <p class="text-sm text-dark-300 mb-2">{{ isZh ? '男性頭像' : 'Male Avatars' }}</p>
              <div class="grid grid-cols-2 sm:grid-cols-4 gap-3">
                <button
                  v-for="avatar in maleAvatars"
                  :key="avatar.id"
                  @click="selectAvatar(avatar)"
                  class="relative aspect-square rounded-xl overflow-hidden border-2 transition-all"
                  :class="selectedAvatarId === avatar.id
                    ? 'border-primary-500 ring-2 ring-primary-500/50'
                    : 'hover:border-dark-500'" style="border-color: rgba(255,255,255,0.08);">
                >
                  <!-- Always show static Asian/Chinese avatar photo (no video overlay) -->
                  <img
                    :src="avatar.url"
                    :alt="isZh ? avatar.name_zh : avatar.name_en"
                    class="w-full h-full object-cover"
                    loading="lazy"
                  />
                  <div class="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/70 to-transparent p-2">
                    <p class="text-xs text-dark-50 text-center">{{ isZh ? avatar.name_zh : avatar.name_en }}</p>
                  </div>
                </button>
              </div>
            </div>

            <!-- Subscriber Interface: Upload Zone -->
            <div v-if="!isDemoUser" class="mb-6">
               <h4 class="text-sm font-medium text-dark-300 mb-2">{{ isZh ? '上傳頭像 (正面人臉)' : 'Upload Portrait (Front-facing)' }}</h4>
               <ImageUploader 
                 v-model="uploadedImage" 
                 :label="isZh ? '點擊上傳或拖放頭像照片' : 'Drop portrait photo here'"
                 class="mb-4"
                 @update:model-value="selectedAvatarId = null"
               />
            </div>
            
            <!-- PRESET-ONLY MODE: Custom upload REMOVED - all users use preset avatars -->
          </div>

          <!-- Custom Script Textarea (subscribers only) -->
          <div v-if="!isDemoUser" class="card">
            <label class="block text-sm font-medium text-dark-300 mb-2">
              {{ isZh ? '自訂腳本' : 'Custom Script' }}
            </label>
            <textarea
              v-model="script"
              rows="4"
              class="w-full rounded-lg p-3 focus:outline-none focus:border-primary-500" style="background: #141420; border: 1px solid rgba(255,255,255,0.08); color: #f5f5fa;">
              :placeholder="isZh ? '輸入您的腳本內容 (建議 100 字以內)...' : 'Enter your script here (max 100 words)...'"
              maxlength="500"
              @input="selectedDefaultScriptId = null"
            ></textarea>
            <div class="text-right text-xs text-dark-400 mt-1">
              {{ script.length }} / 500
            </div>
          </div>

          <!-- 3. Generate (voice is fixed per avatar – no user choice) -->
          <div class="card">
            <h3 class="text-lg font-semibold text-dark-50 mb-4">{{ isZh ? '產生影片' : 'Generate' }}</h3>
            <p class="text-xs text-dark-400 mb-4">
              {{ isZh ? '每位頭像已固定對應專屬聲音，只需選擇頭像與腳本即可。' : 'Each avatar has a fixed voice. Just pick an avatar and a script.' }}
            </p>
            <!-- Credit Cost & Generate -->
            <div class="pt-2">
              <CreditCost service="ai_avatar" />
              <button
                @click="generateAvatar"
                :disabled="!uploadedImage || !script || isProcessing"
                class="btn-primary w-full mt-4"
              >
                {{ t('common.generate') }}
              </button>
            </div>
          </div>
        </div>

        <!-- Right Panel - Result -->
        <div class="card h-fit sticky top-24">
          <h3 class="text-lg font-semibold text-dark-50 mb-4">{{ t('tools.avatar.generatedVideo') }}</h3>

          <div v-if="resultVideo" class="space-y-4">
            <video
              :src="resultVideo"
              controls
              class="w-full rounded-xl"
              autoplay
              loop
            />

            <!-- Watermark badge -->
            <div class="text-center text-xs text-dark-400">vidgo.ai</div>

            <!-- Download / Action Buttons -->
            <div class="flex gap-3">
               <a
                 v-if="!isDemoUser"
                 :href="resultVideo"
                 download="vidgo_avatar_video.mp4"
                 class="btn-primary flex-1 text-center py-3 flex items-center justify-center"
               >
                 <span class="mr-2">📥</span> {{ t('common.download') }}
               </a>

               <RouterLink v-else to="/pricing" class="btn-primary w-full text-center block">
                 {{ isZh ? '訂閱以獲得完整功能' : 'Subscribe for Full Access' }}
               </RouterLink>
            </div>
          </div>

          <div v-else-if="demoEmptyState" class="aspect-[9/16] max-h-96 flex flex-col items-center justify-center rounded-xl text-center px-6 gap-3" style="background: #141420; border: 1px solid rgba(255,255,255,0.08);">
            <span class="text-2xl">🔒</span>
            <p class="text-sm text-dark-200">
              {{ isZh ? '此範例尚未預生成結果' : 'No pre-generated result for this example yet' }}
            </p>
            <RouterLink to="/pricing" class="btn-primary text-sm px-4 py-2">
              {{ isZh ? '訂閱以使用完整 AI 功能' : 'Subscribe to use the real AI' }}
            </RouterLink>
          </div>

          <div v-else class="aspect-[9/16] max-h-96 flex items-center justify-center rounded-xl text-dark-400" style="background: #141420;">
            <div class="text-center">
              <span class="text-5xl block mb-4">🎭</span>
              <p>{{ t('tools.avatar.videoPlaceholder') }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
