<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch } from 'vue'
import { RouterLink, useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { useAuthStore } from '@/stores'
import { useBrandingStore } from '@/stores/branding'
import { useLocalized } from '@/composables'
import { TOOL_EXAMPLES, LANDING_HIGHLIGHTS } from '@/data/toolExamples'

const { t, tm, locale } = useI18n()
const router = useRouter()
const authStore = useAuthStore()
const brandingStore = useBrandingStore()
// 5-language picker — fixes ja/ko/es fall-through (BUG-017).
const { L } = useLocalized()

// Admin-editable hero tagline (added 2026-05-23). When the admin types
// brand_tagline_zh / brand_tagline_en in /admin/branding, that string
// replaces the hardcoded `t('lp.sub1')` headline subtitle. Empty/null
// falls back to the i18n default so unconfigured installs render fine.
//
// Locale handling (2026-06-02): admin only stores _zh/_en. For ja/ko/es
// visitors, respect i18n fallback rather than leaking English admin copy.
const brandTagline = computed(() => {
  const s = brandingStore.settings
  const l = String(locale.value || '')
  if (l.startsWith('zh')) return s.brand_tagline_zh || ''
  if (l.startsWith('en')) return s.brand_tagline_en || ''
  return ''
})

// ── Real demo data from API ──
const demoImages = ref<Record<string, { before: string; after: string }[]>>({})
const demoLoading = ref(true)

// Interior before/after hero image fallback — if the GCS asset 404s we hide
// the broken <img> and surface a styled gradient placeholder instead.
const interiorBeforeFailed = ref(false)
const interiorAfterFailed = ref(false)

// Fallback images — shown only as a last resort while real AI results load.
// Each tool MUST use a logically-PAIRED before/after (same subject, real
// transformation) so visitors never see two unrelated images. The previous
// fallback pairs paired "product-1 → product-2" and "female-1 → male-1",
// which made the demo look broken. We now use the curated `examples/` GCS
// assets where bg/X.png (raw product with background), ps/X.png (product in
// scene), fx/X.png (effect applied), room/X.png (designed room), and
// vid/X.png (short-video still) all share a subject id, so a `bubbletea`
// before maps to a `bubbletea` after.
const _GCS = 'https://storage.googleapis.com/vidgo-media-vidgo-ai'
const FALLBACK: Record<string, { before: string; after: string }> = {
  // try_on: flat trench-coat garment → real try-on render of the same coat
  // on a female model. Both files are stable, public GCS paths owned by us
  // (the "after" was generated by our own try-on tool and persisted to a
  // demo path so signed URLs / 14-day expiry never affect the homepage).
  try_on: {
    before: `${_GCS}/static/tryon/garments/garment-coat.png`,
    after:  `${_GCS}/examples/tryon/demo-female-coat.png`,
  },
  // background_removal: same bubble-tea cup, with grey backdrop vs cleanly
  // cut out on transparent. Hero/* pair was regenerated 2026-05-11 because
  // the legacy fx/bubbletea.png had recolored the drink itself, making the
  // tool look like a color-changer rather than a bg remover.
  background_removal: {
    before: `${_GCS}/examples/bg/bubbletea.png`,
    after:  `${_GCS}/examples/hero/background_removal_after.png`,
  },
  // room_redesign: same room photo → restyled version of THAT room (not a
  // different room). before/after must be a true redesign pair so users
  // understand the tool transforms their own space rather than swapping
  // it for a stock photo.
  room_redesign: {
    before: `${_GCS}/examples/room/living-room.png`,
    after:  `${_GCS}/examples/hero/room_redesign_after.png`,
  },
  // short_video: still frame product photo → motion-ready cinematic still
  short_video: {
    before: `${_GCS}/examples/bg/bubbletea.png`,
    after:  `${_GCS}/examples/vid/bubbletea.png`,
  },
  // product_scene: same bubble-tea cup, on white vs placed on a pastel
  // marble countertop. Hero/* pair was regenerated 2026-05-11 because the
  // legacy ps/bubbletea.png had recolored the cup teal, making the tool
  // look like it changed the product rather than just the scene.
  product_scene: {
    before: `${_GCS}/examples/bg/bubbletea.png`,
    after:  `${_GCS}/examples/hero/product_scene_after.png`,
  },
  // ai_avatar: input headshot → talking avatar still (use the same person's
  // portrait twice rather than swap genders, since the tool animates ONE
  // photo, it does not change the person)
  ai_avatar: {
    before: `${_GCS}/examples/avatar/yating.png`,
    after:  `${_GCS}/examples/avatar/yating.png`,
  },
}

function demo(cat: string, idx: 'before' | 'after') {
  const list = demoImages.value[cat]
  if (list && list.length > 0) {
    const pair = list[0]
    // Background removal: the seeded DB presets use PiAPI-generated input
    // images that are already on a clean white background, so the before/
    // after preview shows two near-identical images and the demo looks
    // broken. The curated `examples/bg/*.png` → `examples/fx/*.png` pair is
    // a real product-with-background → BG-removed cutout, so override here
    // when the API returns one of those auto-generated PiAPI inputs.
    if (cat === 'background_removal' && /\/piapi_[0-9a-f]+\.png/.test(pair.before)) {
      return FALLBACK.background_removal[idx]
    }
    // Legacy seed pairs for these two tools recolored the product /
    // swapped the room instead of preserving the subject (visible as e.g.
    // a clear bubble tea cup becoming a teal cup in the "after"). Force
    // the curated `examples/hero/*` pair which was regenerated 2026-05-11
    // to show the SAME subject in a transformed scene.
    if (cat === 'background_removal' && /\/fx\/bubbletea\.png/.test(pair.after)) {
      return FALLBACK.background_removal[idx]
    }
    if (cat === 'product_scene' && /\/ps\/bubbletea\.png/.test(pair.after)) {
      return FALLBACK.product_scene[idx]
    }
    if (cat === 'room_redesign' && /\/examples\/room\/living-japanese\.png/.test(pair.after)) {
      return FALLBACK.room_redesign[idx]
    }
    return idx === 'before' ? pair.before : pair.after
  }
  return FALLBACK[cat]?.[idx] || ''
}

function fallbackImg(e: Event, cat: string, type: 'before' | 'after') {
  const img = e.target as HTMLImageElement
  const fb = FALLBACK[cat]?.[type]
  if (fb && img.src !== fb) img.src = fb
}

const demoCats = ['try_on', 'background_removal', 'room_redesign', 'short_video', 'product_scene']
let pollTimer: ReturnType<typeof setInterval> | null = null

// Hero interactive demo tabs (label resolved via i18n at render time)
const heroDemoTabs = [
  { key: 'product_scene' },
  { key: 'background_removal' },
  { key: 'try_on' },
  { key: 'room_redesign' },
] as const
const activeDemoTab = ref<typeof heroDemoTabs[number]['key']>('product_scene')

// ── Multi-example helpers ─────────────────────────────────────────────
// Show up to `n` real, validated before/after pairs per category instead
// of just list[0]. Generalises the old per-filename overrides into one
// rule set: drop empty/identical pairs and auto-generated near-identical
// inputs, dedupe by result, and always LEAD with the curated FALLBACK so
// every region opens with a known-correct example even when seeded rows
// are sparse or low quality.
function demoList(cat: string, n = 4): { before: string; after: string }[] {
  const out: { before: string; after: string }[] = []
  const seen = new Set<string>()
  const push = (p?: { before: string; after: string } | null) => {
    if (!p || !p.after) return
    if (p.after === p.before) return            // identical pair → looks broken
    if (seen.has(p.after)) return               // dedupe by result
    seen.add(p.after)
    out.push({ before: p.before, after: p.after })
  }
  push(FALLBACK[cat])                            // guaranteed-correct lead
  for (const p of demoImages.value[cat] || []) {
    // Skip auto-generated inputs whose before≈after (the recolor /
    // clean-white-input seeds the old overrides special-cased one by one).
    if (/piapi_[0-9a-f]+\.|\/ps\/bubbletea\.|\/fx\/bubbletea\./.test(p.before || '')) continue
    push(p)
  }
  return out.slice(0, n)
}

// Which example index is showing in the hero card and each deep-dive row.
const activeExampleIdx = ref(0)
const heroExamples = computed(() => demoList(activeDemoTab.value, 4))
const deepDiveIdx = ref<Record<string, number>>({})
function ddExamples(cat: string) { return demoList(cat, 4) }
function setDeepDiveIdx(key: string, idx: number) { deepDiveIdx.value[key] = idx }
let heroTabTimer: ReturnType<typeof setInterval> | null = null

async function loadDemos() {
  // Primary source: /api/v1/hero/pairs — curated, admin-managed mapping
  // that guarantees BEFORE/AFTER use the SAME subject (no cup-swap, no
  // person-swap). The admin regen endpoint repopulates AFTER through
  // gemini-2.5-flash-image with a "preserve subject EXACTLY" prompt, so
  // these pairs stay correct over time even when underlying provider
  // results drift. Falls through to the legacy /demo/presets path when
  // the hero table is empty (fresh deploy, before first regen).
  try {
    const heroResp = await import('@/api/client').then(m =>
      m.default.get('/api/v1/hero/pairs'),
    )
    const pairs: Array<{ tool_type: string; before_url: string; after_url: string }>
      = heroResp?.data?.pairs || []
    if (pairs.length > 0) {
      const grouped: Record<string, { before: string; after: string }[]> = {}
      for (const p of pairs) {
        if (!p.after_url) continue
        (grouped[p.tool_type] ||= []).push({ before: p.before_url, after: p.after_url })
      }
      demoImages.value = grouped
      demoLoading.value = false
      // Still poll the legacy presets path below for any tool the admin
      // hasn't regenerated yet, so missing rows fall through to the old
      // demo path rather than blanking out the hero card.
    }
  } catch {
    /* fall through to legacy demo presets */
  }

  const results = await Promise.allSettled(
    demoCats.map(cat =>
      import('@/api/client').then(m => m.default.get(`/api/v1/demo/presets/${cat}?limit=8`))
    )
  )
  // Try-on Materials store input_image_url = the GARMENT (e.g. a flat coat
  // photo). The hero pair we want is "garment alone → model wearing it",
  // which matches what the input_image_url already provides — so no
  // override is needed.
  results.forEach((r, i) => {
    if (r.status === 'fulfilled' && r.value?.data?.presets?.length) {
      const cat = demoCats[i]
      // Don't clobber a curated hero pair from /hero/pairs above — only
      // backfill tools that the hero table didn't return.
      if (demoImages.value[cat]?.length) return
      demoImages.value[cat] = r.value.data.presets
        .filter((p: any) => p.result_watermarked_url || p.result_image_url || p.thumbnail_url)
        .map((p: any) => ({
          before: p.input_image_url || '',
          after: p.result_watermarked_url || p.result_image_url || p.thumbnail_url || '',
        }))
    }
  })
  demoLoading.value = false

  const sparse = demoCats.filter(c => (demoImages.value[c]?.length || 0) < 2)
  if (sparse.length > 0 && !pollTimer) {
    pollTimer = setInterval(async () => {
      await loadDemos()
      const stillSparse = demoCats.filter(c => (demoImages.value[c]?.length || 0) < 2)
      if (stillSparse.length === 0 && pollTimer) {
        clearInterval(pollTimer)
        pollTimer = null
      }
    }, 60000)
  }
}

interface LandingTool {
  id: string
  route: string
  emoji: string
  color: string
  tag: string
  nameKey?: string
  descKey?: string
}

// ── All AI Creation Tools ──
const allTools: LandingTool[] = [
  { id: 'tryOn',           route: '/tools/try-on',             emoji: '👗', color: '#eb2f96', tag: 'Hot' },
  { id: 'fashionReels',    route: '/tools/short-video',        emoji: '🎬', color: '#1677ff', tag: 'Hot' },
  { id: 'productAvatars',  route: '/tools/avatar',             emoji: '🗣️', color: '#722ed1', tag: 'New' },
  { id: 'productAnyshoot', route: '/tools/product-scene',      emoji: '📸', color: '#fa8c16', tag: '' },
  { id: 'bgRemoval',       route: '/tools/background-removal', emoji: '✂️', color: '#08979c', tag: 'Free' },
  { id: 'roomRedesign',    route: '/tools/room-redesign',      emoji: '🏠', color: '#52c41a', tag: '' },
  { id: 'hdUpscale',       route: '/tools/upscale',            emoji: '🔍', color: '#13c2c2', tag: 'New' },
  { id: 'patternGenerate', route: '/tools/pattern-generate',   emoji: '▦', color: '#f759ab', tag: '' },
]

function toolName(tool: LandingTool): string {
  return t(tool.nameKey || `lp.allTools.${tool.id}.name`)
}

const isZhLocale = computed(() => String(locale.value || '').startsWith('zh'))

const _toolRouteMap: Record<string, string> = {
  'midjourney-imagine':     '/tools/midjourney-imagine',
  'kling-video':            '/tools/kling-video',
  'try-on':                 '/tools/try-on',
  'room-redesign':          '/tools/room-redesign',
  'pattern-generate':       '/tools/pattern-generate',
  'product-scene-classic':  '/tools/product-scene-classic',
  'short-video':            '/tools/short-video',
  'claymation':             '/tools/claymation',
  'ai-avatar':              '/tools/avatar',
  'image-upscale':          '/tools/upscale',
  'background-removal':     '/tools/background-removal',
}

// 5-language tool display labels. Indexed by tool key; values supply
// translations for all supported locales so ja/ko/es viewers never fall
// through to the English label (BUG-017).
interface ToolDisplayName { zh: string; en: string; ja: string; ko: string; es: string }
const _toolDisplayName: Record<string, ToolDisplayName> = {
  'midjourney-imagine':    { zh: 'AI 圖片生成',  en: 'AI Image Generation', ja: 'AI画像生成',         ko: 'AI 이미지 생성',  es: 'Generación de imágenes IA' },
  'kling-video':           { zh: 'Kling 影片',   en: 'Kling Video',         ja: 'Kling 動画',          ko: 'Kling 비디오',    es: 'Video Kling' },
  'try-on':                { zh: '虛擬試穿',     en: 'Virtual Try-On',      ja: 'バーチャル試着',       ko: '가상 피팅',       es: 'Probador virtual' },
  'room-redesign':         { zh: '室內設計',     en: 'Room Redesign',       ja: 'インテリアリデザイン', ko: '룸 리디자인',     es: 'Rediseño de habitaciones' },
  'pattern-generate':      { zh: '花紋設計',     en: 'Pattern Design',      ja: 'パターンデザイン',     ko: '패턴 디자인',     es: 'Diseño de patrones' },
  'product-scene-classic': { zh: '商品場景',     en: 'Product Scene',       ja: '商品シーン',           ko: '제품 장면',       es: 'Escena de producto' },
  'short-video':           { zh: '短影音',       en: 'Short Video',         ja: 'ショート動画',         ko: '쇼트 비디오',     es: 'Video corto' },
  'claymation':            { zh: '黏土風',       en: 'Claymation',          ja: 'クレイメーション',     ko: '클레이메이션',    es: 'Estilo plastilina' },
  'ai-avatar':             { zh: 'AI 數位人',    en: 'AI Avatar',           ja: 'AIアバター',           ko: 'AI 아바타',       es: 'Avatar IA' },
  'image-upscale':         { zh: '高清放大',     en: 'Image Upscale',       ja: '高解像度化',           ko: '이미지 업스케일', es: 'Ampliación HD' },
  'background-removal':    { zh: '去背',         en: 'Background Removal',  ja: '背景除去',             ko: '배경 제거',       es: 'Quitar fondo' },
}

interface HighlightCard {
  toolKey: string
  toolName: string
  route: string
  category: string
  promptText: string
}

const landingHighlightCards = computed<HighlightCard[]>(() => {
  return LANDING_HIGHLIGHTS.map(h => {
    const list = TOOL_EXAMPLES[h.tool] || []
    const ex = list.find(e => e.id === h.example_id) || list[0]
    if (!ex) return null
    const fallback: ToolDisplayName = { zh: h.tool, en: h.tool, ja: h.tool, ko: h.tool, es: h.tool }
    const tn = _toolDisplayName[h.tool] || fallback
    // TOOL_EXAMPLES has only _zh / _en columns; ja/ko/es fall back to the
    // English copy (legible) rather than mixing with Chinese (BUG-017).
    return {
      toolKey: h.tool,
      toolName: L(tn.zh, tn.en, tn.ja, tn.ko, tn.es),
      route: _toolRouteMap[h.tool] || '/dashboard',
      category: isZhLocale.value ? ex.category_zh : ex.category_en,
      promptText: isZhLocale.value ? ex.prompt_zh : ex.prompt_en,
    }
  }).filter((x): x is HighlightCard => x !== null)
})

function toolDesc(tool: LandingTool): string {
  return t(tool.descKey || `lp.allTools.${tool.id}.desc`)
}

// ── Seasonal marketing scenarios ──
// Season → demo-material topic mapping for the "依照通路與檔期快速換場景"
// section. 2026-05-20 — dropped the generic `seasonal` fallback from
// spring/valentines/blackFriday. The materials DB currently has exactly
// one row tagged `topic=seasonal` and it's autumn-themed; before this
// change clicking 春季特賣 surfaced an autumn maple-leaf product shot,
// which read as a bug. Each tab now resolves against its own topic
// (plus the broader `holiday` group for the gift-driven seasons) and
// falls through to an honest empty state when no matching material
// exists — better than misleading the user with off-season imagery.
const seasons = ref([
  { id: 'spring', topics: ['spring'], active: false },
  { id: 'valentines', topics: ['valentines', 'holiday'], active: false },
  { id: 'blackFriday', topics: ['black_friday', 'holiday'], active: false },
  { id: 'christmas', topics: ['christmas', 'holiday'], active: false },
  { id: 'newYear', topics: ['new_year', 'holiday'], active: true },
])
const activeSeason = ref('newYear')
const seasonLoading = ref(true)

// Pre-generated season showcase data from API
interface SeasonItem { url: string; input_url: string; label: string }
const seasonData = ref<Record<string, SeasonItem[]>>({})

function compactLabel(value: string): string {
  return value
    .replace(/\s*\|\s*Scene:.*/i, '')
    .replace(/\s*\|\s*場景[:：].*/g, '')
    .replace(/棚拍產品照[:：]?\s*/g, '')
    .replace(/Studio product photo of\s*/i, '')
    .replace(/，.*$/g, '')
    .replace(/,.*$/g, '')
    .trim()
}

// Map raw English product_name from the backend to a localized, professional
// display name. Falls back to the raw name if no translation exists.
function localizedProductName(rawName: string | undefined | null): string {
  if (!rawName) return ''
  const key = `lp.productNames.${rawName}`
  const translated = t(key)
  // vue-i18n returns the key itself when no translation is found
  return translated && translated !== key ? translated : rawName
}

function seasonLabel(preset: any, seasonId?: string): string {
  const params = preset.input_params || {}
  const isZh = locale.value.startsWith('zh')
  // Resolution order: zh-locale uses _zh; everyone else picks the raw
  // product_name (English) and we then route it through
  // localizedProductName() which keys into the i18n catalogue
  // (lp.productNames.*) — so ja/ko/es get their localized label when one
  // exists, instead of always reading the English DB field (BUG-017).
  const rawName =
    (isZh ? params.product_name_zh : null) ||
    params.product_name ||
    params.product_name_en ||
    ''
  const productName = localizedProductName(rawName) || (isZh
    ? preset.title_zh || preset.title_en
    : preset.title_en || preset.title_zh)
  const cleaned = compactLabel(productName || preset.prompt_en || preset.prompt || '')
  const seasonTag = seasonId ? t(`lp.seasons.${seasonId}`) : ''
  if (cleaned && seasonTag) return `${seasonTag} · ${cleaned}`
  return cleaned || seasonTag || t('lp.seasonShowcase')
}

// Neutral, untagged product_scene presets used to pad a thin seasonal grid.
// Most seasons have 0–1 topic-tagged materials, so a topic-only grid shows a
// single tile (or the empty state) even though the section advertises four.
// These generic studio shots are safe filler: the dropped-fallback note above
// was about off-SEASON imagery (an autumn shot under 春季), not neutral product
// photos — so we never borrow a sibling season's topic, only untagged scenes.
// Fetched once and shared across every tab.
let generalScenePromise: Promise<any[]> | null = null
function loadGeneralScenes(): Promise<any[]> {
  if (!generalScenePromise) {
    generalScenePromise = (async () => {
      try {
        const client = (await import('@/api/client')).default
        const resp = await client.get('/api/v1/demo/presets/product_scene?limit=8')
        return resp.data?.presets || []
      } catch {
        return []
      }
    })()
  }
  return generalScenePromise
}

// Memoize per-topic preset fetches (perf audit #6). The `holiday` topic is
// shared by 4 of the 5 seasons, so without this the same GET fired up to 4×.
const topicPresetCache = new Map<string, Promise<any[]>>()
function loadTopicPresets(topic: string): Promise<any[]> {
  let p = topicPresetCache.get(topic)
  if (!p) {
    p = (async () => {
      try {
        const client = (await import('@/api/client')).default
        const resp = await client.get(`/api/v1/demo/presets/product_scene?topic=${topic}&limit=4`)
        return resp.data?.presets || []
      } catch {
        return []
      }
    })()
    topicPresetCache.set(topic, p)
  }
  return p
}

async function loadSeasonPresets(seasonId: string) {
  const season = seasons.value.find(s => s.id === seasonId)
  if (!season || seasonData.value[seasonId]) return
  try {
    const topicResults = await Promise.all(season.topics.map(loadTopicPresets))
    const seen = new Set<string>()
    const tagged = topicResults.flat()
    // Season-tagged presets lead; neutral studio shots backfill so the grid is
    // never left with a lone tile (or empty) for the many seasons that have no
    // dedicated material yet.
    const presets = [...tagged, ...(await loadGeneralScenes())]
    seasonData.value[seasonId] = presets
      .filter((p: any) => p.result_watermarked_url || p.result_image_url || p.thumbnail_url)
      .filter((p: any) => {
        const key = p.id || p.result_image_url || p.thumbnail_url
        if (seen.has(key)) return false
        seen.add(key)
        return true
      })
      .slice(0, 4)
      .map((p: any) => ({
        url: p.result_watermarked_url || p.result_image_url || p.thumbnail_url || '',
        input_url: p.input_image_url || '',
        label: seasonLabel(p, seasonId),
      }))
  } catch {
    seasonData.value[seasonId] = []
  }
}

async function loadAllSeasonPresets() {
  // Load ONLY the active season on mount (perf audit #6) — the other seasons'
  // grids are below the fold and setActiveSeason() already lazy-loads a tab
  // when clicked. Previously all 5 loaded eagerly on the LCP page. If the
  // default season turns out empty, THEN probe the rest to auto-switch to one
  // that has content (preserves the original fallback behavior).
  seasonLoading.value = true
  await loadSeasonPresets(activeSeason.value)
  if (!seasonData.value[activeSeason.value]?.length) {
    await Promise.all(
      seasons.value.filter(s => s.id !== activeSeason.value).map(s => loadSeasonPresets(s.id))
    )
    const firstAvailable = seasons.value.find(season => (seasonData.value[season.id]?.length || 0) > 0)
    if (firstAvailable) setActiveSeason(firstAvailable.id)
  }
  seasonLoading.value = false
}

function setActiveSeason(id: string) {
  activeSeason.value = id
  seasons.value.forEach(s => s.active = s.id === id)
  loadSeasonPresets(id)
}

const availableSeasons = computed(() => {
  return seasons.value
})

const activeSeasonItems = computed(() => {
  return seasonData.value[activeSeason.value] || []
})

const interiorWorkflows = computed(() => tm('interior.studio.workflows') as Array<{ label: string; text: string }>)
const interiorStats = computed(() => tm('interior.studio.stats') as Array<{ value: string; label: string }>)
// Price stays universal (NT$); name + credits localised.
const creditPackHighlights = computed(() => {
  const prices = ['NT$299', 'NT$499', 'NT$999']
  const items = tm('interior.studio.creditPacks') as Array<{ name: string; credits: string }>
  return items.map((it, i) => ({ ...it, price: prices[i] }))
})

// ── Before/After deep dives ──
const deepDiveDefs = [
  { key: 'tryOn',      route: '/tools/try-on',            cat: 'try_on',            accentColor: '#eb2f96' },
  { key: 'bgRemoval',  route: '/tools/background-removal', cat: 'background_removal', accentColor: '#13c2c2' },
  { key: 'room',       route: '/tools/room-redesign',      cat: 'room_redesign',     accentColor: '#52c41a' },
]

// ── Trust brands ──
const brands = ['WooCommerce', 'Amazon', 'Instagram', 'TikTok', 'Etsy', 'Walmart', 'Shopify', 'eBay']

// ── Success stories ──
const successStories = [
  { id: 'fashionBrand', icon: '👗' },
  { id: 'furnitureBrand', icon: '🛋️' },
  { id: 'techBrand', icon: '💻' },
  { id: 'ebikeBrand', icon: '🚲' },
]

function handleStartCreating() {
  router.push(authStore.isAuthenticated ? '/tools/try-on' : '/auth/register')
}

onMounted(() => {
  loadDemos()
  loadAllSeasonPresets()
  // Auto-rotate hero demo tabs every 4s
  heroTabTimer = setInterval(() => {
    const idx = heroDemoTabs.findIndex(t => t.key === activeDemoTab.value)
    activeDemoTab.value = heroDemoTabs[(idx + 1) % heroDemoTabs.length].key
    activeExampleIdx.value = 0
  }, 4000)
})
onUnmounted(() => {
  if (pollTimer) { clearInterval(pollTimer); pollTimer = null }
  if (heroTabTimer) { clearInterval(heroTabTimer); heroTabTimer = null }
})

watch(locale, () => { seasonData.value = {}; loadAllSeasonPresets() })
</script>

<template>
  <div class="commerce-page">

    <!-- ============================================================
            SECTION 1 — HERO (Demo-first SMB layout)
    ============================================================= -->
    <section class="commerce-hero relative pt-24 pb-16 md:pt-28 md:pb-20 overflow-hidden">
      <div class="hero-bg-orb hero-bg-orb-a"></div>
      <div class="hero-bg-orb hero-bg-orb-b"></div>
      <div class="hero-bg-orb hero-bg-orb-c"></div>
      <div class="hero-grid-pattern"></div>

      <div class="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="grid lg:grid-cols-12 gap-10 lg:gap-12 items-center">

          <!-- LEFT: Copy column -->
          <div class="lg:col-span-6 text-center lg:text-left">
            <div class="hero-eyebrow inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-semibold mb-6">
              <span class="w-1.5 h-1.5 rounded-full hero-eyebrow-dot"></span>
              {{ t('lp.badge') }}
            </div>
            <h1 class="hero-headline mb-5">
              <span class="hero-brand-mark">VidGo AI</span>
              <span class="hero-headline-main">{{ t('lp.headline') }}</span>
            </h1>
            <p class="hero-sub mb-6">
              {{ brandTagline || t('lp.sub1') }}
            </p>
            <p class="hero-sub-accent mb-8">
              {{ t('lp.sub2') }}
            </p>
            <div class="flex flex-col sm:flex-row items-center lg:items-start justify-center lg:justify-start gap-3 mb-6">
              <button @click="handleStartCreating" class="hero-cta-primary">
                {{ t('lp.ctaPrimary') }}
                <svg class="w-4 h-4 ml-1" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 7l5 5m0 0l-5 5m5-5H6"/></svg>
              </button>
              <RouterLink to="/pricing" class="hero-cta-secondary">
                {{ t('lp.ctaSecondary') }}
              </RouterLink>
            </div>
            <div class="flex flex-wrap items-center justify-center lg:justify-start gap-x-5 gap-y-2 text-sm hero-trust">
              <span class="flex items-center gap-1.5"><span class="hero-check">✓</span> {{ t('lp.trust1') }}</span>
              <span class="flex items-center gap-1.5"><span class="hero-check">✓</span> {{ t('lp.trust2') }}</span>
              <span class="flex items-center gap-1.5"><span class="hero-check">✓</span> {{ t('lp.trust3') }}</span>
            </div>
          </div>

          <!-- RIGHT: Interactive before/after demo -->
          <div class="lg:col-span-6">
            <div class="hero-demo-card">
              <div class="hero-demo-card-glow"></div>
              <div class="hero-demo-tabs">
                <button v-for="cat in heroDemoTabs" :key="cat.key"
                  class="hero-demo-tab" :class="{ 'is-active': activeDemoTab === cat.key }"
                  @click="activeDemoTab = cat.key; activeExampleIdx = 0">
                  {{ t(`lp.heroDemo.tabs.${cat.key}`) }}
                </button>
              </div>
              <div class="hero-demo-stage">
                <div class="hero-demo-pane">
                  <img :src="heroExamples[activeExampleIdx]?.before || FALLBACK[activeDemoTab]?.before" alt="Before" class="hero-demo-img" fetchpriority="high" decoding="async" width="512" height="512" @error="fallbackImg($event, activeDemoTab, 'before')" />
                  <span class="hero-demo-badge hero-demo-badge-before">{{ t('lp.heroDemo.before') }}</span>
                </div>
                <div class="hero-demo-pane">
                  <img :src="heroExamples[activeExampleIdx]?.after || FALLBACK[activeDemoTab]?.after" alt="After" class="hero-demo-img" fetchpriority="high" decoding="async" width="512" height="512" @error="fallbackImg($event, activeDemoTab, 'after')" />
                  <span class="hero-demo-badge hero-demo-badge-after">{{ t('lp.heroDemo.after') }}</span>
                </div>
              </div>
              <!-- Example selector — up to 4 real results for the active tab -->
              <div v-if="heroExamples.length > 1" class="hero-demo-thumbs">
                <button v-for="(ex, exIdx) in heroExamples" :key="exIdx" type="button"
                  class="hero-demo-thumb" :class="{ 'is-active': activeExampleIdx === exIdx }"
                  @click="activeExampleIdx = exIdx" :aria-label="`Example ${exIdx + 1}`">
                  <img loading="lazy" decoding="async" :src="ex.after" alt="" @error="fallbackImg($event, activeDemoTab, 'after')" />
                </button>
              </div>
              <div class="hero-demo-meta">
                <div class="hero-demo-meta-left">
                  <span class="hero-demo-dot"></span>
                  {{ t('lp.heroDemo.generatedIn') }}
                </div>
                <div class="hero-demo-meta-right">
                  {{ t('lp.heroDemo.poweredBy') }}
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
    </section>

    <!-- ============================================================
         SECTION 2 — TRUST BAR (Platform logos)
    ============================================================= -->
    <section class="py-10" style="border-top: 1px solid rgba(255,255,255,0.04); border-bottom: 1px solid rgba(255,255,255,0.04);">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <p class="text-center text-sm font-medium mb-6" style="color: #6b6b8a;"
          v-html="t('lp.trustBrands')"></p>
        <div class="overflow-hidden">
          <div class="flex items-center gap-12 marquee-track">
            <span v-for="(brand, i) in [...brands, ...brands]" :key="i"
              class="font-bold text-lg whitespace-nowrap flex-shrink-0"
              style="color: rgba(255,255,255,0.1);">{{ brand }}</span>
          </div>
        </div>
      </div>
    </section>

    <!-- ============================================================
         SECTION 2.5 — INTERIOR DESIGN FEATURED (reroom.ai inspiration)
         Added 2026-05-25. Room redesign is a flagship high-margin tool
         (premium-tier kling_omni / veo) that was buried in the generic
         tools grid below. Promoting it above the grid mirrors the
         conversion structure on tw.reroom.ai — visitors land, see a
         concrete before/after, and click straight into the tool.
    ============================================================= -->
    <section class="section-padding" style="background: var(--bg-section);">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="interior-featured">
          <!-- Left: copy + CTA -->
          <div class="interior-copy">
            <span class="interior-eyebrow">{{ t('lp.interior.eyebrow') }}</span>
            <h2 class="interior-title">{{ t('lp.interior.title') }}</h2>
            <p class="interior-body">{{ t('lp.interior.body') }}</p>
            <ul class="interior-bullets">
              <li>
                <span class="interior-bullet-dot"></span>
                <span>{{ t('lp.interior.bullet1') }}</span>
              </li>
              <li>
                <span class="interior-bullet-dot"></span>
                <span>{{ t('lp.interior.bullet2') }}</span>
              </li>
              <li>
                <span class="interior-bullet-dot"></span>
                <span>{{ t('lp.interior.bullet3') }}</span>
              </li>
            </ul>
            <div class="interior-cta-row">
              <RouterLink to="/tools/room-redesign" class="interior-cta-primary">
                {{ t('lp.interior.ctaPrimary') }}
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
                  <path d="M5 12h14M12 5l7 7-7 7"/>
                </svg>
              </RouterLink>
              <RouterLink to="/tools/interior-templates" class="interior-cta-secondary">
                {{ t('lp.interior.ctaSecondary') }}
              </RouterLink>
            </div>
          </div>

          <!-- Right: before/after preview. Static two-pane "BEFORE / AFTER"
               for now; an interactive slider can be slotted into this same
               .interior-preview slot in a future pass without touching the
               surrounding layout. -->
          <div class="interior-preview">
            <div class="interior-preview-pane interior-preview-before">
              <img
                loading="lazy" decoding="async"
                v-if="!interiorBeforeFailed"
                src="https://storage.googleapis.com/vidgo-media-vidgo-ai/static/landing/room-before.jpg"
                :alt="t('lp.interior.beforeAlt')"
                @error="interiorBeforeFailed = true"
              />
              <div v-else class="interior-preview-placeholder interior-preview-placeholder-before">
                <span aria-hidden="true">🛋️</span>
              </div>
              <span class="interior-preview-label">{{ t('lp.interior.beforeLabel') }}</span>
            </div>
            <div class="interior-preview-pane interior-preview-after">
              <img
                loading="lazy" decoding="async"
                v-if="!interiorAfterFailed"
                src="https://storage.googleapis.com/vidgo-media-vidgo-ai/static/landing/room-after.jpg"
                :alt="t('lp.interior.afterAlt')"
                @error="interiorAfterFailed = true"
              />
              <div v-else class="interior-preview-placeholder interior-preview-placeholder-after">
                <span aria-hidden="true">✨</span>
              </div>
              <span class="interior-preview-label interior-preview-label-after">{{ t('lp.interior.afterLabel') }}</span>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- ============================================================
         SECTION 3 — EXPLORE ALL AI CREATION TOOLS
    ============================================================= -->
    <section class="section-padding" style="background: var(--bg-section);">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="text-center mb-12">
          <h2 class="text-3xl md:text-4xl font-bold mb-4" style="color: #f5f5fa;">{{ t('lp.sec3Title') }}</h2>
          <p class="text-base md:text-lg max-w-2xl mx-auto" style="color: #9494b0;">{{ t('lp.sec3Sub') }}</p>
        </div>

        <div class="tool-grid">
          <RouterLink
            v-for="tool in allTools"
            :key="tool.id"
            :to="tool.route"
            class="tool-card group"
            :style="`--tool-color: ${tool.color};`"
          >
            <!-- Colored top accent bar -->
            <div class="tool-card-accent" :style="`background: linear-gradient(90deg, ${tool.color}, ${tool.color}88);`" />

            <!-- Badge -->
            <div v-if="tool.tag" class="tool-badge-wrap">
              <span v-if="tool.tag === 'Hot'"  class="badge-hot">{{ tool.tag }}</span>
              <span v-else-if="tool.tag === 'New'"  class="badge-new">{{ tool.tag }}</span>
              <span v-else-if="tool.tag === 'Free'" class="badge-free">{{ tool.tag }}</span>
              <span v-else class="badge-custom" :style="`background: ${tool.color}22; color: ${tool.color}; border: 1px solid ${tool.color}55;`">{{ tool.tag }}</span>
            </div>

            <!-- Icon -->
            <div
              class="tool-icon"
              :style="`background: ${tool.color}18; border: 1.5px solid ${tool.color}30;`"
            >
              <span class="tool-emoji">{{ tool.emoji }}</span>
            </div>

            <!-- Text -->
            <div class="tool-name">{{ toolName(tool) }}</div>
            <div class="tool-desc">{{ toolDesc(tool) }}</div>

            <!-- Arrow (appears on hover) -->
            <div class="tool-arrow">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
                <path d="M5 12h14M12 5l7 7-7 7"/>
              </svg>
            </div>
          </RouterLink>
        </div>
      </div>
    </section>

    <!-- ============================================================
         SECTION 4 — GENERATE ENDLESS POSSIBILITIES (Category showcase)
    ============================================================= -->
    <section class="section-padding" style="background: var(--bg-section-alt);">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="text-center mb-12">
          <h2 class="text-3xl md:text-4xl font-bold mb-4" style="color: #f5f5fa;">{{ t('lp.sec4Title') }}</h2>
          <p class="text-base md:text-lg max-w-2xl mx-auto" style="color: #9494b0;">{{ t('lp.sec4Sub') }}</p>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
          <!-- Card 1: Fashion AI -->
          <div class="rounded-2xl overflow-hidden transition-all duration-300 hover:-translate-y-1"
            style="background: var(--bg-card); border: 1px solid var(--border-subtle);">
            <div class="h-48 overflow-hidden relative">
              <img loading="lazy" decoding="async" :src="demo('try_on', 'after') || FALLBACK.try_on.after"
                alt="Fashion AI" class="w-full h-full object-cover" @error="fallbackImg($event, 'try_on', 'after')" />
              <div class="absolute inset-0" style="background: linear-gradient(to top, #1c1c1c 0%, transparent 60%);"></div>
              <div class="absolute bottom-4 left-4 text-white font-bold text-lg">{{ t('lp.categories.fashionAI') }}</div>
            </div>
            <div class="p-5">
              <p class="text-sm mb-4" style="color: #9494b0;">{{ t('lp.categories.fashionAIDesc') }}</p>
              <div class="space-y-2">
                <RouterLink to="/tools/try-on" class="flex items-center gap-2 text-sm font-medium transition-colors" style="color: #c4c4d8;" @mouseenter="($event.target as HTMLElement).style.color='#f59e0b'" @mouseleave="($event.target as HTMLElement).style.color='#a8a29e'">
                  <span>👗</span> {{ t('lp.allTools.tryOn.name') }}
                  <svg class="w-3 h-3 ml-auto" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
                </RouterLink>
                <RouterLink to="/tools/short-video" class="flex items-center gap-2 text-sm font-medium transition-colors" style="color: #c4c4d8;" @mouseenter="($event.target as HTMLElement).style.color='#f59e0b'" @mouseleave="($event.target as HTMLElement).style.color='#a8a29e'">
                  <span>🎬</span> {{ t('lp.allTools.fashionReels.name') }}
                  <svg class="w-3 h-3 ml-auto" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
                </RouterLink>
                <RouterLink to="/tools/avatar" class="flex items-center gap-2 text-sm font-medium transition-colors" style="color: #c4c4d8;" @mouseenter="($event.target as HTMLElement).style.color='#f59e0b'" @mouseleave="($event.target as HTMLElement).style.color='#a8a29e'">
                  <span>🗣️</span> {{ t('lp.allTools.productAvatars.name') }}
                  <svg class="w-3 h-3 ml-auto" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
                </RouterLink>
              </div>
            </div>
          </div>
          <!-- Card 2: E-commerce AI -->
          <div class="rounded-2xl overflow-hidden transition-all duration-300 hover:-translate-y-1"
            style="background: var(--bg-card); border: 1px solid var(--border-subtle);">
            <div class="h-48 overflow-hidden relative">
              <img loading="lazy" decoding="async" :src="demo('product_scene', 'after') || FALLBACK.product_scene.after"
                alt="E-commerce AI" class="w-full h-full object-cover" @error="fallbackImg($event, 'product_scene', 'after')" />
              <div class="absolute inset-0" style="background: linear-gradient(to top, #1c1c1c 0%, transparent 60%);"></div>
              <div class="absolute bottom-4 left-4 text-white font-bold text-lg">{{ t('lp.categories.ecommerceAI') }}</div>
            </div>
            <div class="p-5">
              <p class="text-sm mb-4" style="color: #9494b0;">{{ t('lp.categories.ecommerceAIDesc') }}</p>
              <div class="space-y-2">
                <RouterLink to="/tools/product-scene" class="flex items-center gap-2 text-sm font-medium transition-colors" style="color: #c4c4d8;" @mouseenter="($event.target as HTMLElement).style.color='#f59e0b'" @mouseleave="($event.target as HTMLElement).style.color='#a8a29e'">
                  <span>📸</span> {{ t('lp.allTools.productAnyshoot.name') }}
                  <svg class="w-3 h-3 ml-auto" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
                </RouterLink>
                <RouterLink to="/tools/background-removal" class="flex items-center gap-2 text-sm font-medium transition-colors" style="color: #c4c4d8;" @mouseenter="($event.target as HTMLElement).style.color='#f59e0b'" @mouseleave="($event.target as HTMLElement).style.color='#a8a29e'">
                  <span>✂️</span> {{ t('lp.allTools.bgRemoval.name') }}
                  <svg class="w-3 h-3 ml-auto" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
                </RouterLink>
                <RouterLink to="/tools/upscale" class="flex items-center gap-2 text-sm font-medium transition-colors" style="color: #c4c4d8;" @mouseenter="($event.target as HTMLElement).style.color='#f59e0b'" @mouseleave="($event.target as HTMLElement).style.color='#a8a29e'">
                  <span>🔍</span> {{ t('lp.allTools.hdUpscale.name') }}
                  <svg class="w-3 h-3 ml-auto" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
                </RouterLink>
                <RouterLink to="/tools/pattern-generate" class="flex items-center gap-2 text-sm font-medium transition-colors" style="color: #c4c4d8;" @mouseenter="($event.target as HTMLElement).style.color='#f59e0b'" @mouseleave="($event.target as HTMLElement).style.color='#a8a29e'">
                  <span>▦</span> {{ t('lp.allTools.patternGenerate.name') }}
                  <svg class="w-3 h-3 ml-auto" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
                </RouterLink>
              </div>
            </div>
          </div>
          <!-- Card 3: Design & Content AI -->
          <div class="rounded-2xl overflow-hidden transition-all duration-300 hover:-translate-y-1"
            style="background: var(--bg-card); border: 1px solid var(--border-subtle);">
            <div class="h-48 overflow-hidden relative">
              <img loading="lazy" decoding="async" :src="demo('room_redesign', 'after') || FALLBACK.room_redesign.after"
                alt="Design AI" class="w-full h-full object-cover" @error="fallbackImg($event, 'room_redesign', 'after')" />
              <div class="absolute inset-0" style="background: linear-gradient(to top, #1c1c1c 0%, transparent 60%);"></div>
              <div class="absolute bottom-4 left-4 text-white font-bold text-lg">{{ t('lp.categories.designAI') }}</div>
            </div>
            <div class="p-5">
              <p class="text-sm mb-4" style="color: #9494b0;">{{ t('lp.categories.designAIDesc') }}</p>
              <div class="space-y-2">
                <RouterLink to="/tools/room-redesign" class="flex items-center gap-2 text-sm font-medium transition-colors" style="color: #c4c4d8;" @mouseenter="($event.target as HTMLElement).style.color='#f59e0b'" @mouseleave="($event.target as HTMLElement).style.color='#a8a29e'">
                  <span>🏠</span> {{ t('lp.allTools.roomRedesign.name') }}
                  <svg class="w-3 h-3 ml-auto" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
                </RouterLink>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- ============================================================
         SECTION 4B — INTERIOR DESIGN STUDIO
    ============================================================= -->
    <section class="section-padding" style="background: var(--bg-section);">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="grid lg:grid-cols-12 gap-10 lg:gap-14 items-center">
          <div class="lg:col-span-6">
            <div class="grid grid-cols-2 gap-3 rounded-2xl overflow-hidden" style="box-shadow: 0 10px 48px rgba(0,0,0,0.45); border: 1px solid rgba(255,255,255,0.08);">
              <div class="relative overflow-hidden" style="aspect-ratio: 4/5; background: #141420;">
                <img loading="lazy" decoding="async" :src="demo('room_redesign', 'before') || FALLBACK.room_redesign.before"
                  alt="Interior before" class="w-full h-full object-cover" @error="fallbackImg($event, 'room_redesign', 'before')" />
                <div class="absolute top-3 left-3 px-2.5 py-1 rounded-md text-xs font-bold" style="background: rgba(0,0,0,0.62); color: #ffffff;">{{ t('interior.studio.beforeLabel') }}</div>
              </div>
              <div class="relative overflow-hidden" style="aspect-ratio: 4/5; background: #141420;">
                <img :src="demo('room_redesign', 'after') || FALLBACK.room_redesign.after"
                  alt="Interior render" class="w-full h-full object-cover" @error="fallbackImg($event, 'room_redesign', 'after')" />
                <div class="absolute top-3 left-3 px-2.5 py-1 rounded-md text-xs font-bold" style="background: #52c41a; color: #06120a;">{{ t('interior.studio.afterLabel') }}</div>
              </div>
            </div>
          </div>

          <div class="lg:col-span-6">
            <div class="inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-semibold mb-4" style="background: rgba(82,196,26,0.12); color: #95de64; border: 1px solid rgba(82,196,26,0.28);">
              {{ t('interior.studio.badge') }}
            </div>
            <h2 class="text-3xl md:text-4xl font-black mb-4" style="color: #f5f5fa;">
              {{ t('interior.studio.title') }}
            </h2>
            <p class="text-base leading-relaxed mb-8" style="color: #9494b0;">
              {{ t('interior.studio.description') }}
            </p>

            <div class="grid sm:grid-cols-2 gap-3 mb-8">
              <div v-for="item in interiorWorkflows" :key="item.label" class="rounded-xl p-4" style="background: rgba(255,255,255,0.035); border: 1px solid rgba(255,255,255,0.06);">
                <div class="font-semibold mb-1" style="color: #f5f5fa;">{{ item.label }}</div>
                <p class="text-sm leading-relaxed" style="color: #9494b0;">{{ item.text }}</p>
              </div>
            </div>

            <div class="grid grid-cols-1 sm:grid-cols-3 gap-3 mb-8">
              <div v-for="stat in interiorStats" :key="stat.value" class="text-center rounded-xl px-3 py-4" style="background: rgba(82,196,26,0.08); border: 1px solid rgba(82,196,26,0.18);">
                <div class="text-lg font-black" style="color: #95de64;">{{ stat.value }}</div>
                <div class="text-xs mt-1 leading-snug" style="color: #b7b7cc;">{{ stat.label }}</div>
              </div>
            </div>

            <div class="rounded-xl p-4 mb-8" style="background: rgba(22,119,255,0.07); border: 1px solid rgba(22,119,255,0.18);">
              <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 mb-3">
                <div>
                  <div class="text-sm font-semibold" style="color: #f5f5fa;">{{ t('interior.studio.creditPricingTitle') }}</div>
                  <p class="text-xs mt-1" style="color: #9494b0;">{{ t('interior.studio.creditPricingBody') }}</p>
                </div>
                <RouterLink to="/pricing#credit-packs" class="inline-flex items-center justify-center px-4 py-2 text-xs font-semibold rounded-lg" style="background: #1677ff; color: #ffffff;">
                  {{ t('interior.studio.viewPricing') }}
                </RouterLink>
              </div>
              <div class="grid grid-cols-1 sm:grid-cols-3 gap-2">
                <div v-for="pkg in creditPackHighlights" :key="pkg.name" class="rounded-lg px-3 py-2" style="background: rgba(0,0,0,0.18); border: 1px solid rgba(255,255,255,0.06);">
                  <div class="text-xs" style="color: #b7b7cc;">{{ pkg.name }}</div>
                  <div class="font-black" style="color: #f5f5fa;">{{ pkg.price }}</div>
                  <div class="text-xs" style="color: #9494b0;">{{ pkg.credits }}</div>
                </div>
              </div>
            </div>

            <div class="flex flex-col sm:flex-row gap-3">
              <RouterLink to="/tools/room-redesign" class="inline-flex items-center justify-center gap-2 px-6 py-3 text-sm font-semibold rounded-lg transition-all duration-200 hover:opacity-90" style="background: #52c41a; color: #06120a; box-shadow: 0 4px 16px rgba(82,196,26,0.26);">
                {{ t('interior.studio.startCta') }}
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 7l5 5m0 0l-5 5m5-5H6"/></svg>
              </RouterLink>
              <RouterLink to="/pricing" class="inline-flex items-center justify-center px-6 py-3 text-sm font-semibold rounded-lg transition-all duration-200" style="color: #c4c4d8; border: 1px solid rgba(255,255,255,0.12); background: rgba(255,255,255,0.035);">
                {{ t('interior.studio.viewCreditPacks') }}
              </RouterLink>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- ============================================================
         SECTION 5 — THE FIRST AI THAT TRULY UNDERSTANDS MARKETING
    ============================================================= -->
    <section class="section-padding" style="background: var(--bg-section);">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="text-center mb-12">
          <h2 class="text-3xl md:text-4xl font-bold mb-4" style="color: #f5f5fa;">{{ t('lp.sec5Title') }}</h2>
          <p class="text-base md:text-lg max-w-2xl mx-auto" style="color: #9494b0;">{{ t('lp.sec5Sub') }}</p>
        </div>
        <!-- Season tabs -->
        <div class="flex flex-wrap items-center justify-center gap-3 mb-10">
          <button v-for="season in availableSeasons" :key="season.id"
            @click="setActiveSeason(season.id)"
            class="px-5 py-2.5 rounded-full text-sm font-medium transition-all duration-200"
            :style="activeSeason === season.id
              ? 'background: #f59e0b; color: #0a0a0a; font-weight: 600; box-shadow: 0 4px 16px rgba(245,158,11,0.30);'
              : 'background: var(--bg-card); color: var(--text-secondary); border: 1px solid var(--border-light);'">
            {{ t('lp.seasons.' + season.id) }}
          </button>
        </div>
        <!-- Season tagline -->
        <p class="text-center text-sm md:text-base max-w-2xl mx-auto mb-8" style="color: #b8b8d0;">
          {{ t('lp.seasonsTagline.' + activeSeason) }}
        </p>
        <!-- Season showcase grid -->
        <div v-if="seasonLoading && activeSeasonItems.length === 0" class="grid grid-cols-2 md:grid-cols-4 gap-4">
          <div v-for="idx in 4" :key="idx"
            class="rounded-xl overflow-hidden relative"
            style="aspect-ratio: 3/4; background: var(--bg-card); border: 1px solid var(--border-subtle);">
            <div class="absolute inset-0 animate-pulse" style="background: linear-gradient(90deg, transparent, rgba(255,255,255,0.06), transparent);"></div>
          </div>
        </div>
        <div v-else-if="activeSeasonItems.length > 0" class="grid grid-cols-2 md:grid-cols-4 gap-4">
          <div v-for="(item, idx) in activeSeasonItems" :key="activeSeason + '-' + idx"
            class="rounded-xl overflow-hidden relative group cursor-pointer transition-all duration-300 hover:-translate-y-1"
            style="aspect-ratio: 3/4; background: #141420; border: 1px solid rgba(255,255,255,0.06);">
            <img loading="lazy" decoding="async" :src="item.url"
              :alt="item.label"
              class="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105"
              @error="($event.target as HTMLImageElement).src = FALLBACK.product_scene.after" />
            <div class="absolute inset-0" style="background: linear-gradient(to top, rgba(0,0,0,0.7) 0%, transparent 50%);"></div>
            <div class="absolute bottom-3 left-3 right-3">
              <span class="text-white text-xs font-medium px-2.5 py-1 rounded-md" style="background: rgba(255,255,255,0.1); backdrop-filter: blur(8px);">
                {{ item.label }}
              </span>
            </div>
          </div>
        </div>
        <div v-else class="rounded-xl p-8 text-center" style="background: #141420; border: 1px solid rgba(255,255,255,0.06); color: #9494b0;">
          {{ t('lp.seasonUnavailable') }}
        </div>
      </div>
    </section>

    <!-- ============================================================
         SECTION 6 — BEFORE/AFTER DEEP DIVES
    ============================================================= -->
    <section class="section-padding" style="background: var(--bg-section-alt);">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-20">
        <div v-for="(feature, i) in deepDiveDefs" :key="feature.key"
          class="flex flex-col lg:flex-row items-center gap-10 md:gap-16"
          :class="i % 2 === 1 ? 'lg:flex-row-reverse' : ''">
          <!-- Before/After image pair + up to 4 example selector -->
          <div class="lg:w-1/2 w-full">
            <div class="grid grid-cols-2 gap-3 rounded-2xl overflow-hidden" style="box-shadow: 0 8px 40px rgba(0,0,0,0.5);">
              <div class="relative overflow-hidden" style="aspect-ratio: 3/4;">
                <img loading="lazy" decoding="async" :src="ddExamples(feature.cat)[deepDiveIdx[feature.key] || 0]?.before || FALLBACK[feature.cat]?.before"
                  :alt="t('lp.deepDives.' + feature.key + '.before')" class="w-full h-full object-cover"
                  @error="fallbackImg($event, feature.cat, 'before')" />
                <div class="absolute top-3 left-3 px-2.5 py-1 rounded-md text-xs font-bold" style="background: rgba(0,0,0,0.6); backdrop-filter: blur(4px); color: #ffffff;">Before</div>
              </div>
              <div class="relative overflow-hidden" style="aspect-ratio: 3/4;">
                <img loading="lazy" decoding="async" :src="ddExamples(feature.cat)[deepDiveIdx[feature.key] || 0]?.after || FALLBACK[feature.cat]?.after"
                  :alt="t('lp.deepDives.' + feature.key + '.after')" class="w-full h-full object-cover"
                  @error="fallbackImg($event, feature.cat, 'after')" />
                <div class="absolute top-3 left-3 px-2.5 py-1 rounded-md text-xs font-bold" :style="'background: ' + feature.accentColor + '; color: #ffffff;'">After</div>
              </div>
            </div>
            <!-- Example thumbnails (up to 4) -->
            <div v-if="ddExamples(feature.cat).length > 1" class="dd-thumbs">
              <button v-for="(ex, exIdx) in ddExamples(feature.cat)" :key="exIdx" type="button"
                class="dd-thumb" :class="{ 'is-active': (deepDiveIdx[feature.key] || 0) === exIdx }"
                @click="setDeepDiveIdx(feature.key, exIdx)" :aria-label="`Example ${exIdx + 1}`"
                :style="(deepDiveIdx[feature.key] || 0) === exIdx ? ('border-color: ' + feature.accentColor) : ''">
                <img loading="lazy" decoding="async" :src="ex.after" alt="" class="w-full h-full object-cover" @error="fallbackImg($event, feature.cat, 'after')" />
              </button>
            </div>
          </div>
          <!-- Text -->
          <div class="lg:w-1/2 w-full">
            <div class="inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-semibold mb-4"
              :style="'background: ' + feature.accentColor + '15; color: ' + feature.accentColor + '; border: 1px solid ' + feature.accentColor + '30;'">
              AI Powered
            </div>
            <h3 class="text-2xl md:text-3xl font-black mb-4" style="color: #f5f5fa;">{{ t('lp.deepDives.' + feature.key + '.title') }}</h3>
            <p class="text-base leading-relaxed mb-8" style="color: #9494b0;">{{ t('lp.deepDives.' + feature.key + '.desc') }}</p>
            <RouterLink :to="feature.route"
              class="inline-flex items-center gap-2 px-6 py-3 text-white text-sm font-semibold rounded-lg transition-all duration-200 hover:opacity-90"
              :style="'background: ' + feature.accentColor + '; box-shadow: 0 4px 16px ' + feature.accentColor + '40;'">
              {{ t('lp.tryNow') }}
              <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 7l5 5m0 0l-5 5m5-5H6"/></svg>
            </RouterLink>
          </div>
        </div>
      </div>
    </section>

    <!-- ============================================================
         SECTION 8 — TESTIMONIALS
    ============================================================= -->
    <section class="section-padding" style="background: var(--bg-section-alt);">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="text-center mb-12">
          <h2 class="text-3xl md:text-4xl font-bold mb-4" style="color: #f5f5fa;">{{ t('lp.sec8Title') }}</h2>
          <p class="text-base md:text-lg max-w-xl mx-auto" style="color: #9494b0;">{{ t('lp.sec8Sub') }}</p>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5">
          <div v-for="(t2, idx) in (tm('lp.testimonials') as any[])" :key="idx"
            class="rounded-xl p-6 flex flex-col transition-all duration-300 hover:-translate-y-1"
            style="background: var(--bg-card); border: 1px solid var(--border-subtle);">
            <div class="flex gap-0.5 mb-4">
              <span v-for="s in 5" :key="s" class="text-base" style="color: #f59e0b;">★</span>
            </div>
            <p class="text-sm leading-relaxed flex-1 mb-5" style="color: #9494b0;">&ldquo;{{ t2.text }}&rdquo;</p>
            <div class="pt-4" style="border-top: 1px solid rgba(255,255,255,0.06);">
              <div class="flex items-center gap-3">
                <div class="w-10 h-10 rounded-full flex items-center justify-center text-sm font-bold text-white"
                  :style="'background: ' + ['#1677ff','#6366f1','#eb2f96','#fa8c16'][idx % 4]">
                  {{ t2.name.charAt(0) }}
                </div>
                <div>
                  <div class="font-semibold text-sm" style="color: #e8e8f0;">{{ t2.name }}</div>
                  <div class="text-xs mt-0.5" style="color: #6b6b8a;">{{ t2.role }}</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- ============================================================
         SECTION 9 — CUSTOMER SUCCESS STORIES
    ============================================================= -->
    <section class="section-padding" style="background: var(--bg-section);">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="text-center mb-12">
          <h2 class="text-3xl md:text-4xl font-bold mb-4" style="color: #f5f5fa;">{{ t('lp.sec9Title') }}</h2>
          <p class="text-base md:text-lg max-w-xl mx-auto" style="color: #9494b0;">{{ t('lp.sec9Sub') }}</p>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div v-for="story in successStories" :key="story.id"
            class="group rounded-2xl overflow-hidden transition-all duration-300 hover:-translate-y-1"
            style="background: var(--bg-card); border: 1px solid var(--border-subtle);">
            <div class="p-6">
              <div class="flex items-center gap-3 mb-4">
                <span class="text-2xl">{{ story.icon }}</span>
                <div>
                  <div class="font-bold text-base" style="color: #e8e8f0;">{{ t('lp.stories.' + story.id + '.brand') }}</div>
                  <div class="text-xs" style="color: #6b6b8a;">{{ t('lp.stories.' + story.id + '.role') }}</div>
                </div>
              </div>
              <h4 class="font-bold text-lg mb-3" style="color: #f5f5fa;">{{ t('lp.stories.' + story.id + '.title') }}</h4>
              <p class="text-sm leading-relaxed mb-4" style="color: #9494b0;">{{ t('lp.stories.' + story.id + '.quote') }}</p>
              <button class="inline-flex items-center gap-1 text-sm font-semibold transition-colors hover:opacity-80" style="color: #1677ff;">
                {{ t('lp.readStory') }}
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
              </button>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- ============================================================
         SECTION 10 — STATS (Why Choose VidGo AI)
    ============================================================= -->
    <section class="py-20 relative overflow-hidden">
      <div class="absolute inset-0" style="background: linear-gradient(135deg, #0f1830, #141420);"></div>
      <div class="absolute inset-0 bg-mesh"></div>
      <div class="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="text-center mb-12">
          <h2 class="text-2xl md:text-3xl font-bold mb-3" style="color: #f5f5fa;">{{ t('lp.sec10Title') }}</h2>
          <p class="text-base" style="color: #9494b0;">{{ t('lp.sec10Sub') }}</p>
        </div>
        <div class="grid grid-cols-2 md:grid-cols-4 gap-8 mb-12">
          <div v-for="(stat, idx) in (tm('lp.stats') as any[])" :key="idx" class="text-center">
            <div class="text-4xl md:text-5xl font-black mb-2 gradient-text">{{ stat.value }}</div>
            <div class="text-sm font-medium" style="color: #9494b0;">{{ stat.label }}</div>
          </div>
        </div>
      </div>
    </section>

    <!-- ============================================================
         PROMPT HIGHLIGHTS — one cherry-picked example per tool
    ============================================================= -->
    <section class="py-20 relative">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="text-center mb-10">
          <h2 class="text-3xl md:text-4xl font-black mb-3" style="color: #f5f5fa;">
            {{ L(
              '靈感範例 · 12 種一鍵試做',
              'Prompt Highlights · 12 Ideas to Try',
              'プロンプト集 · 12 アイデア',
              '프롬프트 모음 · 12가지 아이디어',
              'Destacados de prompts · 12 ideas',
            ) }}
          </h2>
          <p class="text-base max-w-2xl mx-auto" style="color: #9494b0;">
            {{ L(
              '從每個工具精選一組提示詞，點擊卡片直接前往對應工具開始創作。',
              'One cherry-picked prompt per tool — click any card to jump to that tool and start creating.',
              'ツールごとに厳選したプロンプト。カードをクリックして、そのツールで作成を始められます。',
              '도구별로 엄선된 프롬프트 한 가지. 카드를 클릭해 해당 도구로 바로 시작하세요.',
              'Una prompt destacada por herramienta: haz clic en cualquier tarjeta para abrirla.',
            ) }}
          </p>
        </div>
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
          <RouterLink
            v-for="h in landingHighlightCards"
            :key="h.toolKey"
            :to="h.route"
            class="rounded-xl p-4 flex flex-col gap-2 transition-all hover:scale-[1.02]"
            style="background: #141420; border: 1px solid rgba(255,255,255,0.08);"
          >
            <div class="flex items-center justify-between">
              <span class="text-xs font-semibold uppercase tracking-wide" style="color: #a78bfa;">{{ h.toolName }}</span>
              <span
                class="px-2 py-0.5 rounded text-[10px] font-medium"
                style="background: rgba(124,58,237,0.15); color: #c4b5fd;"
              >{{ h.category }}</span>
            </div>
            <p class="text-sm leading-snug flex-1" style="color: #e8e8f0;">{{ h.promptText }}</p>
            <span class="text-xs font-medium mt-1" style="color: #a78bfa;">
              {{ L('前往工具', 'Open tool', 'ツールを開く', '도구 열기', 'Abrir herramienta') }} →
            </span>
          </RouterLink>
        </div>
      </div>
    </section>

    <!-- ============================================================
         SECTION 11 — FINAL CTA
    ============================================================= -->
    <section class="py-20 relative overflow-hidden">
      <div class="absolute inset-0" style="background: radial-gradient(ellipse at center, rgba(22,119,255,0.08) 0%, #09090b 70%);"></div>
      <div class="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
        <h2 class="text-3xl md:text-5xl font-black mb-5" style="color: #f5f5fa;">{{ t('lp.ctaFinalTitle') }}</h2>
        <p class="text-lg mb-10 max-w-xl mx-auto" style="color: #9494b0;">{{ t('lp.ctaFinalSub') }}</p>
        <button @click="handleStartCreating"
          class="btn-accent px-10 py-4 font-bold text-base">
          {{ t('lp.ctaFinalBtn') }}
        </button>
        <p class="text-sm mt-4" style="color: #6b6b8a;">{{ t('lp.ctaFinalNote') }}</p>
      </div>
    </section>

  </div>
</template>

<style scoped>
/* ================================================================
   VidGo AI — Premium Dark AI Landing Page
   ================================================================ */

.section-padding {
  padding-top: 5rem;
  padding-bottom: 5rem;
}

/* ── Tool Grid ──────────────────────────────────────────────────── */
.tool-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 1rem;
}
@media (min-width: 640px)  { .tool-grid { grid-template-columns: repeat(3, 1fr); gap: 1.25rem; } }
@media (min-width: 900px)  { .tool-grid { grid-template-columns: repeat(4, 1fr); gap: 1.5rem; } }

/* ── Tool Card ──────────────────────────────────────────────────── */
.tool-card {
  position: relative;
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  padding: 1.375rem 1.375rem 1.125rem;
  border-radius: 18px;
  overflow: hidden;
  background: rgba(12, 12, 22, 0.85);
  border: 1px solid rgba(100, 80, 200, 0.12);
  cursor: pointer;
  text-decoration: none;
  transition: transform 0.25s ease, border-color 0.25s ease, box-shadow 0.25s ease, background 0.25s ease;
  min-height: 160px;
  backdrop-filter: blur(16px);
}
.tool-card::before {
  content: '';
  position: absolute; inset: 0;
  border-radius: 18px;
  background: radial-gradient(ellipse at top left, color-mix(in srgb, var(--tool-color) 8%, transparent), transparent 60%);
  opacity: 0;
  transition: opacity 0.3s ease;
  pointer-events: none;
}
.tool-card:hover {
  transform: translateY(-6px);
  background: rgba(16, 16, 30, 0.95);
  border-color: color-mix(in srgb, var(--tool-color) 50%, transparent);
  box-shadow:
    0 20px 60px rgba(0,0,0,0.6),
    0 0 0 1px color-mix(in srgb, var(--tool-color) 25%, transparent),
    0 0 40px color-mix(in srgb, var(--tool-color) 10%, transparent);
}
.tool-card:hover::before { opacity: 1; }

.tool-card-accent {
  position: absolute;
  top: 0; left: 0; right: 0;
  height: 2px;
  opacity: 0.9;
  border-radius: 18px 18px 0 0;
}

.tool-badge-wrap {
  position: absolute;
  top: 0.75rem; right: 0.75rem;
}
.badge-custom {
  display: inline-block;
  padding: 1px 7px;
  border-radius: 5px;
  font-size: 10px;
  font-weight: 700;
  letter-spacing: 0.03em;
}

.tool-icon {
  width: 52px; height: 52px;
  border-radius: 14px;
  display: flex;
  align-items: center; justify-content: center;
  margin-bottom: 0.875rem;
  transition: transform 0.25s ease, box-shadow 0.25s ease;
  flex-shrink: 0;
}
.tool-card:hover .tool-icon {
  transform: scale(1.1);
  box-shadow: 0 0 20px color-mix(in srgb, var(--tool-color) 35%, transparent);
}
.tool-emoji { font-size: 1.5rem; line-height: 1; }

.tool-name {
  font-size: 0.9375rem;
  font-weight: 650;
  color: #e8e8f8;
  margin-bottom: 0.35rem;
  line-height: 1.3;
}
.tool-desc {
  font-size: 0.8125rem;
  color: #6868a0;
  line-height: 1.55;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
  flex: 1;
  transition: color 0.2s ease;
}
.tool-card:hover .tool-desc { color: #a0a0c8; }

.tool-arrow {
  position: absolute;
  bottom: 0.875rem; right: 0.875rem;
  color: var(--tool-color);
  opacity: 0; transform: translateX(-6px);
  transition: opacity 0.22s ease, transform 0.22s ease;
}
.tool-card:hover .tool-arrow { opacity: 0.9; transform: translateX(0); }

/* ── Marquee ──────────────────────────────────────────────────── */
@keyframes marquee {
  0% { transform: translateX(0); }
  100% { transform: translateX(-50%); }
}
.marquee-track { animation: marquee 30s linear infinite; }

/* ================================================================
   DARK AI PREMIUM THEME
   ================================================================ */

.commerce-page {
  background: #07070f;
  color: #e8e8f8;
  --bg-page:        #07070f;
  --bg-section:     #09090f;
  --bg-section-alt: #0c0c18;
  --bg-card:        #0f0f1e;
  --bg-card-hover:  #141428;
  --bg-elevated:    #1a1a2e;
  --text-primary:   #e8e8f8;
  --text-secondary: #9898c0;
  --text-muted:     #5a5a80;
  --border-subtle:  rgba(100, 80, 220, 0.10);
  --border-light:   rgba(100, 80, 220, 0.16);
  --border-medium:  rgba(100, 80, 220, 0.24);
}

/* Reset text colors for dark theme */
.commerce-page,
.commerce-page p,
.commerce-page span,
.commerce-page li { color: inherit; }
.commerce-page h1, .commerce-page h2, .commerce-page h3,
.commerce-page h4, .commerce-page h5, .commerce-page h6 { color: #e8e8f8; }
.commerce-page a { color: inherit; }

/* Section backgrounds */
.commerce-page section { background: var(--bg-section) !important; }
.commerce-page section:nth-of-type(even) { background: var(--bg-section-alt) !important; }

/* Restore inline dark-friendly colors */
.commerce-page [style*="color: #f5f5fa"],
.commerce-page [style*="color: #e8e8f0"],
.commerce-page [style*="color: #c4c4d8"] { color: #e8e8f8 !important; }
.commerce-page [style*="color: #9494b0"],
.commerce-page [style*="color: #b8b8d0"] { color: #9898c0 !important; }
.commerce-page [style*="color: #6b6b8a"] { color: #6060a0 !important; }

/* Keep already-dark inline backgrounds as-is */
.commerce-page [style*="background: #141420"],
.commerce-page [style*="background: #0f0f17"],
.commerce-page [style*="background: #09090b"] {
  background: var(--bg-section-alt) !important;
  border-color: var(--border-subtle) !important;
}

/* Gradient text for stats & highlights */
.commerce-page :deep(.gradient-text) {
  background: linear-gradient(135deg, #f59e0b 0%, #a855f7 55%, #06b6d4 100%);
  -webkit-background-clip: text;
  background-clip: text;
  -webkit-text-fill-color: transparent;
  color: transparent;
}

.commerce-page :deep(.btn-secondary) {
  border-color: rgba(120,100,255,0.28);
  color: #d0d0f0;
  background: rgba(120,100,255,0.06);
}
.commerce-page :deep(.btn-secondary:hover) {
  border-color: #f59e0b;
  color: #f59e0b;
  background: rgba(245,158,11,0.06);
}

.commerce-page :deep(.bg-mesh) { display: block; }

/* ── Hero Section ─────────────────────────────────────────────── */
.commerce-hero {
  min-height: 700px;
  background: #07070f;
  border-bottom: 1px solid rgba(100, 80, 220, 0.08);
  position: relative;
  overflow: hidden;
}

/* ── Animated Aurora Orbs ─────────────────────────────────────── */
.hero-bg-orb {
  position: absolute;
  border-radius: 50%;
  filter: blur(100px);
  pointer-events: none;
  z-index: 0;
}
.hero-bg-orb-a {
  width: 650px; height: 650px;
  top: -200px; left: -200px;
  background: radial-gradient(circle, rgba(124, 58, 237, 0.45), rgba(99, 102, 241, 0.25), transparent 65%);
  animation: orb-drift-a 14s ease-in-out infinite;
}
.hero-bg-orb-b {
  width: 600px; height: 600px;
  bottom: -200px; right: -200px;
  background: radial-gradient(circle, rgba(6, 182, 212, 0.35), rgba(16, 185, 129, 0.18), transparent 65%);
  animation: orb-drift-b 16s ease-in-out infinite;
}
.hero-bg-orb-c {
  width: 400px; height: 400px;
  top: 40%; left: 50%;
  background: radial-gradient(circle, rgba(245, 158, 11, 0.12), transparent 65%);
  animation: orb-drift-c 20s ease-in-out infinite;
}

@keyframes orb-drift-a {
  0%, 100% { transform: translate(0, 0) scale(1); opacity: 0.55; }
  40%       { transform: translate(60px, 40px) scale(1.08); opacity: 0.65; }
  70%       { transform: translate(-30px, 70px) scale(0.93); opacity: 0.45; }
}
@keyframes orb-drift-b {
  0%, 100% { transform: translate(0, 0) scale(1); opacity: 0.5; }
  35%       { transform: translate(-50px, -40px) scale(1.1); opacity: 0.6; }
  65%       { transform: translate(40px, -60px) scale(0.9); opacity: 0.4; }
}
@keyframes orb-drift-c {
  0%, 100% { transform: translate(-50%, -50%) scale(1); opacity: 0.4; }
  50%       { transform: translate(-50%, -50%) scale(1.3); opacity: 0.2; }
}

/* ── Animated dot-grid ────────────────────────────────────────── */
.hero-grid-pattern {
  position: absolute; inset: 0; z-index: 0;
  pointer-events: none;
  background-image:
    radial-gradient(circle, rgba(120, 100, 255, 0.35) 1px, transparent 1px);
  background-size: 36px 36px;
  mask-image: radial-gradient(ellipse 80% 70% at 50% 50%, black 20%, transparent 90%);
  animation: grid-fade 8s ease-in-out infinite;
}
@keyframes grid-fade {
  0%, 100% { opacity: 0.3; }
  50%       { opacity: 0.55; }
}

/* ── Hero Eyebrow Badge ───────────────────────────────────────── */
.hero-eyebrow {
  background: rgba(124, 58, 237, 0.14);
  color: #c4b5fd;
  border: 1px solid rgba(124, 58, 237, 0.30);
  letter-spacing: 0.05em;
  text-transform: uppercase;
}
.hero-eyebrow-dot {
  background: #a78bfa;
  box-shadow: 0 0 0 4px rgba(124, 58, 237, 0.22), 0 0 10px rgba(167, 139, 250, 0.5);
  animation: pulse-dot 2s ease-in-out infinite;
}
@keyframes pulse-dot {
  0%, 100% { transform: scale(1); opacity: 1; }
  50%       { transform: scale(1.5); opacity: 0.5; }
}

/* ── Hero Headline ────────────────────────────────────────────── */
.hero-headline {
  font-family: 'Syne', system-ui, sans-serif;
  font-weight: 800;
  line-height: 1.05;
  color: #f0f0fa;
  display: flex; flex-direction: column; gap: 6px;
}
.hero-headline-main {
  font-size: clamp(2.25rem, 5vw, 3.75rem);
  color: #f0f0fa;
}

.commerce-page .hero-brand-mark {
  display: inline-block;
  font-size: clamp(1.1rem, 1.6vw, 1.35rem);
  font-weight: 800;
  letter-spacing: 0.04em;
  text-transform: uppercase;
  background: linear-gradient(135deg, #f59e0b 0%, #a855f7 50%, #06b6d4 100%);
  -webkit-background-clip: text;
  background-clip: text;
  -webkit-text-fill-color: transparent;
  color: transparent;
  margin-bottom: 4px;
  filter: drop-shadow(0 0 12px rgba(168, 85, 247, 0.35));
}

.hero-sub {
  font-size: 1.125rem;
  line-height: 1.65;
  color: #7878a8;
  max-width: 32rem;
}
.hero-sub-accent {
  font-size: 0.95rem;
  font-weight: 600;
  color: #c4b5fd;
  max-width: 32rem;
}

/* ── Hero CTAs ────────────────────────────────────────────────── */
.hero-cta-primary {
  display: inline-flex; align-items: center; justify-content: center;
  padding: 14px 32px;
  font-size: 0.95rem; font-weight: 700;
  color: #ffffff;
  background: linear-gradient(135deg, #f59e0b 0%, #ea580c 100%);
  border-radius: 10px;
  border: none;
  box-shadow: 0 12px 32px rgba(245, 158, 11, 0.35), 0 0 0 1px rgba(245,158,11,0.2), inset 0 1px 0 rgba(255,255,255,0.2);
  transition: transform .18s ease, box-shadow .18s ease, filter .18s ease;
  cursor: pointer;
}
.hero-cta-primary:hover {
  transform: translateY(-2px);
  box-shadow: 0 18px 44px rgba(245, 158, 11, 0.45), 0 0 24px rgba(245,158,11,0.2);
  filter: brightness(1.08);
}

.hero-cta-secondary {
  display: inline-flex; align-items: center; justify-content: center;
  padding: 14px 28px;
  font-size: 0.95rem; font-weight: 600;
  color: #c0c0e8;
  background: rgba(100, 80, 220, 0.10);
  border: 1.5px solid rgba(100, 80, 220, 0.28);
  border-radius: 10px;
  backdrop-filter: blur(12px);
  transition: all .18s ease;
}
.hero-cta-secondary:hover {
  border-color: rgba(167, 139, 250, 0.55);
  color: #f0f0fa;
  background: rgba(100, 80, 220, 0.18);
  box-shadow: 0 6px 24px rgba(124, 58, 237, 0.18);
}

.hero-trust { color: #5050a0; }
.hero-check {
  display: inline-flex; align-items: center; justify-content: center;
  width: 18px; height: 18px; border-radius: 999px;
  background: rgba(16, 185, 129, 0.15);
  color: #10b981; font-weight: 800;
  box-shadow: 0 0 8px rgba(16,185,129,0.2);
}

/* ── Demo Card — glassmorphism ────────────────────────────────── */
.hero-demo-card {
  position: relative;
  background: rgba(10, 10, 22, 0.75);
  border: 1px solid rgba(100, 80, 220, 0.20);
  border-radius: 24px;
  box-shadow:
    0 32px 80px -20px rgba(0, 0, 0, 0.8),
    0 0 60px rgba(124, 58, 237, 0.08),
    inset 0 1px 0 rgba(255,255,255,0.06);
  padding: 18px;
  overflow: hidden;
  backdrop-filter: blur(24px);
}
.hero-demo-card::before {
  content: '';
  position: absolute; inset: -1px;
  border-radius: 24px;
  padding: 1px;
  background: linear-gradient(135deg, rgba(124,58,237,0.55) 0%, rgba(6,182,212,0.30) 50%, transparent 75%);
  -webkit-mask: linear-gradient(#000 0 0) content-box, linear-gradient(#000 0 0);
  -webkit-mask-composite: xor;
          mask-composite: exclude;
  pointer-events: none;
}
.hero-demo-card-glow {
  position: absolute;
  inset: -30px;
  background: radial-gradient(ellipse at 50% 0%, rgba(124,58,237,0.15), transparent 65%);
  pointer-events: none; z-index: 0;
}

.hero-demo-tabs {
  display: flex; gap: 5px;
  padding: 4px;
  background: rgba(0, 0, 0, 0.35);
  border: 1px solid rgba(100, 80, 220, 0.12);
  border-radius: 11px;
  margin-bottom: 14px;
  overflow-x: auto;
  position: relative; z-index: 1;
}
.hero-demo-tab {
  flex: 1;
  padding: 8px 12px;
  font-size: 0.8rem; font-weight: 600;
  color: #5050a0;
  background: transparent;
  border: none;
  border-radius: 8px;
  cursor: pointer;
  transition: all .2s ease;
  white-space: nowrap;
}
.hero-demo-tab:hover { color: #b0b0e0; background: rgba(100,80,220,0.08); }
.hero-demo-tab.is-active {
  background: rgba(124, 58, 237, 0.22);
  color: #d4c0ff;
  box-shadow: 0 2px 10px rgba(124,58,237,0.22), 0 0 0 1px rgba(124,58,237,0.28);
}

.hero-demo-stage {
  display: grid; grid-template-columns: 1fr 1fr; gap: 10px;
  position: relative; z-index: 1;
}
.hero-demo-pane {
  position: relative;
  aspect-ratio: 1 / 1;
  border-radius: 14px;
  overflow: hidden;
  background: rgba(8, 8, 18, 0.6);
  border: 1px solid rgba(100, 80, 220, 0.14);
}
.hero-demo-img {
  width: 100%; height: 100%;
  object-fit: cover; display: block;
  transition: opacity .35s ease, transform .5s ease;
}
.hero-demo-pane:hover .hero-demo-img { transform: scale(1.04); }
.hero-demo-badge {
  position: absolute; top: 10px; left: 10px;
  padding: 4px 9px;
  font-size: 0.65rem; font-weight: 800;
  letter-spacing: 0.08em;
  border-radius: 6px;
  backdrop-filter: blur(10px);
}
.hero-demo-badge-before {
  background: rgba(0, 0, 0, 0.65);
  color: #c0c0e8;
  border: 1px solid rgba(255,255,255,0.08);
}
.hero-demo-badge-after {
  background: linear-gradient(135deg, #7c3aed, #06b6d4);
  color: #ffffff;
  box-shadow: 0 4px 14px rgba(124, 58, 237, 0.45);
}

.hero-demo-meta {
  display: flex; justify-content: space-between; align-items: center;
  margin-top: 14px; padding: 0 4px;
  font-size: 0.78rem; color: #505090;
  position: relative; z-index: 1;
}
.hero-demo-meta-left { display: inline-flex; align-items: center; gap: 8px; font-weight: 600; }
.hero-demo-meta-right { font-weight: 500; opacity: 0.6; }
.hero-demo-dot {
  width: 6px; height: 6px; border-radius: 50%;
  background: #10b981;
  box-shadow: 0 0 0 4px rgba(16, 185, 129, 0.18), 0 0 10px rgba(16,185,129,0.45);
  animation: pulse-dot 1.6s ease-in-out infinite;
}

/* Example selector thumbnails (hero card) */
.hero-demo-thumbs {
  display: flex; gap: 8px; margin-top: 12px;
  position: relative; z-index: 1;
}
.hero-demo-thumb {
  flex: 1 1 0; aspect-ratio: 1 / 1; max-width: 64px;
  padding: 0; border-radius: 9px; overflow: hidden; cursor: pointer;
  background: rgba(8, 8, 18, 0.6);
  border: 1px solid rgba(255,255,255,0.10);
  opacity: 0.55; transition: opacity .2s ease, border-color .2s ease, transform .2s ease;
}
.hero-demo-thumb img { width: 100%; height: 100%; object-fit: cover; display: block; }
.hero-demo-thumb:hover { opacity: 0.85; transform: translateY(-1px); }
.hero-demo-thumb.is-active {
  opacity: 1;
  border-color: #7c3aed;
  box-shadow: 0 0 0 1px #7c3aed, 0 4px 14px rgba(124, 58, 237, 0.35);
}

/* Example selector thumbnails (deep-dive rows) */
.dd-thumbs { display: flex; gap: 8px; margin-top: 12px; }
.dd-thumb {
  flex: 1 1 0; aspect-ratio: 1 / 1; max-width: 84px;
  padding: 0; border-radius: 10px; overflow: hidden; cursor: pointer;
  background: #141420;
  border: 2px solid rgba(255,255,255,0.10);
  opacity: 0.6; transition: opacity .2s ease, border-color .2s ease, transform .2s ease;
}
.dd-thumb:hover { opacity: 0.9; transform: translateY(-1px); }
.dd-thumb.is-active { opacity: 1; }

@media (max-width: 1024px) { .hero-demo-card { margin-top: 8px; } }
@media (max-width: 768px) {
  .commerce-hero { min-height: 0; }
  .hero-headline-main { font-size: 2rem; }
  .hero-demo-pane { aspect-ratio: 4 / 5; }
}

/* ─── Interior Design featured section (2026-05-25) ─────────────── */
.interior-featured {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 48px;
  align-items: center;
}

.interior-copy {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.interior-eyebrow {
  display: inline-flex;
  align-items: center;
  align-self: flex-start;
  gap: 6px;
  padding: 4px 12px;
  font-size: 12px;
  font-weight: 700;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: #ffffff;
  background: linear-gradient(135deg, #1677ff 0%, #7c3aed 100%);
  border-radius: 999px;
}

.interior-title {
  font-size: clamp(1.85rem, 3.5vw, 2.75rem);
  font-weight: 700;
  line-height: 1.15;
  color: #f5f5fa;
  letter-spacing: -0.01em;
  margin: 0;
}

.interior-body {
  font-size: 1.0625rem;
  line-height: 1.65;
  color: #c2c2d5;
  margin: 0;
  max-width: 52ch;
}

.interior-bullets {
  display: flex;
  flex-direction: column;
  gap: 10px;
  margin: 8px 0 4px;
  padding: 0;
  list-style: none;
}

.interior-bullets li {
  display: flex;
  align-items: flex-start;
  gap: 10px;
  font-size: 0.9375rem;
  color: #c2c2d5;
  line-height: 1.5;
}

.interior-bullet-dot {
  display: inline-block;
  width: 6px;
  height: 6px;
  border-radius: 999px;
  background: #1677ff;
  margin-top: 8px;
  flex-shrink: 0;
  box-shadow: 0 0 8px rgba(22, 119, 255, 0.5);
}

.interior-cta-row {
  display: flex;
  gap: 12px;
  flex-wrap: wrap;
  margin-top: 12px;
}

.interior-cta-primary {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  padding: 12px 22px;
  font-weight: 600;
  font-size: 0.9375rem;
  color: #ffffff;
  background: linear-gradient(135deg, #1677ff 0%, #7c3aed 100%);
  border-radius: 10px;
  transition: transform 0.18s ease, box-shadow 0.18s ease;
  box-shadow: 0 4px 16px rgba(22, 119, 255, 0.35);
}

.interior-cta-primary:hover {
  transform: translateY(-1px);
  box-shadow: 0 8px 24px rgba(22, 119, 255, 0.45);
}

.interior-cta-secondary {
  display: inline-flex;
  align-items: center;
  padding: 12px 22px;
  font-weight: 600;
  font-size: 0.9375rem;
  color: #f5f5fa;
  background: rgba(255, 255, 255, 0.04);
  border: 1px solid rgba(255, 255, 255, 0.10);
  border-radius: 10px;
  transition: background 0.18s ease, border-color 0.18s ease;
}

.interior-cta-secondary:hover {
  background: rgba(255, 255, 255, 0.08);
  border-color: rgba(22, 119, 255, 0.45);
}

.interior-preview {
  position: relative;
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 8px;
  padding: 8px;
  border-radius: 18px;
  background: linear-gradient(145deg, #141420 0%, #1a1a28 100%);
  border: 1px solid rgba(255, 255, 255, 0.06);
  box-shadow: 0 12px 36px rgba(0, 0, 0, 0.55);
}

.interior-preview-pane {
  position: relative;
  aspect-ratio: 3 / 4;
  border-radius: 12px;
  overflow: hidden;
  background: #0f0f17;
}

.interior-preview-pane img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  display: block;
}

.interior-preview-label {
  position: absolute;
  top: 10px;
  left: 10px;
  padding: 4px 10px;
  font-size: 11px;
  font-weight: 700;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: #ffffff;
  background: rgba(0, 0, 0, 0.55);
  border-radius: 999px;
  backdrop-filter: blur(4px);
}

.interior-preview-label-after {
  background: linear-gradient(135deg, #1677ff 0%, #7c3aed 100%);
}

.interior-preview-placeholder {
  position: absolute;
  inset: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 56px;
  color: rgba(245, 245, 250, 0.85);
}
.interior-preview-placeholder-before {
  background: linear-gradient(145deg, #1a1a28 0%, #232336 100%);
}
.interior-preview-placeholder-after {
  background: linear-gradient(135deg, rgba(22, 119, 255, 0.35) 0%, rgba(124, 58, 237, 0.35) 100%), #1a1a28;
}

@media (max-width: 900px) {
  .interior-featured { grid-template-columns: 1fr; gap: 32px; }
  .interior-preview-pane { aspect-ratio: 4 / 5; }
}
</style>
